export const legacyEnrollmentEnglishCopy: Record<string, string> = {
  '目前帳號尚未取得教練或管理員權限。': 'This account does not have coach or administrator access.',
  '測試報名者': 'Test applicant',
  '週一測試班': 'Monday test class',
  '測試資料': 'Test data',
  '驗證教練端報名流程': 'Verify the coach enrollment workflow',
  '獨立沙盒資料': 'Isolated sandbox data',
  '讀取教練課程權限失敗。': 'Unable to load coach course permissions.',
  'Supabase 尚未設定，暫時無法收集資料。': 'Supabase is not configured. Submissions are unavailable for now.',
  '報名來源無效。': 'Invalid enrollment source.',
  '請填寫信箱。': 'Enter an email address.',
  '銀行帳號後五碼必須是 5 位數字。': 'The last five bank account digits must contain exactly five numbers.',
  '請不要填寫完整銀行卡號、身分證號或信用卡資料；這裡只需要銀行帳號後五碼。': 'Enter only the last five bank account digits. Do not include full bank card, identity or credit card details.',
  '請先建立課程報名記錄，再更新同一筆匯款資料。': 'Create a course enrollment before updating its transfer details.',
  '請至少填寫一種聯絡方式。': 'Provide at least one contact method.',
  '報名資料提交失敗。': 'Unable to submit enrollment details.',
  '課程報名記錄已建立，但安全憑證產生失敗，請聯絡客服。': 'Your course enrollment was created, but its security token could not be generated. Contact support.',
  '課程報名安全憑證無效，請重新建立報名記錄。': 'The course enrollment security token is invalid. Create a new enrollment record.',
  '匯款資料更新失敗。': 'Unable to update transfer details.',
  '缺少報名資料 ID。': 'An enrollment record ID is required.',
  '狀態無效。': 'Invalid status.',
  '找不到測試報名資料。': 'Test enrollment not found.',
  '報名確認請由管理員或財務在後台處理。': 'Enrollment confirmation must be handled by an administrator or finance in the workspace.',
  '找不到報名資料。': 'Enrollment details not found.',
  '課程匯款只能由管理員在管理後台核對。': 'Only administrators can review course transfers in the administrator workspace.',
  '課程匯款必須由銀行對帳確認，不能直接改為已確認入帳。': 'Course transfers require bank reconciliation and cannot be marked paid directly.',
  '課程報名請使用「補件通知與紀錄」處理，避免覆蓋已完成的核對。': 'Use follow-up notifications and history for course enrollments to preserve completed reviews.',
  '這個班級已達目前設定的名額上限，不能再確認新的匯款。': 'This class has reached its capacity. Further payments cannot be confirmed.',
  '報名資料更新失敗。': 'Unable to update enrollment details.',
}
