export const adminDutyEnglishCopy: Record<string, string> = {
  '待設定課酬': 'Compensation not configured',
  '讀取教練到課資料失敗。': 'Unable to load coach attendance.',
  '待簽到': 'Awaiting check-in',
  '已請假，待安排代班': 'Leave approved; substitute needed',
  '請假核對': 'Leave review',
  '核准請假': 'Approve leave',
  '拒絕請假': 'Reject leave',
  '管理員代提請假': 'Leave requested by administrator',
  '請假待管理員安排': 'Leave awaiting administrator arrangements',
  '指定代班': 'Assign substitute',
  '管理員直接邀請代班': 'Substitute invited by administrator',
  '原教練邀請代班': 'Substitute invited by original coach',
  '確認代班': 'Confirm substitute',
  '緊急確認代班': 'Confirm emergency substitute',
  '接受管理員代班': 'Accepted administrator substitution',
  '拒絕管理員代班': 'Declined administrator substitution',
  '接受直接代班': 'Accepted direct substitution',
  '拒絕直接代班': 'Declined direct substitution',
  '管理員補登簽到': 'Check-in recorded by administrator',
  '教練本人簽到': 'Coach self check-in',
  '人工修正出勤': 'Correct attendance manually',
  '排班資料更新': 'Assignment updated',
  '更新失敗。': 'Update failed.',
  '請填寫原因。': 'Enter a reason.',
  '人工修正必須填寫原因。': 'A reason is required for manual corrections.',
  '網站驗收測試': 'Website acceptance test',
  '測試期間每 30 秒自動更新；這些紀錄不會進入正式出勤、點名、課酬或季度統計。': 'Updates every 30 seconds during the test. These records are excluded from official attendance, roll calls, compensation, and season statistics.',
  '尚未有人完成測試簽到。': 'No test check-ins yet.',
  '原定：': 'Scheduled: ',
  '實際：': 'Actual: ',
  '本筆原定教練：': 'Originally assigned coach: ',
  '角色：': 'Role: ',
  '排班：': 'Assignment: ',
  '代班已接受並生效': 'Substitution accepted and active',
  '原教練已邀請，待代班回覆': 'Invited by original coach; awaiting reply',
  '代班已拒絕，待重新邀請': 'Substitution declined; invite another coach',
  '請假待核對': 'Leave awaiting review',
  '請假已核准': 'Leave approved',
  '請假已拒絕': 'Leave rejected',
  '原定排班': 'Original assignment',
  '代班：': 'Substitute: ',
  '已接受': 'Accepted',
  '待回覆': 'Awaiting reply',
  '未安排': 'Not arranged',
  '簽到：': 'Check-in: ',
  '（人工修正）': '(Manually corrected)',
  '尚無記錄': 'No record yet',
  '請假原因：': 'Leave reason: ',
  '指定／更換代班': 'Assign / Change substitute',
  '最終確認代班': 'Finalize substitution',
  '最近稽核：': 'Latest audit: ',
  '關閉操作視窗': 'Close action dialog',
  '原定教練': 'Scheduled coach',
  '目前代班': 'Current substitute',
  '尚未指定': 'Not assigned yet',
  '請先在課次卡片選擇代班教練，再回到這裡確認指定。': 'Select a substitute on the session card, then return here to confirm the assignment.',
  '操作說明': 'Action note',
  '（可留空）': '(Optional)',
  '請填寫原因': 'Enter a reason',
  '可補充這次處理的原因': 'Optionally explain this action',
  '這項處理需要留下原因，方便日後核對。': 'A reason is required for future review.',
  '儲存後會保留操作人、時間與原因，方便日後追查。': 'The actor, time, and reason are recorded for future review.',
  '儲存中…': 'Saving…',
  '確認核准': 'Confirm approval',
  '確認拒絕': 'Confirm rejection',
  '確認指定': 'Confirm assignment',
  '確認緊急代班': 'Confirm emergency coverage',
  '關閉人工修正': 'Close manual correction',
  '簽到結果': 'Check-in result',
  '未到': 'Absent',
  '實際到課教練': 'Attending coach',
  '目前簽到時間': 'Current check-in time',
  '薪資狀態': 'Compensation status',
  '管理員修正原因 *': 'Administrator correction reason *',
  '請說明為何需要人工修正': 'Explain why a manual correction is needed',
  '儲存簽到': 'Save check-in',
}
