export const achievementEnglishCopy: Record<string, string> = {
  '好運跑班限定': 'Exclusive to Nurture Running Team',
  'SUB 系列榮耀徽章': 'SUB Series Achievement Badges',
  '每一步的汗水與堅持，都值得被紀念。': 'Every step of effort and persistence deserves to be remembered.',
  '完成賽事、達標成績，即可依申請資格取得專屬徽章，收藏每一次突破自己的榮耀時刻。': 'Finish a race and meet the required standard to apply for a badge, subject to eligibility. Celebrate each personal breakthrough.',
  '認識全系列': 'Explore the collection',
  '查看申請方式': 'How to apply',
  'SUB 系列榮耀徽章的誕生。': 'The story of the SUB Series.',
  '始於 2025 年，好運跑班以跑者追逐目標的歷程為靈感，打造專屬於跑班成員的 SUB 系列榮耀徽章。': 'Launched in 2025, the SUB Series was inspired by runners’ journeys toward their goals and created exclusively for Nurture Running Team members.',
  '從 2025 年初開始企劃設計，歷經數個月的反覆討論與製作，於 2025 年 4 月完成首批實體徽章，並於同年 6 月好運跑班週年慶首次頒發給達成目標的跑班學員，正式開啟 SUB 系列的第一個里程碑。': 'Planning and design began in early 2025. After months of discussion and production, the first badges were completed in April and awarded to qualifying runners at the team’s anniversary celebration in June, marking the first milestone of the SUB Series.',
  '整體設計採用黑、金、白三色，呈現簡約且高級的視覺風格，並以好運跑班 Logo 中具有代表性的 U 字馬蹄鐵作為系列核心元素，延伸出專屬於跑班的榮耀識別。每一款徽章皆融入不同的象徵圖騰，代表各自的挑戰與目標，讓每一次突破，都化為值得珍藏的榮耀。': 'The collection uses black, gold, and white for a simple, refined look. The U-shaped horseshoe from the Nurture Running Team logo anchors the design. Each badge adds its own symbol for a different challenge or goal, turning a breakthrough into something to treasure.',
  '自推出以來，SUB 系列陪伴許多跑者完成人生第一枚 SUB2、SUB4、突破 SUB3、達成 SUB100，甚至站上 BQ 的門檻。它所象徵的不只是完賽成績，更是無數個清晨、每一場訓練，以及一次次超越自我的見證。': 'Since its launch, the SUB Series has celebrated runners’ first SUB2 and SUB4 finishes, SUB3 and SUB100 breakthroughs, and progress toward Boston qualification. It represents more than a finish time: countless early mornings, training sessions, and personal breakthroughs.',
  '對好運跑班而言，SUB 系列榮耀徽章從來不只是一件紀念品，而是一份對努力的肯定。每一枚徽章，都承載著跑者一路走來的汗水、堅持與成長，也希望陪伴每一位跑者，收藏屬於自己的榮耀時刻。': 'For Nurture Running Team, these badges are more than souvenirs. They recognize the effort, persistence, and growth behind each runner’s journey and preserve a personal moment of achievement.',
  '全系列五款榮耀徽章': 'Five badges in the collection',
  '四款對應全馬與半馬達標標準，第五款 BQ Pride 獻給完成波士頓馬拉松的跑者。': 'Four badges recognize marathon and half marathon time standards. The fifth, BQ Pride, celebrates runners who have completed the Boston Marathon.',
  '全馬 SUB 3': 'Marathon SUB 3',
  '閃電征途': 'Lightning Journey',
  '閃電構成 SUB「3」，展現速度與爆發力；融入 U 型馬蹄鐵，象徵競速與好運並存。': 'Lightning forms the SUB “3”, expressing speed and power. The U-shaped horseshoe brings racing ambition and good fortune together.',
  '星芒點綴其中，代表在挑戰中持續突破閃耀。': 'Starbursts celebrate the breakthroughs that shine through every challenge.',
  '全馬 SUB 4': 'Marathon SUB 4',
  '成就之星': 'Star of Achievement',
  '放射光芒呈現 SUB「4」，象徵達標瞬間的榮耀時刻；光芒四射的設計，展現挑戰自我的能量。': 'Radiating light forms the SUB “4”, capturing the moment a goal is achieved and the energy of a personal challenge.',
  '每位跑者，都是為自己發光的一顆星。': 'Every runner is a star shining in their own way.',
  '半馬 SUB 100': 'Half Marathon SUB 100',
  '與影同行': 'Running with Your Shadow',
  '影子為主視覺，象徵一路上的陪伴與自我對話；SUB 字樣延伸形成「100」，代表為目標付出的努力。': 'A shadow represents companionship and self-reflection along the way. The SUB lettering extends into “100”, symbolizing the effort behind the goal.',
  '你不孤單，陪你到終點的，是一路堅持的自己。': 'You are not alone: your persistent self stays with you all the way to the finish.',
  '半馬 SUB 2': 'Half Marathon SUB 2',
  '飛躍跑道': 'Taking Flight',
  '跑道造型呈現 SUB「2」，日復一日的累積與訓練；每一圈都是汗水與堅持的軌跡。': 'A running track forms the SUB “2”, reflecting daily practice and progress. Every lap traces effort and persistence.',
  '斜向延伸如展翅飛翔，突破極限持續向前。': 'The rising shape suggests wings taking flight, pushing onward beyond previous limits.',
  '獻給真正完成波士頓馬拉松的你': 'For runners who have completed the Boston Marathon',
  '融合 U 型馬蹄鐵，象徵幸運與實力的累積；代表突破自我、邁向波士頓的榮耀門檻。這不只是成績，而是屬於你的堅持與驕傲。': 'The U-shaped horseshoe represents good fortune and fitness built over time, celebrating the journey toward Boston. It reflects not just a result, but your persistence and pride.',
  '申請資格': 'Eligibility',
  '提供當年度波士頓馬拉松正式完賽證明，經核對後依當期公告領取。': 'Provide official proof of finishing that year’s Boston Marathon. After verification, collect your badge according to the current announcement.',
  '每一次突破，都值得留下紀念。': 'Every breakthrough deserves a keepsake.',
  '達標紀念卡將與榮耀徽章一同記錄賽事與成績，讓每一次突破，不只停留在成績查詢頁，而是真正成為值得珍藏的回憶。': 'An achievement card records your race and result alongside the badge, turning a result on a webpage into a memory worth keeping.',
  '如何取得好運榮耀徽章': 'How to earn a Nurture achievement badge',
  '必須為好運跑班學員。': 'You must be a Nurture Running Team student.',
  '參加正式賽事，並達到對應的成績標準。': 'Complete an official race and meet the relevant time standard.',
  '成績須於加入好運跑班期間內達成。': 'The result must be achieved while enrolled with Nurture Running Team.',
  '向各班教練詢問及填寫申請表。': 'Ask your class coach and complete the application form.',
  '經過審核後通知，並於課堂或指定地點領取徽章。': 'After approval, you will be notified to collect the badge in class or at a designated location.',
  '每人每年限申請一款達標徽章；如同時符合多項資格，請擇一申請，且不得重複申請。每年度申請期間與領發安排不同，請以所屬跑班 LINE 群組的當期公告為準。': 'Each person may apply for one achievement badge per year. If you qualify for more than one, choose one; duplicate applications are not allowed. Application periods and collection arrangements vary by year. Follow the current announcement in your class LINE group.',
  '成績核對後才正式取得': 'Awarded after results are verified',
  '申請資料會依正式賽事成績與跑班成員資格核對。徽章不是報名贈品，也不能單獨購買。': 'Applications are checked against official race results and team membership. Badges are not registration gifts and cannot be purchased separately.',
  '查看你已經取得的徽章': 'View the badges you have earned',
  '登入個人帳戶後，可查看解鎖狀態與實際取得原因。': 'Sign in to see which badges are unlocked and why they were awarded.',
  '前往個人帳戶': 'Go to my account',
  '好運榮耀徽章與達標紀念卡全系列': 'The complete Nurture achievement badge and card collection',
  '手持全馬 SUB 3 好運榮耀徽章': 'Holding a Marathon SUB 3 achievement badge',
  '好運榮耀徽章全系列': 'The complete Nurture achievement badge collection',
  '全馬 SUB 3 閃電征途徽章': 'Marathon SUB 3 Lightning Journey badge',
  '全馬 SUB 4 成就之星徽章': 'Marathon SUB 4 Star of Achievement badge',
  '半馬 SUB 100 與影同行徽章': 'Half Marathon SUB 100 Running with Your Shadow badge',
  '半馬 SUB 2 飛躍跑道徽章': 'Half Marathon SUB 2 Taking Flight badge',
  'BQ Pride 波士頓馬拉松完賽徽章': 'BQ Pride Boston Marathon finisher badge',
  '好運榮耀徽章達標紀念卡': 'Nurture achievement cards',
  '全馬 SUB 3 達標紀念卡': 'Marathon SUB 3 achievement card',
  '全馬 SUB 4 達標紀念卡': 'Marathon SUB 4 achievement card',
  '半馬 SUB 100 達標紀念卡': 'Half Marathon SUB 100 achievement card',
  '半馬 SUB 2 達標紀念卡': 'Half Marathon SUB 2 achievement card',
  'BQ Pride 達標紀念卡': 'BQ Pride achievement card',
  '跑者手持好運榮耀徽章': 'A runner holding a Nurture achievement badge',
}
