// Complete server messages shown in account, enrollment and student workflows.
export const studentActionEnglishCopy: Record<string, string> = {
  '請填寫姓名。': 'Enter your name.',
  '找不到這個課程。': 'Course not found.',
  '請先登入後再查看匯款狀態。': 'Sign in to view your payment status.',
  '請登入原報名帳號後查看收款資訊。': 'Sign in with the account used to enroll to view payment details.',
  '匯款資料權限核對失敗。': 'Unable to verify access to payment details.',
  '找不到可存取的報名。': 'No accessible enrollment found.',
  '季度核對暫時無法完成。': 'Unable to verify the season right now.',
  '此季度已封存，請聯絡跑班確認款項。': 'This season is archived. Contact the team to confirm your payment.',
  '目前無法提供這個課程的匯款資料。': 'Payment details for this course are currently unavailable.',
  '完成課程資料與費用確認後，才可查看匯款資料。': 'Confirm your course details and fees to view payment instructions.',
  '匯款資料圖片目前無法讀取。': 'Unable to load the payment details image.',
  '目前尚未設定招生季度。': 'No enrollment season has been set up yet.',
  '課次設定讀取失敗。': 'Unable to load session settings.',
  '請先登入後再提交課程報名。': 'Sign in before submitting your course enrollment.',
  '無法確認這筆課程報名。': 'Unable to verify this course enrollment.',
  '本班目前已額滿，暫時無法建立新的報名記錄。': 'This class is full and cannot accept new enrollments right now.',
  '請完成學員與緊急聯絡人資料。': 'Complete the student and emergency contact details.',
  '請完成所有新生必填資料。': 'Complete all required details for new students.',
  '課程費用驗證失敗，請返回匯款步驟重新計算。': 'Unable to verify the course fee. Return to the payment step to recalculate it.',
  '課程報價已超過保留時間，請返回匯款步驟重新計算。': 'Your course quote has expired. Return to the payment step to recalculate it.',
  '請填寫正確的匯款帳號後五碼。': 'Enter the correct last five digits of the account used for the transfer.',
  '請完成電子發票資料。': 'Complete your e-invoice details.',
  '請閱讀並同意課程規範後再送出。': 'Read and agree to the class rules before submitting.',
  '備註中請勿填寫完整帳號、信用卡號或身分證號。': 'Do not include full bank account, credit card or identity numbers in your notes.',
  '建立網站報名記錄失敗。': 'Unable to create your website enrollment record.',
  '請使用網站課程報名表。': 'Use the course enrollment form on this website.',
  '請填寫正確的銀行帳號後五碼。': 'Enter the correct last five digits of your bank account.',
  '找不到可更新的報名記錄，或這筆報名不屬於目前帳號。': 'This enrollment could not be found or does not belong to your account.',
  '報名編號格式不正確。': 'Invalid enrollment ID format.',
  '報名狀態格式不正確。': 'Invalid enrollment status format.',
  '未指定季度': 'No season selected',
  '請重新開啟補件表單。': 'Reopen the form for additional information.',
  '已重新檢查郵件寄送狀態。': 'Email delivery status checked again.',
  '報名資料已更新，請重新整理。': 'The enrollment details have changed. Refresh to continue.',
  '補件要求與站內通知已保存；郵件狀態尚未確認，請重新整理後重試寄送。': 'The information request and website notification were saved. Email delivery is unconfirmed; refresh and retry sending.',
  '請填寫有效日期、後五碼與補充說明；勿填完整帳號或身分證號。': 'Enter a valid date, the last five account digits and additional details. Do not include a full account or identity number.',
  '通知服務尚未設定。': 'The notification service has not been configured.',
  '請先登入已驗證的帳號。': 'Sign in with a verified account first.',
  '隔離測試帳號不使用正式報名通知。': 'Isolated test accounts do not use live enrollment notifications.',
  '目前帳號沒有報名核對權限。': 'This account does not have permission to review enrollments.',
  '這筆報名已更新、已完成或季度已封存，請重新整理後再試。': 'This enrollment has changed, is complete, or belongs to an archived season. Refresh and try again.',
  '請檢查匯款日期、後五碼與補充說明。': 'Check the transfer date, last five account digits and additional details.',
  '通知服務暫時無法使用，請稍後重新整理。': 'Notifications are temporarily unavailable. Refresh again later.',
  '郵件服務尚未設定；站內通知已保存。': 'The email service is not configured. The website notification was saved.',
  '郵件發送未確認；站內通知仍有效，可安全重試。': 'Email delivery is unconfirmed. The website notification is still valid, and you can safely retry.',
  '請先登入學員帳號。': 'Sign in to your student account first.',
  '請先切換至學員測試模式。': 'Switch to student test mode first.',
  '目前沒有可使用的季度課程。': 'No season courses are currently available.',
  '找不到你的本季度課程資格。': 'No eligible enrollment found for this season.',
  '找不到所屬班級的課次設定。': 'Session settings for your class could not be found.',
  '隔離測試帳號不會寫入正式簽到，請使用測試資料庫驗收。': 'Isolated test accounts cannot create live check-ins. Use the test database for verification.',
  '無效的簽到課次。': 'Invalid check-in session.',
  '簽到已記錄，請等候教練現場核實。': 'Check-in recorded. Wait for your coach to verify attendance in person.',
  '請假課次不屬於測試班級。': 'This leave session does not belong to the test class.',
  '測試請假已送出，可繼續驗證本季度補課選擇；不會寫入正式名單。': 'Test leave submitted. You can test makeup selections for this season; the live roster is unchanged.',
  '找不到測試請假資料。': 'Test leave record not found.',
  '測試補課只能選擇本季度其他班級的有效課次。': 'Test makeup sessions must be valid sessions in another class in the same season.',
  '無法辨識這次測試點名操作。': 'Unrecognized test attendance action.',
  '測試補課已安排。': 'Test makeup session scheduled.',
  '測試補課已取消，可重新選擇。': 'Test makeup session cancelled. You can choose another session.',
  '測試請假已取消。': 'Test leave cancelled.',
  '請假課次不屬於你的班級。': 'This leave session does not belong to your class.',
  '本堂已經停課，不需要另行請假。': 'This session is cancelled. No leave request is needed.',
  '目前只能為最近一堂尚未開始的課程請假。': 'You can request leave only for your next upcoming session.',
  '本堂點名已經由教練確認，無法再改為請假。': 'Your coach has confirmed attendance for this session. It can no longer be changed to leave.',
  '請假已送出，你可以選擇原課次之後、本季度內其他班級的可用課次補課。': 'Leave submitted. Choose an available makeup session in another class after your original session and within the same season.',
  '找不到這筆請假與補課資料。': 'Leave and makeup record not found.',
  '補課只能選擇本季度的其他班級。': 'Makeup sessions must be in another class in the same season.',
  '原請假課次與你的所屬班級不一致。': 'The original leave session does not match your enrolled class.',
  '這一堂已達班級名額上限，請選擇其他補課課次。': 'This session is full. Choose another makeup session.',
  '補課課次已開始，無法再取消或更換。': 'The makeup session has started and cannot be cancelled or changed.',
  '這筆補課目前不在已安排狀態。': 'This makeup record does not currently have a scheduled session.',
  '已取消原補課安排，可以重新選擇其他課次。': 'Your makeup session was cancelled. You can choose another session.',
  '原課次已開始，無法再取消請假。': 'The original session has started. Leave can no longer be cancelled.',
  '本堂點名或補課已經確認，無法取消請假。': 'Attendance or makeup attendance has been confirmed. Leave cannot be cancelled.',
  '請假已取消，本堂恢復為待點名。': 'Leave cancelled. This session is awaiting attendance again.',
  '無法辨識這次點名操作。': 'Unrecognized attendance action.',
  '補課課次不在本季度課表內。': 'This makeup session is not on the current season schedule.',
  '補課課次不可超過本季度結束日。': 'The makeup session must take place on or before the last day of the season.',
  '補課只能選擇原請假課次之後的課程。': 'The makeup session must be after the original leave session.',
  '只能選擇尚未開始的補課課次。': 'Choose a makeup session that has not started yet.',
  '這一堂目前停課，請選擇其他補課課次。': 'This session is cancelled. Choose another makeup session.',
  '教練會在課程確認入帳後依報名班級自動關聯，不需手動綁定。': 'Your coach is linked automatically based on your enrolled class after payment is confirmed.',
  '新增賽事失敗。': 'Unable to add the race.',
  '缺少賽事 ID。': 'A race ID is required.',
  '請先完成匯款並回報後五碼；財務確認入帳後將自動開通課表。': 'Transfer payment and report the last five account digits. Your training plan unlocks automatically when finance confirms receipt.',
  'RPE 必須在 1 到 10 之間。': 'RPE must be between 1 and 10.',
  '這份課表不屬於目前學員，不能提交回饋。': 'This training plan does not belong to your account. Feedback cannot be submitted.',
  '完成第一次訓練回報': 'Submitted your first training report',
  '此教練帳號已由管理員停用。': 'This coach account has been disabled by an administrator.',
  '教練身份或登入信箱與其他帳號衝突，請聯絡管理員處理。': 'The coach identity or sign-in email conflicts with another account. Contact an administrator.',
  '請先完成登記信箱驗證，驗證後重新登入即可啟用教練帳號。': 'Verify your registered email, then sign in again to activate your coach account.',
  '教練帳號已登記，完成驗證後即可啟用。': 'Coach account registered. Complete verification to activate it.',
  '此帳號已在其他裝置登入，目前裝置已登出。': 'Your account was signed in on another device. You have been signed out on this device.',
  '更新帳號資料失敗。': 'Unable to update account details.',
  '讀取教練帳號狀態失敗。': 'Unable to load the coach account status.',
  '發票選項無效。': 'Invalid invoice option.',
  '手機條碼載具格式應為「/」加 7 位英數字。': 'Your mobile barcode must start with “/” followed by seven letters or digits.',
  '統一編號必須是 8 位數字。': 'The tax ID must contain eight digits.',
  '完成個人跑者資料': 'Completed your runner profile',
}
