// Complete API messages and fixed export labels used by administration workflows.
export const adminActionEnglishCopy: Record<string, string> = {
  '只有管理員可以管理教練到課紀錄。': 'Only administrators can manage coach attendance records.',
  '未命名帳號': 'Unnamed account',
  '讀取教練到課管理資料失敗。': 'Unable to load coach attendance management data.',
  '請假核對結果無效。': 'Invalid leave review result.',
  '這堂課目前沒有待核對的請假申請。': 'This session has no leave request awaiting review.',
  '本堂已停課，不能再核對請假。': 'This session is cancelled. Leave cannot be reviewed.',
  '本堂已完成簽到，不能再核對一般請假。': 'Check-in is complete. Regular leave requests can no longer be reviewed.',
  '拒絕請假時必須填寫原因。': 'Enter a reason for declining leave.',
  '課次已結束，核對請假必須填寫異常處理原因。': 'The session has ended. Enter an exception reason to review leave.',
  '請假狀態已過期或課次已結束，請重新整理後確認。': 'The leave status is outdated or the session has ended. Refresh to check.',
  '請假狀態已被其他操作更新，請重新整理。': 'Another action changed the leave status. Refresh to continue.',
  '請假已核准；代班仍須完成邀請、接受與最終確認。': 'Leave approved. Substitution still requires an invitation, acceptance and final confirmation.',
  '請假已拒絕，原定教練仍為本堂實際教練。': 'Leave declined. The scheduled coach remains assigned to teach this session.',
  '請選擇另一位教練作為代班。': 'Choose another coach as the substitute.',
  '代班帳號目前沒有啟用的教練權限。': 'The substitute account does not have active coach access.',
  '本堂已停課，不能安排或更換代班。': 'This session is cancelled. Substitutes cannot be assigned or changed.',
  '本堂已完成簽到，不能安排或更換代班。': 'Check-in is complete. Substitutes cannot be assigned or changed.',
  '開課後緊急指定或更換代班必須填寫原因。': 'Enter a reason for assigning or changing an emergency substitute after the session starts.',
  '課次狀態已結束或已變更；請填寫原因並重新整理後再處理。': 'The session has ended or its status has changed. Enter a reason and refresh before continuing.',
  '代班狀態已被其他操作更新，請重新整理。': 'Another action changed the substitution status. Refresh to continue.',
  '代班邀請已送出，等待代班教練回覆後再由管理員最終確認。': 'Substitution invitation sent. Wait for the coach to reply before final administrator confirmation.',
  '尚未指定代班教練。': 'No substitute coach has been assigned.',
  '代班教練尚未接受邀請，不能最終確認。': 'The substitute has not accepted the invitation. Final confirmation is unavailable.',
  '緊急代班確認必須填寫原因。': 'Enter a reason to confirm an emergency substitution.',
  '目前代班帳號已沒有啟用的教練權限。': 'The substitute account no longer has active coach access.',
  '本堂已停課，不能確認代班。': 'This session is cancelled. Substitution cannot be confirmed.',
  '課次已結束，請使用有原因的緊急確認。': 'The session has ended. Use emergency confirmation and provide a reason.',
  '課次狀態已過期，請重新整理後再處理。': 'The session status is outdated. Refresh before continuing.',
  '代班已最終確認；原教練權限已移除，代班教練可簽到並核實學員出席。': 'Substitution confirmed. The original coach’s session access was removed; the substitute can check in and verify student attendance.',
  '人工修正必須選擇狀態並填寫原因。': 'Select a status and enter a reason for the manual correction.',
  '出勤狀態已變更，請重新整理。': 'Attendance status has changed. Refresh to continue.',
  '出勤狀態已人工修正，操作人、時間與原因已保留。': 'Attendance corrected. The operator, time and reason were recorded.',
  '無法讀取登入帳號。': 'Unable to load sign-in accounts.',
  '登入帳號數量超過單次管理範圍，請稍後再試。': 'There are too many sign-in accounts to manage in one request. Try again later.',
  '教練帳號資料庫功能尚未更新，請先套用管理員審閱的 SQL。': 'Coach account database features need an update. Apply the administrator-reviewed SQL first.',
  '目前帳號沒有管理員權限。': 'This account does not have administrator access.',
  '找不到這筆教練帳號登記。': 'Coach account registration not found.',
  '這筆教練帳號已明確停用，請先由管理員重新啟用。': 'This coach account was disabled. An administrator must reactivate it first.',
  '此信箱尚未完成驗證，完成驗證後才能啟用教練帳號。': 'Verify this email address before activating the coach account.',
  '登入信箱與管理員登記不一致。': 'The sign-in email does not match the administrator’s registration.',
  '找不到要啟用的帳號資料。': 'The account to activate could not be found.',
  '管理員帳號保留管理員權限，不能用教練停用操作。': 'Administrator accounts retain their access and cannot be disabled through coach controls.',
  '教練信箱或公開身份已連結其他帳號，未套用這次變更。': 'The coach email or public profile is linked to another account. No changes were applied.',
  '教練帳號操作失敗。': 'Unable to complete the coach account action.',
  '未填寫姓名': 'Name not provided',
  '暫無訂單': 'No orders yet',
  '未知教練': 'Unknown coach',
  '已同意': 'Agreed',
  '未同意': 'Not agreed',
  '本期正常報名': 'Regular enrollment this season',
  '教練點名已確認到課': 'Coach confirmed attendance',
  '教練點名未到，需人工處理': 'Coach marked absent; manual review required',
  '待教練完成該堂點名': 'Awaiting coach attendance for this session',
  '已核對': 'Reviewed',
  '舊版報名': 'Legacy enrollment',
  '不適用（跑班自取）': 'Not applicable (team pickup)',
  '季度或課程資料無效。': 'Invalid season or course details.',
  '班級名額必須是 1 至 500 之間的整數。': 'Class capacity must be an integer between 1 and 500.',
  '請設定有效的課程開始時間，才能進行教練到課簽到。': 'Set a valid class start time to enable coach check-in.',
  '找不到這個季度。': 'Season not found.',
  '找不到這一季的課程。': 'Course not found in this season.',
  '季度課程儲存失敗。': 'Unable to save the season course.',
  '已儲存到這一季；若為當前招生季度，前台也已同步。': 'Saved to this season. If it is the active enrollment season, the public website was also updated.',
  '請選擇版型並填寫新課程名稱。': 'Choose a template and enter the new course name.',
  '新增季度課程失敗。': 'Unable to add the season course.',
  '季度或來源課程無效。': 'Invalid season or source course.',
  '找不到要複製的課程。': 'The course to duplicate could not be found.',
  '複製課程失敗。': 'Unable to duplicate the course.',
  '課程複本已建立；完成設定前不會顯示於前台。': 'Course copy created. It stays hidden from the public website until setup is complete.',
  '找不到要移除的課程。': 'The course to remove could not be found.',
  '無法確認課程是否已有資料。': 'Unable to check whether the course already has records.',
  '這門課已有報名、點名、停課或補課資料，不能刪除；請改為關閉對外顯示。': 'This course has enrollment, attendance, cancellation or makeup records and cannot be deleted. Hide it from the public website instead.',
  '無法建立刪除稽核記錄。': 'Unable to create the deletion audit record.',
  '移除課程失敗。': 'Unable to remove the course.',
  '空白課程已移除，其他季度與既有資料不受影響。': 'Empty course removed. Other seasons and existing records are unchanged.',
  '季度資料無效。': 'Invalid season details.',
  '季度刪除功能尚待資料庫更新，請稍後再試；目前未刪除任何資料。': 'Season deletion requires a database update. Try again later; no records were deleted.',
  '空白季度及其課程設定已刪除，其他季度與歷史資料不受影響。': 'The empty season and its course settings were deleted. Other seasons and historical records are unchanged.',
  '找不到要複製的季度。': 'The season to duplicate could not be found.',
  '建立下一季失敗。': 'Unable to create the next season.',
  '讀取上一季課程失敗。': 'Unable to load courses from the previous season.',
  '缺少季度 ID。': 'A season ID is required.',
  '請先建立並開啟至少一門對外顯示的課程。': 'Create and publish at least one course first.',
  '切換前台招生季度失敗。': 'Unable to change the public enrollment season.',
  '前台訓練課程、日程表與報名頁已切換到新季度。': 'Public training courses, schedules and enrollment pages now use the new season.',
  '季度狀態無效。': 'Invalid season status.',
  '請先將前台招生切換到其他季度，再封存這一季。': 'Switch public enrollment to another season before archiving this one.',
  '無法停止季度同步，尚未封存。': 'Unable to stop season synchronization. The season was not archived.',
  '更新季度狀態失敗。': 'Unable to update the season status.',
  '季度狀態已更新，報名資料不會被刪除。': 'Season status updated. Enrollment records are retained.',
  '請先選擇要登記的公開教練身份。': 'Choose the public coach profile to register.',
  '請填寫這位教練實際登入網站的有效信箱。': 'Enter the valid email address this coach uses to sign in.',
  '目前無法確認登入帳號，未寫入教練登記。': 'Unable to verify the sign-in account. No coach registration was saved.',
  '已登記並啟用教練帳號。': 'Coach account registered and activated.',
  '已登記教練帳號；完成信箱驗證後即可啟用。': 'Coach account registered. Verify the email address to activate it.',
  '已登記教練信箱；待教練首次登入並完成信箱驗證後啟用。': 'Coach email registered. The account will activate after the coach signs in and verifies the email.',
  '教練帳號登記 ID 無效。': 'Invalid coach account registration ID.',
  '目前無法確認登入帳號，未變更教練狀態。': 'Unable to verify the sign-in account. Coach status was not changed.',
  '這筆教練登記已綁定其他帳號，未套用啟用操作。': 'This coach registration is linked to another account. Activation was not applied.',
  '教練帳號已重新啟用；若尚未完成信箱驗證，會保持待啟用。': 'Coach account reactivated. If email verification is incomplete, activation remains pending.',
  '教練帳號已停用，之後登入不會自動恢復。': 'Coach account disabled. Signing in will not automatically reactivate it.',
  '教練認證碼已取消，請改用登記信箱管理教練帳號。': 'Coach verification codes are no longer used. Manage coach accounts by registered email.',
  '舊版教練角色操作已取消，請改用教練帳號登記／停用／啟用。': 'Legacy coach role actions are unavailable. Use coach account registration, deactivation or activation.',
  '缺少使用者 ID。': 'A user ID is required.',
  '找不到使用者。': 'User not found.',
  '請先授予這個帳號教練權限。': 'Grant this account coach access first.',
  '找不到要連結的公開教練資料。': 'The public coach profile to link could not be found.',
  '這份公開教練資料已經連結其他帳號，未套用這次變更。': 'This public coach profile is linked to another account. No changes were applied.',
  '這個帳號已連結其他公開教練身份，請先解除原連結。': 'This account is linked to another public coach profile. Unlink it first.',
  '這份公開教練資料剛剛已被其他帳號連結。': 'Another account has just linked this public coach profile.',
  '教練帳號與公開資料已連結。': 'Coach account linked to the public profile.',
  '已解除公開教練資料連結。': 'Public coach profile unlinked.',
  '點名異常處理資料無效。': 'Invalid attendance exception details.',
  '找不到這筆點名資料。': 'Attendance record not found.',
  '找不到這筆課程報名。': 'Course enrollment not found.',
  '這筆點名目前不構成計費起點異常。': 'This attendance record does not currently have a billing-start exception.',
  '已重新開啟這筆計費異常。': 'Billing exception reopened.',
  '已記錄補繳完成。': 'Additional payment recorded as complete.',
  '已記錄本次免除補繳。': 'Additional payment waiver recorded.',
  '訂單資料不完整。': 'Order details are incomplete.',
  '已確認的商城訂單不能刪除。': 'Confirmed shop orders cannot be deleted.',
  '刪除商城訂單失敗。': 'Unable to delete the shop order.',
  '找不到商城訂單。': 'Shop order not found.',
  '商城訂單已刪除；如有預留庫存，系統已自動歸還。': 'Shop order deleted. Any reserved stock was returned automatically.',
  '找不到課程報名訂單。': 'Course enrollment order not found.',
  '已確認入帳的課程報名不能刪除。': 'Course enrollments with confirmed payment cannot be deleted.',
  '刪除課程報名失敗。': 'Unable to delete the course enrollment.',
  '未完成的課程報名記錄已刪除。': 'Incomplete course enrollment deleted.',
  '缺少訂單 ID。': 'An order ID is required.',
  '商城訂單只能確認匯款入帳或標記為匯款資料需補充。': 'Shop orders can only be marked as payment confirmed or requiring additional transfer details.',
  '請聯絡顧客補充或重新確認匯款資料。': 'Contact the customer to provide or reconfirm transfer details.',
  '商城訂單更新失敗。': 'Unable to update the shop order.',
  '請先核實款項已實際入帳，並填寫 1 至 1000 字的核對依據。': 'Verify that payment was received and enter 1–1,000 characters describing the evidence.',
  '本班名額已滿，未確認入帳；請先處理班級名額。': 'The class is full. Payment was not confirmed; resolve class capacity first.',
  '確認入帳未完成，請重新整理核對狀態後再試。': 'Payment confirmation did not complete. Refresh the review status and try again.',
  '已確認課程匯款入帳，確認時間、操作人及核對依據已保存。': 'Course payment confirmed. The confirmation time, operator and evidence were recorded.',
  '這裡只能將課程報名標記為「匯款資料需補充」。': 'This control can only mark a course enrollment as requiring additional transfer details.',
  '請從「補件通知與紀錄」填寫給學生的說明，內部備註不會寄給學生。': 'Use the follow-up notification history to enter instructions for the student. Internal notes are not sent to students.',
  '缺少商品 ID。': 'A product ID is required.',
  '讀取商品失敗。': 'Unable to load the product.',
  '找不到商品，或商品已經刪除。': 'Product not found or already deleted.',
  '刪除商品失敗。': 'Unable to delete the product.',
  '商品已被其他管理員刪除，請重新整理。': 'Another administrator deleted this product. Refresh to continue.',
  '請完整填寫商品名稱、分類與主圖。': 'Provide the product name, category and main image.',
  '商品圖片網址無效。': 'Invalid product image URL.',
  '商品影片網址無效。': 'Invalid product video URL.',
  '商品詳情圖片網址無效。': 'Invalid product detail image URL.',
  '商品官方連結網址無效。': 'Invalid official product URL.',
  '請完整填寫每一個商品款式、款式主圖與有效的詳情圖片。': 'Complete every product style, its main image and valid detail images.',
  '庫存數量必須是 0 或正整數。': 'Stock must be zero or a positive integer.',
  '商品售價必須是有效的新台幣整數金額。': 'Product price must be a valid whole-number amount in NT$.',
  '更新商品失敗。': 'Unable to update the product.',
  '商品內容、圖片、影片、售價與庫存已更新。': 'Product content, images, video, price and stock updated.',
  '庫存數量必須是有效整數。': 'Stock must be a valid integer.',
  '新增商品失敗。': 'Unable to add the product.',
  '商品已建立並加入商城管理。': 'Product created and added to shop management.',
  '教練資料識別碼無效。': 'Invalid coach profile ID.',
  '請填寫教練姓名，並確認照片網址格式正確。': 'Enter the coach’s name and a valid photo URL.',
  '教練公開資料儲存失敗。': 'Unable to save the public coach profile.',
  '團隊陣容資料已更新並發布。': 'Team roster updated and published.',
  '內容區塊清單無效。': 'Invalid content section list.',
  '輪播圖片資料不完整，請重新選擇圖片。': 'Slideshow image details are incomplete. Select the images again.',
  '請填寫每一則活動的名稱與說明；連結可留空，填寫時請使用有效的網址。': 'Enter a name and description for every event. Links are optional but must be valid URLs.',
  '顯示季度資訊前，請先填寫標題與摘要。': 'Enter a title and summary before displaying season information.',
  '網站內容區塊無效。': 'Invalid website content section.',
  '網站內容儲存失敗。': 'Unable to save website content.',
  '內容已儲存，但重新讀取失敗。': 'Content saved, but reloading it failed.',
  '內容已儲存，但教練資料重新讀取失敗。': 'Content saved, but reloading coach details failed.',
  '網站內容已儲存並同步發布。': 'Website content saved and published.',
  '請填寫通道名稱、戶名、銀行名稱和收款帳號。': 'Enter the channel name, account holder, bank name and receiving account number.',
  '權重必須是正整數。': 'Weight must be a positive integer.',
  '新增收款帳戶失敗。': 'Unable to add the receiving account.',
  '收款帳戶已新增。': 'Receiving account added.',
  '缺少收款帳戶 ID。': 'A receiving account ID is required.',
  '更新收款帳戶失敗。': 'Unable to update the receiving account.',
  '收款帳戶已啟用。': 'Receiving account enabled.',
  '收款帳戶已停用。': 'Receiving account disabled.',
  '正式教練關聯由已入帳班級自動產生；請在季度管理調整班級任課教練。': 'Coach links are generated automatically from paid class enrollments. Change assigned coaches in season management.',
  '請依實際報名、退費或班級設定調整正式資格，不能單獨解除教練關聯。': 'Adjust eligibility through enrollment, refunds or class settings. Coach links cannot be removed independently.',
  '未知的管理員操作。': 'Unknown administrator action.',
}
