// Romanized public names follow the site's existing coach keys; stored identities
// and private student names are never changed by these display translations.
export const coachEnglishCopy: Record<string, string> = {
  '一起跑，讓訓練更有方向與效率。\n專業教練帶領系統化訓練，身邊夥伴陪你穩步突破。來看看好運教練與助教的專業陣容！': 'Run together with greater direction and purpose.\nOur coaches lead structured training while your teammates help you make steady progress. Meet the Nurture Running Team coaches and assistants.',
  '帶好每一堂訓練': 'Guidance for every session',
  '位': 'people',
  '本季度負責班級': 'Classes this season',
  '擅長・經歷與證照': 'Expertise, experience, and qualifications',
  '查看完整介紹': 'View full profile',
  '好運跑班教練團隊背影合照': 'The Nurture Running Team coaches, photographed from behind',
  '總教練 陳盛琦': 'Head Coach Chen Sheng-qi',
  '陳盛琦': 'Chen Sheng-qi',
  '琦琦教練': 'Coach Qi-qi',
  '劉丞恩教練': 'Coach Liu Cheng-en',
  '劉丞恩': 'Liu Cheng-en',
  '恩恩教練': 'Coach En-en',
  '扁扁教練': 'Coach Bian-bian',
  '扁扁': 'Bian-bian',
  '吳珮慈教練': 'Coach Wu Pei-ci',
  '吳珮慈': 'Wu Pei-ci',
  '周賢峰教練': 'Coach Zhou Xian-feng',
  '周賢峰': 'Zhou Xian-feng',
  '鄭以群教練': 'Coach Zheng Yi-qun',
  '鄭以群': 'Zheng Yi-qun',
  '螞蟻教練': 'Coach Ant',
  '羅珮慈教練': 'Coach Luo Pei-ci',
  '羅珮慈': 'Luo Pei-ci',
  '羅閔耀教練': 'Coach Luo Min-yao',
  '羅閔耀': 'Luo Min-yao',
  'CC 教練': 'Coach CC',
  '鄔惟喬教練': 'Coach Wu Wei-qiao',
  '鄔惟喬': 'Wu Wei-qiao',
  '林尚平教練': 'Coach Lin Shang-ping',
  '林尚平': 'Lin Shang-ping',
  'Peter 教練': 'Coach Peter',
  '楊陞豪教練': 'Coach Yang Sheng-hao',
  '楊陞豪': 'Yang Sheng-hao',
  '赫嵐妮助教': 'Assistant Coach He Lan-ni',
  '赫嵐妮': 'He Lan-ni',
  '小赫助教': 'Assistant Coach Xiao-he',
  '鍾立宸助教': 'Assistant Coach Zhong Li-chen',
  '鍾立宸': 'Zhong Li-chen',
  '史昕娣助教': 'Assistant Coach Shi Xin-di',
  '史昕娣': 'Shi Xin-di',
  '黃苙倫助教': 'Assistant Coach Huang Li-lun',
  '黃苙倫': 'Huang Li-lun',
  '柯詠馨助教': 'Assistant Coach Ke Yong-xin',
  '柯詠馨': 'Ke Yong-xin',
  '戴嘉惠助教': 'Assistant Coach Dai Jia-hui',
  '戴嘉惠': 'Dai Jia-hui',
  '林祐安助教': 'Assistant Coach Lin You-an',
  '林祐安': 'Lin You-an',
  '小黑教練': 'Coach Xiao-hei',
  '好運跑班教練': 'Nurture Running Team coach',
  '好運跑班助教。': 'Nurture Running Team assistant coach.',
  '完整週期規劃、線上課表與賽事目標，重視跑者長期穩定進步。': 'Season planning, online training plans, and race goals, with a focus on steady long-term progress.',
  '好運跑班創始人兼總教練，曾任NIKE RUN CLUB 大中華區與北京總教練、MIZUNO REBELLION 馬拉松訓練營總教練、長榮航空懂跑訓練班教練、寶礦力路跑進階訓練課程教練。': 'Founder and head coach of Nurture Running Team. Previously head coach for NIKE RUN CLUB Greater China and Beijing and the MIZUNO REBELLION Marathon Training Camp, and coach for EVA Air running classes and Pocari Sweat advanced running courses.',
  '訓練紀律與個別化調整，能陪跑者從入門走到進階。': 'Training discipline and individual adjustments to support runners from beginner to advanced levels.',
  '好運跑班教練，NIKE NRC PACER，曾任台灣應用材料跑班教練、長榮航空懂跑訓練班教練、寶礦力路跑初階訓練課程教練，並長期投入學校田徑與企業跑班教學。': 'Nurture Running Team coach and NIKE NRC pacer. Previously coached Applied Materials Taiwan running classes, EVA Air running classes, and Pocari Sweat beginner running courses, with extensive work in school athletics and corporate running programs.',
  '細膩觀察身體狀態，用功能性訓練與肌力基礎降低跑步風險。': 'Careful observation, functional training, and foundational strength work to reduce running-related risks.',
  '好運跑班教練，具伊甸松山視障中心視多障運動課教師、臺師大體適能與適應體育 TA 經歷。': 'Nurture Running Team coach with experience teaching exercise for people with visual and multiple disabilities at the Eden Songshan center, and as a fitness and adapted physical education teaching assistant at National Taiwan Normal University.',
  '建立初階跑者的跑步習慣，穩定肌力基礎，讓跑步更安全、更有效率。': 'Helps newer runners build consistent habits and a strength foundation for safer, more efficient running.',
  '好運跑班教練，曾任我型我速萬金石 MIZUNO REBELLION馬拉松訓練營教練、寶礦力路跑初階訓練課程教練、博仲法律事務所跑步社教練。': 'Nurture Running Team coach. Previously coached the Wan Jin Shi MIZUNO REBELLION Marathon Training Camp, Pocari Sweat beginner running courses, and the running club at Winkler Partners.',
  '協助初階跑者建立運動習慣、半馬訓練與賽事配速指導': 'Exercise habits for beginners, half marathon training, and race pacing guidance',
  '好運跑班教練，曾任長榮航空懂跑訓練班助教、MIZUNO REBELLION 馬拉松訓練營教練，具豐富路跑賽與場地賽經驗。': 'Nurture Running Team coach. Previously an assistant for EVA Air running classes and a coach at the MIZUNO REBELLION Marathon Training Camp, with extensive road and track racing experience.',
  '協助教練掌握不同程度跑者的課堂狀態，讓訓練更有秩序。': 'Helps coaches monitor runners at different levels and keep training organized.',
  '好運跑班教練，曾任 GARMIN希望跑步學堂教練、NIKE  NRC  PACER。': 'Nurture Running Team coach. Previously coached the GARMIN Hope Running School and served as a NIKE NRC pacer.',
  '把週期訓練拆成清楚可執行的步驟，協助跑者穩定完成課表。': 'Turns periodized training into clear, practical steps to help runners follow their plans consistently.',
  '好運跑班教練，曾任GarminRun 跑步教練。': 'Nurture Running Team coach and former GarminRun running coach.',
  '以訓練原理為基礎，結合戰術和個別化安排，讓跑者清楚知道每堂課目的。': 'Combines training principles, tactics, and individual plans so runners understand the purpose of every session.',
  '好運跑班教練，曾任丹鳳高中、八里國中、金山高中田徑教練，以及 NIKE RUN CLUB PACER、NIKE FAST42 臺灣北區助教。': 'Nurture Running Team coach. Previously coached athletics at Danfeng High School, Bali Junior High School, and Jinshan High School, and served as a NIKE RUN CLUB pacer and NIKE FAST42 assistant coach in northern Taiwan.',
  '用穩定陪伴與動作提醒，幫助跑者在團練裡逐步累積。': 'Offers steady support and form cues to help runners progress through group training.',
  '好運跑班教練，曾任森林跑站助教、MIZUNO REBELLION 馬拉松訓練營助教。': 'Nurture Running Team coach. Previously an assistant coach at Forest Run Station and the MIZUNO REBELLION Marathon Training Camp.',
  '兼顧基礎動作與個別化調整，能陪跑者從進階走到菁英。': 'Combines movement fundamentals with individual adjustments to support runners from intermediate to advanced levels.',
  '好運跑班教練，曾任NIKE RUN CLUB PACER。': 'Nurture Running Team coach and former NIKE RUN CLUB pacer.',
  '以穩定的節奏建立訓練秩序，幫助跑者穩定累積。': 'Creates an organized training rhythm to help runners build fitness consistently.',
  '好運跑班教練，曾任長庚路跑社教練。': 'Nurture Running Team coach and former Chang Gung running club coach.',
  '在課堂中即時協助學員理解訓練內容，讓訓練執行更順暢。': 'Helps students understand workouts during sessions so training runs smoothly.',
  '用穩定陪伴與即時提醒，幫助學員把課表內容確實完成。': 'Helps students complete their planned training with consistent support and timely reminders.',
  '好運跑班助教，曾任長榮航空懂跑訓練班助教。': 'Nurture Running Team assistant coach and former assistant for EVA Air running classes.',
  '用清楚提醒與陪伴協助跑者完成當日訓練。': 'Helps runners complete the day’s session with clear guidance and support.',
  '好運跑班助教，曾任長榮航空懂跑訓練班助教助教、中正高中田徑隊助理教練。': 'Nurture Running Team assistant coach. Previously assisted EVA Air running classes and the Zhongzheng High School athletics team.',
  '一對一 中、高階線上訓練規劃': 'Individual online training plans for intermediate and advanced runners',
  '中、高階跑者週期訓練規劃': 'Periodized training for intermediate and advanced runners',
  '初階跑者建立運動習慣': 'Building exercise habits for beginner runners',
  '企業跑班課程規劃': 'Corporate running program planning',
  '以完整週期規劃串起團練、線上課表與賽事目標，重視跑者長期穩定進步。': 'Connects group training, online plans, and race goals through complete training cycles, emphasizing steady long-term progress.',
  '國立體育大學－陸上運動技術學系學士': 'Bachelor’s degree in Athletics, National Taiwan Sport University',
  '教育部學校專任運動教練證': 'Ministry of Education full-time school sports coach certificate',
  '中華民國田徑協會 C 級教練': 'Chinese Taipei Athletics Association Level C coach',
  '中華民國田徑協會 C 級裁判': 'Chinese Taipei Athletics Association Level C official',
  'DR ACADEMY 功能性運動表現專家 L1': 'DR ACADEMY Functional Performance Specialist L1',
  '兼顧基礎動作、訓練紀律與個別化調整，能陪跑者從入門走到進階。': 'Combines movement fundamentals, training discipline, and individual adjustments to support runners from beginner to advanced levels.',
  '國立臺灣體育運動大學 - 競技運動學系學士': 'Bachelor’s degree in Competitive Sport, National Taiwan University of Sport',
  '中華民國健身運動協會運動按摩技術人員': 'Sports massage practitioner, Taiwan fitness association',
  '初階跑者': 'Beginner runners',
  '企業課程': 'Corporate classes',
  '肌力訓練': 'Strength training',
  '幼兒體能訓練': 'Fitness training for young children',
  '一對一 教學': 'Individual coaching',
  '輔仁大學 - 運動管理學系碩士': 'Master’s degree in Sport Management, Fu Jen Catholic University',
  '中華民國田徑協會Ｃ級教練': 'Chinese Taipei Athletics Association Level C coach',
  '中華民國田徑協會Ｃ級裁判': 'Chinese Taipei Athletics Association Level C official',
  '中華民國體適能健身C級指導員證': 'Level C fitness instructor certificate',
  'DR ACADEMY - 功能性運動表現專家L1': 'DR ACADEMY Functional Performance Specialist L1',
  '初階跑者訓練': 'Beginner runner training',
  '特殊族群功能性訓練': 'Functional training for special populations',
  '國立臺灣師範大學 - 體育與運動科學系碩士': 'Master’s degree in Physical Education and Sport Sciences, National Taiwan Normal University',
  'C 級健身體適能教練': 'Level C fitness coach',
  '國民體適能檢測員': 'National fitness assessment examiner',
  '丙級運動防護員': 'Level C athletic trainer',
  '初、中、高階跑者訓練': 'Training for beginner, intermediate, and advanced runners',
  '競技運動員訓練': 'Competitive athlete training',
  '臺北市立大學－陸上運動學系學士': 'Bachelor’s degree in Athletics, University of Taipei',
  '110年全國運動會20公里競走 第三名': '2021 National Games · 20 km race walk · 3rd place',
  '112年全國運動會20公里競走 第四名': '2023 National Games · 20 km race walk · 4th place',
  '114年全國運動會20公里競走 第三名': '2025 National Games · 20 km race walk · 3rd place',
  '20公里競走最佳成績1:46:20': '20 km race walk personal best · 1:46:20',
  '中華民國初級田徑專任教練證': 'Entry-level full-time athletics coach certificate',
  '中華民國 C 級田徑裁判證': 'Level C athletics official certificate',
  '中華民國 C 級田徑教練證': 'Level C athletics coach certificate',
  '體適能 C 級指導員': 'Level C fitness instructor',
  '初、中階跑者週期訓練規劃': 'Periodized training for beginner and intermediate runners',
  '跑步基礎能力建立': 'Building running fundamentals',
  '配速與訓練節奏引導': 'Pacing and training rhythm guidance',
  '國立臺灣師範大學 - 體育學系學士': 'Bachelor’s degree in Physical Education, National Taiwan Normal University',
  '半馬 1:21:30': 'Half marathon · 1:21:30',
  '中華民國田徑 C 級教練': 'Level C athletics coach',
  '中華民國田徑 C 級裁判': 'Level C athletics official',
  '初階跑姿建立與企業跑班規劃': 'Running form for beginners and corporate running programs',
  '初階跑者跑姿建立': 'Running form for beginners',
  '社團跑班課程規劃': 'Running club program planning',
  '重視跑姿細節與課程結構，讓初階跑者在安全節奏裡建立自信。': 'Focuses on running form and structured sessions to help beginners build confidence at a safe pace.',
  '輔仁大學 - 體育學碩士': 'Master’s degree in Physical Education, Fu Jen Catholic University',
  '臺北市立大學 - 陸上運動技術學系學士': 'Bachelor’s degree in Athletics, University of Taipei',
  '中華民國田徑專任教練證照': 'Full-time athletics coach certificate',
  '中華民國田徑協會 B 級教練證': 'Chinese Taipei Athletics Association Level B coach certificate',
  'IBMA-BASIC 個人伸展教練證': 'IBMA-BASIC personal stretching coach certificate',
  '半程馬拉松訓練': 'Half marathon training',
  '賽事配速經驗分享': 'Race pacing experience and guidance',
  '把選手經驗轉化為一般跑者可吸收的訓練提醒，陪學員穩定養成習慣。': 'Turns competitive experience into practical guidance for everyday runners, supporting steady training habits.',
  '2022 臺北馬 半程馬拉松 - 第一名': '2022 Taipei Marathon · Half marathon · 1st place',
  '2023 Garmin Run 亞洲系列賽臺北站 半程馬拉松 - 第一名': '2023 Garmin Run Asia Series, Taipei · Half marathon · 1st place',
  '2023 臺南古都國際半程馬拉松 - 第二名': '2023 Tainan Ancient Capital International Half Marathon · 2nd place',
  '成都世大運半程馬拉松國手': 'National team half marathon runner at the Chengdu World University Games',
  '半程馬拉松 1:06:58': 'Half marathon · 1:06:58',
  '全程馬拉松 2:31:24': 'Marathon · 2:31:24',
  '社團課程規劃': 'Club training program planning',
  '以跑姿基礎和團練節奏建立訓練秩序，幫助跑者穩定累積。': 'Uses running fundamentals and a consistent group training rhythm to help runners make steady progress.',
  '國立體育大學 - 陸上運動技術學系學士': 'Bachelor’s degree in Athletics, National Taiwan Sport University',
  '2026 萬金石馬拉松 10公里 第二名': '2026 Wan Jin Shi Marathon · 10 km · 2nd place',
  '2026 台南國際古都馬拉松 10公里 第三名': '2026 Tainan Ancient Capital International Marathon · 10 km · 3rd place',
  '2025 台中國際馬拉松半程馬拉松 第一名': '2025 Taichung International Marathon · Half marathon · 1st place',
  '2024 全國田徑錦標賽男子 1500公尺 第一名': '2024 National Athletics Championships · Men’s 1500 m · 1st place',
  '跑步生理學與訓練原則': 'Running physiology and training principles',
  '跑步訓練技巧與戰術': 'Running techniques and tactics',
  '個別化訓練計畫': 'Individual training plans',
  '帶領跑者訓練，協助團隊合作': 'Leading running sessions and supporting teamwork',
  '亞洲核心訓練師': 'Asian core training instructor',
  '課堂協助': 'Session support',
  '動作觀察': 'Movement observation',
  '團練陪跑': 'Group running support',
  '在課堂中即時協助學員理解訓練內容，讓團練執行更順暢。': 'Helps students understand their workouts during sessions so group training runs smoothly.',
  '國立清華大學 - 運動科學系學士': 'Bachelor’s degree in Sports Science, National Tsing Hua University',
  '114年全國運動會3000公尺障礙 第二名': '2025 National Games · 3000 m steeplechase · 2nd place',
  '115全國大專院校運動會1500公尺 第一名': '2026 National Intercollegiate Athletic Games · 1500 m · 1st place',
  '2025 WMRTC山徑越野世界錦標賽代表選手': 'National team athlete at the 2025 World Mountain and Trail Running Championships',
  '1500公尺最佳成績4:43.47': '1500 m personal best · 4:43.47',
  '3000公尺障礙最佳成績11:03.13': '3000 m steeplechase personal best · 11:03.13',
  '5000公尺最佳成績18:37.44': '5000 m personal best · 18:37.44',
  '10000公尺最佳成績 40:52.00': '10000 m personal best · 40:52.00',
  '半程馬拉松最佳成績 92分': 'Half marathon personal best · 92 minutes',
  '訓練動線維持': 'Keeping training groups organized',
  '清華大學生命科學系學士': 'Bachelor’s degree in Life Science, National Tsing Hua University',
  '清華大學運動科學系學士': 'Bachelor’s degree in Sports Science, National Tsing Hua University',
  '115全大運 5000公尺 17:38': '2026 National Intercollegiate Athletic Games · 5000 m · 17:38',
  '115全大運 1500公尺 4:30': '2026 National Intercollegiate Athletic Games · 1500 m · 4:30',
  '跑步教學': 'Running instruction',
  '一對一教學': 'Individual coaching',
  '三鐵訓練': 'Triathlon training',
  '游泳教學': 'Swimming instruction',
  '體能訓練': 'Fitness training',
  '重量訓練': 'Weight training',
  '跑步：': 'Running:',
  '2017 年全國中等學校運動會': '2017 National High School Games',
  '5000公尺15:38:00': '5000 m · 15:38:00',
  '10000公尺33:13:00': '10000 m · 33:13:00',
  '2018 日本上尾半程馬拉松 1:13:20': '2018 Ageo Half Marathon, Japan · 1:13:20',
  '2019 臺北市秋季全國田徑公開賽 10000公尺 32:58:00': '2019 Taipei Autumn National Athletics Open · 10000 m · 32:58:00',
  '2020 全國大專院校運動會 10000公尺 第八名': '2020 National Intercollegiate Athletic Games · 10000 m · 8th place',
  '2020全國大專院校田徑公開賽 5000公尺 第六名 16:02': '2020 National Intercollegiate Athletics Open · 5000 m · 6th place · 16:02',
  '三鐵：': 'Triathlon:',
  '2023 Challenge-Taiwan 226 11:02:00 分齡一': '2023 Challenge-Taiwan 226 · 11:02:00 · 1st in age group',
  '2024 Challenge-Taiwan 113 5:05:00 分齡三': '2024 Challenge-Taiwan 113 · 5:05:00 · 3rd in age group',
  '中華民國田徑協會C級裁判證': 'Chinese Taipei Athletics Association Level C official certificate',
  '中華民國田徑協會C級教練證': 'Chinese Taipei Athletics Association Level C coach certificate',
  '中華民國紅十字會基本救命術': 'Red Cross Society of the Republic of China Basic Life Support',
  '中華民國水適能訓練協會丙級游泳教練證': 'Level C swimming coach certificate, Taiwan aquatic fitness training association',
  '學員狀態觀察': 'Monitoring students during training',
  '國立臺灣師範大學 - 運動競技學系學士': 'Bachelor’s degree in Athletic Performance, National Taiwan Normal University',
  '106年全國運動會800公尺 第三名': '2017 National Games · 800 m · 3rd place',
  '107年臺灣國際田徑公開賽': '2018 Taiwan Athletics Open',
  '800公尺 第一名 / 1500公尺 第三名': '800 m · 1st place / 1500 m · 3rd place',
  '1500公尺最佳成績4:52.30': '1500 m personal best · 4:52.30',
  '800公尺最佳成績2:15.83': '800 m personal best · 2:15.83',
  '400公尺最佳成績58.48': '400 m personal best · 58.48',
  '400公尺跨欄最佳成績63.24': '400 m hurdles personal best · 63.24',
  '中華民國田徑協會C級運動教練': 'Chinese Taipei Athletics Association Level C sports coach',
  '兒童體適能C級教練': 'Level C children’s fitness coach',
  '運動部田徑初級專任運動教練': 'Ministry of Sports entry-level full-time athletics coach',
  '雲林科技大學 - 企業管理學系學士': 'Bachelor’s degree in Business Administration, National Yunlin University of Science and Technology',
  '2020 台北渣打半程馬拉松 1:16:21': '2020 Taipei Standard Chartered Half Marathon · 1:16:21',
  '2021 台北馬拉松 2:40:31': '2021 Taipei Marathon · 2:40:31',
  '112年1500公尺全運會 第一名': '2023 National Games · 1500 m · 1st place',
  '全大運1500公尺三連霸': 'Three consecutive National Intercollegiate Athletic Games 1500 m titles',
  '800公尺最佳1:50.52': '800 m personal best · 1:50.52',
  '1500公尺最佳3:49.45': '1500 m personal best · 3:49.45',
  '5000公尺最佳15:23.62': '5000 m personal best · 15:23.62',
  '10000公尺最佳33:04.88': '10000 m personal best · 33:04.88',
  '中華民國田徑C級裁判': 'Level C athletics official',
  '中華民國田徑協會C級裁判': 'Chinese Taipei Athletics Association Level C official',
}
