// Complete English copy for published public content and its visible UI fragments.
// Keep source sentences intact: short dictionary words are not translation rules.
export const publicEnglishCopy: Record<string, string> = {
  '快速預覽': 'Quick preview',
  '關閉課程預覽': 'Close class preview',
  '查看課程詳情': 'View class details',
  '暫無符合篩選條件的課程': 'No classes match your filters',
  '試試其他城市或程度，或清除篩選查看所有班級。': 'Try another city or level, or clear the filters to see all classes.',
  '登入嘗試太頻繁，請稍後再試。': 'Too many sign-in attempts. Try again later.',
  '登入服務暫時無法完成驗證，請稍後再試。': 'The sign-in service cannot verify your account right now. Try again later.',
  '請填寫信箱和密碼。': 'Enter your email address and password.',
  '註冊嘗試太頻繁，請稍後再試。': 'Too many registration attempts. Try again later.',
  '帳戶暫時無法建立，請稍後再試。': 'Your account could not be created right now. Try again later.',
  '請輸入有效的電子信箱。': 'Enter a valid email address.',
  '密碼請使用 10 至 128 個字元。': 'Use a password between 10 and 128 characters.',
  '請完整填寫姓名與聯絡電話。': 'Enter your name and contact phone number.',
  '帳戶服務暫時無法使用，請稍後再試。': 'The account service is temporarily unavailable. Try again later.',
  '上一位教練': 'Previous coach',
  '下一位教練': 'Next coach',
  '品牌理念': 'Our philosophy',
  '返回商店': 'Back to shop',
  '返回我的': 'Back to my account',
  '課程操作': 'Class actions',
  '直接選擇教練': 'Choose a coach',
  '教練姓名': 'Coach names',
  '修改跑者資料': 'Edit runner profile',
  'IG 諮詢': 'Ask on Instagram',
  '切換工作空間': 'Switch workspace',
  '個人': 'Personal',
  '關閉登入視窗': 'Close sign-in window',
  '隱藏密碼': 'Hide password',
  '顯示密碼': 'Show password',
  '信箱或密碼不正確。': 'Incorrect email or password.',
  '這個信箱已經註冊，請直接登入。': 'This email is already registered. Please sign in.',
  '密碼強度不足，請使用至少 10 個字元。': 'The password is too weak. Use at least 10 characters.',
  '目前無法連線到登入服務。請先重新整理頁面再試一次；如果仍失敗，可能是目前網路或瀏覽器阻擋 Supabase 認證服務。': 'Unable to connect to the sign-in service. Refresh the page and try again. If the problem continues, your network or browser may be blocking the authentication service.',
  '教練將在課程確認入帳後，依報名班級自動關聯。': 'Your coach will be linked to your registered class after payment is confirmed.',
  '登入中...': 'Signing in…',
  '建立中...': 'Creating account…',
  '連線中...': 'Connecting…',
  '註冊即表示你同意本站在帳戶與服務所需範圍內處理所填資料。': 'By registering, you agree to the processing of your details as needed for your account and the service.',
  '開啟選單': 'Open menu',
  '關閉選單': 'Close menu',
  '主要導覽': 'Main navigation',
  '返回課程': 'Back to classes',
  '課程': 'Classes',
  '團隊': 'Team',
  '我的': 'Account',
  '左右滑動查看全系列': 'Swipe to explore the collection',
  '左右滑動查看全部紀念卡': 'Swipe to see all achievement cards',
  '參加正式賽事並達標對應成績。': 'Complete an official race and meet the relevant time standard.',
  '放射光芒呈現 SUB4，象徵達標瞬間的榮耀時刻；光芒四射的設計，展現挑戰自我的能量。': 'Radiating light forms SUB4, capturing the moment a goal is achieved and the energy of a personal challenge.',
  '教練卡片控制': 'Coach card controls',
  '左右滑動': 'Swipe left or right',
  '關閉教練介紹': 'Close coach profile',
  '教練介紹': 'Coach profile',
  '教學專長': 'Coaching specialties',
  '經歷與證照': 'Experience and qualifications',
  '本期訓練重點': 'Training priorities this season',
  '立即報名': 'Register now',
  '查看團隊資料': 'View coach profiles',
  '返回課程詳情': 'Back to class details',
  '報名': 'Registration',
  '費用：': 'Fee: ',
  '系統依學員身分與本期計費起始課次自動核算': 'Your fee is calculated from your student category and the first billable session this season.',
  '訓練重點：': 'Training focus: ',
  '適合對象：': 'Suitable for: ',
  '本班名額': 'Class capacity',
  '人': 'participants',
  '登入或註冊後填寫報名表': 'Sign in or create an account to register',
  '已有帳戶可直接登入；第一次使用可在下一個視窗切換到註冊。網站會使用登入信箱建立報名記錄，避免重複報名，並讓你隨時查看匯款核對狀態。': 'Sign in with an existing account, or switch to registration in the next window to create one. Your signed-in email links your registration, helps prevent duplicates, and lets you check payment review status.',
  '登入或註冊後開始填寫': 'Sign in or create an account to begin',
  '我的報名狀態': 'My registration status',
  '請先登入；第一次使用可在登入視窗切換到註冊，再於網站內填寫報名與匯款資料。': 'Sign in first. New users can switch to registration in the sign-in window, then complete class and transfer details on this website.',
  '登入或註冊查看狀態': 'Sign in or create an account to view status',
  '更新報名狀態': 'Refresh registration status',
  '開班提醒：': 'Class opening note: ',
  '專注於速度能力與跑步經濟性': 'Focus on speed and running economy',
  '為賽季打下穩固有氧與速度基礎': 'Build an aerobic and speed foundation for race season',
  '用清楚的訓練節奏，讓每一次累積都能銜接賽事目標。': 'A clear training rhythm connects every session to your race goals.',
  '教學品質保障': 'Quality coaching',
  '依人數配置專屬教練。': 'Coaching support is assigned according to class size.',
  '不同程度的跑者，都可以在這裡找到自己的節奏。': 'Runners of every level can find their own rhythm here.',
  '我們不把跑者分成「會跑」或「不會跑」。每個人都有自己的起點，也有自己的目標。好運跑班希望做的是，讓你知道今天為什麼這樣跑，這週為什麼這樣練，下一個階段又要怎麼調整。': 'Everyone has a different starting point and different goals. We help you understand the purpose of today’s run, this week’s training, and the adjustments to make in the next phase.',
  '新手小白': 'First-time runners',
  '業餘跑者': 'Recreational runners',
  '專業跑者': 'Competitive runners',
  '5000m / 10000m 備賽': '5K / 10K race preparation',
  '半馬 / 全馬備賽': 'Half marathon / marathon preparation',
  '從下一次訓練開始，跑得更清楚一點。': 'Bring more purpose to your next training session.',
  '如果你還不確定自己適合哪一班，先讓我們知道你的跑步經驗、目標距離與可訓練時間，我們會協助你找到更適合的起點。': 'If you are unsure which class suits you, tell us about your running experience, target distance, and available training time. We will help you find the right starting point.',
  '可以。我們有初階班課程，請先依目前跑步經驗、訓練時間與目標，來選擇適合班級。如果對報名有任何問題，歡迎諮詢好運官方Instagram。': 'Yes. We offer beginner classes. Choose a class based on your current running experience, available time, and goals. Contact our official Instagram with any registration questions.',
  '教練團會依天候與場地狀況，決定是否調整集合地點或停課，並於班級 LINE 群組公告，出發前請留意最新消息。': 'Coaches will decide whether to change the meeting point or cancel a session based on the weather and venue. Check the latest announcement in your class LINE group before leaving.',
  '各班費用與插班計價會依季度及剩餘堂數不同，請先至報名頁登入後確認本次金額；想先了解費用，也歡迎諮詢好運官方 Instagram。': 'Class and late-entry fees depend on the season and remaining sessions. Sign in on the registration page to confirm your amount. You can also ask about fees through our official Instagram.',
  '可以依當期規則申請最近一堂課請假，並在本季度符合條件的其他班級課次安排補課。': 'You may request leave for your next session under the current rules and arrange an eligible make-up session in another class within the same season.',
  '有的。歡迎諮詢好運官方Instagram，我們將依當期名額、場地與教練安排，來確認是否能參加體驗課程。': 'Yes. Contact our official Instagram to check whether a trial is available based on current places, venue conditions, and coach arrangements.',
  '真實內容持續更新': 'Real stories, regularly updated',
  '到 Instagram 看最新學員故事與訓練現場': 'See the latest runner stories and training on Instagram',
  '為避免使用未經確認的姓名、成績或照片，網站不刊登虛構見證；公開內容以好運跑班官方帳號發布為準。': 'We do not publish fictional testimonials or unverified names, results, or photos. Refer to the Nurture Running Team official account for public stories.',
  '好運跑班限定\nSUB 系列榮耀徽章': 'Exclusive to Nurture Running Team\nSUB Series Achievement Badges',
  '週一紅色 Logo': 'Monday red logo',
  '週二橙色 Logo': 'Tuesday orange logo',
  '週三黃色 Logo': 'Wednesday yellow logo',
  '週四綠色 Logo': 'Thursday green logo',
  '週五青色 Logo': 'Friday cyan logo',
  '週六藍色 Logo': 'Saturday blue logo',
  '閱讀公告': 'Read announcement',
  '週日紫色 Logo': 'Nurture Running Team purple logo',
  '好運跑班 Logo': 'Nurture Running Team logo',
  '好運跑班精神': 'The Nurture Running Team philosophy',
  '在 Instagram 關注好運跑班': 'Follow Nurture Running Team on Instagram',
  '課程總覽': 'Explore our classes',
  '快速掌握各班開課時間、地點與目標，輕鬆挑選最適合自己的班級。': 'Compare class times, locations, and goals to find the right class for you.',
  '程度': 'Level',
  '初階': 'Beginner',
  '進階': 'Intermediate',
  '菁英': 'Advanced',
  '城市': 'City',
  '全部城市': 'All cities',
  '找到': 'Found',
  '個班級': 'classes',
  '在課程詳情最下方點選「立即報名」，登入會員後填寫資料，並確認本次課程費用。': 'Select Register at the bottom of the class page, sign in, complete your details, and confirm the fee.',
  '依網站顯示的金額完成匯款，並提交銀行帳戶後五碼，財務核對無誤即完成報名。': 'Transfer the amount shown and report the last five account digits. Registration is complete once finance confirms payment.',
  '請問新手可以參加嗎？': 'Can beginners join?',
  '請問下雨怎麼辦？': 'What happens if it rains?',
  '請問課程費用是多少？': 'How much does a class cost?',
  '請問可以請假嗎？': 'Can I request leave?',
  '請問有體驗課嗎？': 'Can I try a class first?',
  '涵蓋 5000公尺、10000公尺、半馬、全馬。 一起為完賽或刷新個人最佳成績做準備。': 'Prepare for 5K, 10K, half marathon, and marathon races, whether your goal is to finish or set a personal best.',
  '多地訓練': 'Training across multiple locations',
  '台北市、新北市、新竹縣(市)、苗栗等班級依各季安排開課。': 'Classes in Taipei, New Taipei, Hsinchu City and County, Miaoli, and other locations are scheduled by season.',
  '好運跑班本期課程預覽': 'Preview of this season’s Nurture Running Team classes',
  '「好」的環境， 創造出優秀的「運」動員。': 'A great environment helps runners thrive.',
  '真正的進步，來自一季又一季穩定累積。用清楚的訓練節奏，讓每一次努力都能為目標賽事做好準備。': 'Real progress comes from consistent work, season after season. A clear training rhythm helps every effort contribute to your target race.',
  '依班級人數安排教練，留意每位學員的訓練狀況，提供指導與回饋。': 'Coach staffing follows class size so each runner’s training receives attention, guidance, and feedback.',
  '台北、新北、竹市、竹縣、苗栗。當期班級與地點，請查看最新課表。': 'Taipei, New Taipei, Hsinchu City and County, and Miaoli. See the latest schedule for current classes and locations.',
  '依訓練階段安排課表、團練與恢復，陪你逐步累積跑步能力。': 'Workouts, group sessions, and recovery follow each training phase to help you build running fitness gradually.',
  '練得順不順、最近累不累，都可以和教練聊聊。我們依你的狀態調整，一起找到能持續下去的節奏。': 'Talk with your coach about how training feels and how tired you are. We adjust to your condition and help you find a sustainable rhythm.',
  '真正喜歡上跑步。': 'truly enjoy running.',
  '無論是想養成跑步習慣，或正準備下一場比賽，好運跑班都歡迎您。\n可以成為第一次想規律跑步的自己，也可以是正在追逐 PB 的跑者；可以為 5000公尺、10000公尺 準備，也可以把目標放在半馬、全馬。重要的不是你現在跑得多快，而是你願意開始理解自己的身體，並且一步一步跑向更穩定的自己。': 'Whether you want to build a running habit or prepare for your next race, Nurture Running Team welcomes you.\nYou might be starting your first regular routine or chasing a personal best in the 5K, 10K, half marathon, or marathon. What matters is not how fast you are today, but your willingness to understand your body and become a more consistent runner, one step at a time.',
  '陽光下的田徑跑道': 'An athletics track in the sunshine',
  '好運跑班跑者與團隊': 'Nurture Running Team runners and coaches',
  '每一次進步，都從願意踏出第一步開始。': 'Every improvement begins with a first step.',
  '從第一次的訓練，到站上起跑線、朝目標前進，好運陪你一起累積。\n想看看同學們怎麼練、有哪些進步，歡迎到官方 Instagram 看看大家的跑步日常。': 'From your first session to the starting line and beyond, Nurture Running Team helps you build toward your goals.\nVisit our official Instagram to see how our runners train, improve, and enjoy their running lives.',
  '依自己的跑步經驗、目前能力與可訓練時間選擇適合的班級，先把穩定跑步的節奏建立起來。': 'Choose a class that suits your experience, current ability, and available time, then build a consistent running routine.',
  '第一次參賽、順利完賽，或刷新個人最佳成績，都值得好好準備。用適合自己的步調，努力朝目標靠近。': 'Your first race, a successful finish, or a new personal best all deserve preparation. Work toward your goal at a pace that suits you.',
  '好運跑班學員與教練團體合照': 'Nurture Running Team students and coaches together',
  '好運跑班學員一起訓練與成長': 'Nurture Running Team students training and improving together',
  '目前尚無上架商品，裝備與補給資訊，歡迎透過 Instagram 詢問。': 'No products are currently available. Contact us on Instagram for gear and running nutrition enquiries.',
  '裝備與補給，準備中': 'Gear and nutrition are on the way',
  '目前尚無上架商品。想詢問跑班裝備或補給，可以直接聯絡好運 Instagram。': 'No products are currently listed. Contact Nurture Running Team on Instagram to ask about gear or running nutrition.',
  '詢問裝備與補給': 'Ask about gear and nutrition',
  '先看看訓練課程': 'Explore training classes',
  '購物車': 'Shopping cart',
  '好運跑班服飾與跑步裝備': 'Nurture Running Team apparel and running gear',
  '商品列表': 'Product list',
  '開啟購物車': 'Open shopping cart',
  '返回首頁': 'Back to home',
  '為什麼我們一起團練': 'Why we run together',
  '週末，一個人跑是練習，一群人跑是好運！\n\n有同學、教練相約，用「輕鬆跑」或「長距離」練習，累積跑量，也享受一起運動的時光，\n大家依自己的狀態與配速，找合拍的夥伴一起跑步。\n\n團練位於台北、新竹兩地舉辦，\n安排在週末，日期、時間與集合地點依每次公告為準。\n\n好運跑班學員皆可「免費」報名，也歡迎邀請朋友一起參加！': 'Spend your weekend running with good company!\n\nMeet teammates and coaches for easy runs or long runs, build your mileage, and enjoy being active together. Find running partners who suit your pace and how you feel.\n\nGroup runs take place on weekends in Taipei and Hsinchu. Check each announcement for the date, time, and meeting point.\n\nRegistration is free for Nurture Running Team students, and friends are welcome to join!',
  '如何參加團練': 'How to join a group run',
  '進入 LINE 大家庭，查看當次團練記事本。': 'Join our LINE community and open the notes for the upcoming group run.',
  '依記事本說明登記參加；需要更改或取消，也請在同一則記事本更新。': 'Follow the note’s instructions to register. Use the same note to update or cancel your registration.',
  '出發前確認群內最新公告的日期、時間與集合地點。': 'Before leaving, check the latest group announcement for the date, time, and meeting point.',
  '團練報名與人數統計，統一以 LINE 大家庭記事本為準。網站不另外收集報名資料。': 'Registration and participant counts are managed in the LINE community notes. This website does not collect a separate registration.',
  '前往 LINE 大家庭報名': 'Register in the LINE community',
  '連結會開啟 LINE 社群邀請頁；加入後，請到記事本查看團練公告。': 'This link opens the LINE community invitation. After joining, check the notes for group run announcements.',
  '好運跑班 4 週年活動': 'Nurture Running Team 4th Anniversary',
  '商店結帳': 'Shop checkout',
  '購物車還沒有商品': 'Your cart is empty',
  '先到商店選擇商品，再回來確認品項與金額。尚未選購商品前，不需要填寫資料或匯款。': 'Choose products in the shop, then return to confirm your items and total. You do not need to enter details or transfer payment before selecting products.',
  '聯絡好運 Instagram': 'Contact us on Instagram',
  '我的匯款狀態': 'My transfer status',
  '查看課程應匯金額、後五碼提交狀態與財務核對結果。網站不會保存完整銀行帳號、網銀密碼或信用卡資料。': 'Check the amount due for your class, your transfer report, and the finance review result. The website does not store full bank account numbers, online banking passwords, or credit card details.',
  '待完成匯款': 'Awaiting bank transfer',
  '尚未提交匯款帳號後五碼。': 'The last five account digits have not yet been submitted.',
  '已回報，待人工核對': 'Reported, awaiting review',
  '已提交後五碼與申報金額，等待財務或超級管理員核對銀行入帳。': 'The last five digits and reported amount have been submitted. Finance or a super administrator will verify the bank payment.',
  '已由財務或超級管理員核實款項入帳。': 'Finance or a super administrator has confirmed receipt of payment.',
  '匯款資料需補充': 'More transfer details needed',
  '匯款資料需要補充或重新核對，請依核對說明處理。': 'Your transfer needs additional details or another review. Please follow the review instructions.',
  '登入後查看自己的匯款狀態': 'Sign in to check your transfer status',
  '系統只會顯示與登入信箱相符的課程報名資料。': 'Only registrations matching your signed-in email address are shown.',
  '登入查看': 'Sign in to view',
  '科學訓練，跑出好運': 'Science-based training for better running',
  '登入後建立你的跑者檔案': 'Sign in to create your runner profile',
  '記錄跑步目標、個人最佳與榮耀徽章。': 'Track your running goals, personal bests, and achievement badges.',
  '一個帳戶，記錄每次進步': 'One account for every step forward',
  '登入後修改跑者資料': 'Sign in to edit your runner profile',
  '登入後會留在此頁，繼續編輯你的跑者檔案。': 'After signing in, you will stay here to continue editing your runner profile.',
  '已報名學員請登入後查看課表並提交訓練回饋': 'Registered students: sign in to view training plans and submit feedback',
  '訓練課表、訓練資料、目標賽事和個人資料都會綁定到你的報名信箱。登入後，教練同步的課表和你提交的訓練回饋才會正確儲存。': 'Training plans, training data, race goals, and personal details are linked to your registration email. Sign in so your coach’s plans and your feedback are saved to the correct account.',
  '登入學員帳號': 'Sign in as a student',
  '登入後開放': 'Available after sign-in',
  '查看教練同步的訓練安排和當日重點。': 'View your coach’s training plan and daily priorities.',
  '提交里程、配速、RPE、疲勞和身體感受。': 'Submit distance, pace, RPE, fatigue, and how your body feels.',
  '目標與資料': 'Goals and profile',
  '維護比賽目標、聯絡方式和訓練溝通資料。': 'Update race goals, contact details, and training communication preferences.',
  '教練工作台': 'Coach workspace',
  '登入後使用教練工作台': 'Sign in to use the coach workspace',
  '使用管理員已登記的教練信箱登入，即可繼續查看此頁。': 'Sign in with the coach email registered by your administrator to continue.',
  '登入教練帳號': 'Sign in as a coach',
  '查看公開課程': 'View public classes',
  '課程點名': 'Class attendance',
  '報名資料': 'Registration details',
  '學員列表': 'Student list',
  '好運跑班教練端': 'Nurture Running Team · Coaches',
  '銀行對帳 · 財務工作區': 'Bank reconciliation · Finance workspace',
  '登入並輸入財務密碼後，選擇季度、上傳銀行明細，核對報名名單與繳費狀態。': 'Sign in and enter the finance password, then select a season, upload bank records, and reconcile registrations and payments.',
  '登入財務帳號': 'Sign in to finance',
  '管理員後台': 'Administration',
  '無法進入管理員後台': 'Administration access unavailable',
  '請先登入管理員帳號。': 'Sign in with an administrator account first.',
  '陪伴全球跑者的系統化訓練團隊': 'Structured coaching for runners around the world',
  '認識跑步，': 'Discover running.',
  '跑向更穩定的自己。': 'Become a more consistent runner.',
  '認識跑步，跑向更穩定的自己': 'Discover running. Become a more consistent runner.',
  '輕觸或滑動，留下你的好運足跡。': 'Tap or swipe to leave your running trail.',
  '一起帶領': 'Together, we guide',
  '每一次訓練': 'every training session',
  '好運跑班 X 週末團練': 'Nurture Running Team × Weekend Group Runs',
  '週末，一個人跑是練習，一群人跑是好運！': 'Spend your weekend running with good company!',
  '週末，一個人跑是練習，一群人跑是好運！\n\n和同學、教練相約，用輕鬆跑或長距離練習累積跑量，也享受一起運動的時光。\n依自己的狀態與配速，找到合拍的夥伴，一起把當日的訓練目標完成。\n\n團練在台北、新竹兩地的週末舉辦，\n日期、時間與集合地點，請看每次的 LINE 大家庭群組公告。\n\n團練為「免費」報名，也歡迎邀約朋友一起來跑步。': 'Spend your weekend running with good company!\n\nJoin teammates and coaches for easy runs or long runs, build your mileage, and enjoy training together. Find partners who suit your pace and how you feel, then work toward your goals for the day.\n\nWeekend group runs take place in Taipei and Hsinchu. Check the LINE community announcements for each run’s date, time, and meeting point.\n\nRegistration is free, and friends are welcome to join.',
  '2026第三季 招生中': '2026 Season 3 · Registration open',
  '• 開 • 始 • 報 • 名 •': '• REGISTRATION OPEN •',
  '❛ STAY CONSISTENT ❜\n穩定 • 累積\n在夏日裡保持頻率，靜心累積實力，讓每一步都跨得踏實。\n\n❝ KEEP MOVING ❞\n耐熱 • 抗暑\n無懼高溫規律推進，展現續航實力，維持最佳體能狀態。\n\n好運跑班的教練團隊，將以穩定的訓練節奏，陪您跑得更遠。': '❛ STAY CONSISTENT ❜\nBuild steadily\nKeep a regular rhythm through summer and patiently build the fitness behind every step.\n\n❝ KEEP MOVING ❞\nAdapt to the heat\nMaintain consistent training through warm weather to develop endurance and fitness.\n\nThe Nurture Running Team coaches will help you build a steady training rhythm and run farther.',
  '了解更多': 'Learn more',
  '了解團練': 'Explore group runs',
  '團練說明': 'Group run information',
  '了解團練：好運跑班 X 週末團練': 'Explore Nurture Running Team weekend group runs',
  '找到適合您的時間與訓練方向，不確定怎麼選，也歡迎諮詢好運Instagram。': 'Find a time and training focus that suit you. If you need help choosing, contact us on Instagram.',
  '新竹市': 'Hsinchu City',
  '新竹縣': 'Hsinchu County',
  '台北市': 'Taipei City',
  '新北市': 'New Taipei City',
  '苗栗': 'Miaoli',
  '台灣': 'Taiwan',
  '星期一': 'Monday',
  '星期二': 'Tuesday',
  '星期三': 'Wednesday',
  '星期四': 'Thursday',
  '星期五': 'Friday',
  '星期六': 'Saturday',
  '星期日': 'Sunday',
  '竹市初階班': 'Hsinchu Beginner Class',
  '新莊初階班': 'Xinzhuang Beginner Class',
  '第一運動場': 'First Stadium',
  '板橋第一運動場': 'Banqiao First Stadium',
  '新莊體育場': 'Xinzhuang Stadium',
  '照南國民小學': 'Zhaonan Elementary School',
  '費用與名額請透過 Instagram 諮詢': 'Contact us on Instagram for fees and availability',
  '我們陪你建立晨跑節奏 ─ 迎接更強的自己': 'Build a morning running routine and grow stronger with us',
  '下班時間不固定、需要晨練夥伴互相督促，並已能完成 10KM 的上班族跑者。': 'For working runners with unpredictable evenings who want morning training partners and can already run 10 km.',
  '晨間訓練、耐力建立、穩定輸出': 'Morning training, endurance, and consistent performance',
  '固定晨練，累積穩定訓練量': 'Build consistent mileage with regular morning sessions',
  '持續提升速度與有氧能力': 'Develop speed and aerobic fitness',
  '專業教練協助精進表現': 'Improve your performance with professional coaching',
  '賽前專業建議與訓練規劃': 'Race preparation advice and training plans',
  '不定期團練活動': 'Occasional community group runs',
  '裝備＆補給優惠': 'Discounts on gear and running nutrition',
  '建立晨跑作息，為訓練保留時間': 'Make time for training with a morning running routine',
  '持續累積有氧，培養耐力與速度': 'Build aerobic fitness, endurance, and speed',
  '透過教練指導，培養訓練習慣': 'Build training habits with coaching support',
  '上班族，下班時間不固定': 'Working runners with unpredictable evenings',
  '需要晨練夥伴互相督促': 'Runners looking for morning training partners',
  '我們陪你一步一步前進 ─ 讓跑步成為生活的一部分': 'Move forward step by step and make running part of your life',
  '想建立跑步習慣、循序漸進避免受傷，並已能完成 5-10KM 的跑步新手。': 'For newer runners who can run 5–10 km and want to build a routine while progressing gradually to reduce injury risk.',
  '初階跑班、基礎體能與穩定訓練': 'Beginner running, foundational fitness, and consistent training',
  '建立運動習慣，培養跑步基礎': 'Build an exercise routine and a foundation for running',
  '循序提升體能，累積自信與耐力': 'Improve fitness gradually while building confidence and endurance',
  '專業教練帶領，安心開始訓練': 'Start training confidently with professional guidance',
  '認識跑步要領，執行基礎訓練': 'Learn running fundamentals and practise basic workouts',
  '循序累積體能，找到適合的步調': 'Build fitness gradually and find your own pace',
  '透過團練陪伴，建立持續跑步的信心': 'Gain confidence to keep running with a supportive group',
  '跑步新手，想建立習慣': 'New runners looking to build a routine',
  '希望循序漸進，避免受傷': 'Runners seeking gradual progress and reduced injury risk',
  '我們幫助你穩紮穩打 ─ 逐步邁向更好狀態': 'Build a solid foundation and improve step by step',
  '剛開始跑步、想培養穩定習慣，並希望提升路跑成績、突破 PB 的跑者。': 'For newer runners seeking a consistent routine, better race results, and a new personal best.',
  '夜間團練、基礎跑力與配速控制': 'Evening group runs, running fundamentals, and pace control',
  '穩定訓練，持續累積體能': 'Build fitness through consistent training',
  '強化速度與耐力，打造基礎': 'Develop a foundation of speed and endurance',
  '專業指導，避免過度訓練': 'Manage training load with professional guidance',
  '穩定訓練，讓跑步成為日常安排': 'Make running part of your routine with consistent training',
  '從目前能力出發，累積每一次進步': 'Start with your current ability and build on each improvement',
  '和夥伴一起練習，朝自己的目標前進': 'Train with teammates and work toward your goals',
  '剛開始跑步，想培養穩定習慣': 'New runners seeking a consistent routine',
  '想提升路跑成績、突破 PB': 'Runners aiming for better race results and a new PB',
  '已能完成 5KM，並想更進一步': 'Able to run 5 km and ready to progress',
  '我們幫助你穩定突破 ─ 為下一次 PB 做好準備': 'Make steady progress and prepare for your next PB',
  '有固定跑步習慣、追求突破 PB，下半年已有目標賽事，並具半馬完賽能力的跑者。': 'For regular runners who can finish a half marathon and are targeting a personal best at a race in the second half of the year.',
  '速度能力、間歇訓練、賽事 PB 目標': 'Speed development, interval training, and race PB goals',
  '持續強化速度與有氧能力': 'Continue developing speed and aerobic fitness',
  '掌握節奏，提升跑步效率': 'Improve rhythm and running efficiency',
  '專業指導，避免訓練迷惘': 'Train with clear direction and professional guidance',
  '聚焦賽事目標，建立備賽方向': 'Set a clear training direction around your race goals',
  '穩定訓練，讓進步有跡可循': 'Track your progress through consistent training',
  '跟隨訓練安排，逐步接近目標成績': 'Follow a training plan and work toward your target time',
  '有固定跑步習慣，追求突破 PB': 'Regular runners targeting a new PB',
  '下半年已有目標賽事，需規律訓練': 'Runners preparing for a race in the second half of the year',
  '具半馬完賽能力（21KM）': 'Able to finish a half marathon (21 km)',
  '我們陪你穩定前進 ─ 建立長期進步的節奏': 'Find a consistent rhythm for long-term progress',
  '已有跑步基礎、想再進階，並希望提升賽事表現、突破成績的跑者。': 'For runners with a solid foundation who want to advance their training and improve race performance.',
  '夜間團練、肌耐力整合': 'Evening group runs and muscular endurance',
  '循序訓練，打造紮實基礎': 'Build a solid foundation through gradual training',
  '專業課表，降低疲勞與傷害風險': 'Structured plans to manage fatigue and injury risk',
  '結合交叉訓練，提升整體能力': 'Use cross-training to develop overall fitness',
  '精進技術，讓跑步更流暢': 'Refine your technique for smoother running',
  '整合有氧與肌耐力，強化跑步能力': 'Combine aerobic fitness and muscular endurance',
  '循序累積訓練，延續長期進步': 'Build training gradually for lasting progress',
  '已有跑步基礎，想再進階': 'Runners with a foundation who want to advance',
  '想提升賽事表現、突破成績': 'Runners seeking better race performance and results',
  '我們陪你扎穩根基 ─ 在本季跑出更好的自己': 'Build a strong foundation and make progress this season',
  '已有跑步習慣、想進一步挑戰，對賽事成績有追求，並已能完成 10KM 的跑者。': 'For regular runners who can run 10 km and want a new challenge and better race results.',
  '夜間團練、耐力與節奏訓練': 'Evening group runs, endurance, and tempo training',
  '穩定累積體能，持續強化有氧基礎': 'Build fitness consistently and strengthen your aerobic base',
  '循序訓練，為賽季做好準備': 'Prepare for race season with gradual training',
  '專業課表，避免過度訓練': 'Structured plans to manage training load',
  '累積有氧耐力，打穩進階體能': 'Build aerobic endurance for the next level of training',
  '掌握跑步節奏，練出穩定表現': 'Develop pacing skills for consistent performance',
  '調整訓練細節，提升跑步效率': 'Fine-tune your training to improve running efficiency',
  '已有跑步習慣，想進一步挑戰': 'Regular runners looking for a new challenge',
  '對賽事成績有追求': 'Runners with race performance goals',
  '我們幫助你精準訓練 ─ 跑出更好的表現': 'Train with purpose and improve your performance',
  '已有跑步習慣、想更進階，下半年有賽事目標，並已能完成 5-10KM 的跑者。': 'For regular runners who can run 5–10 km and want to progress toward a race in the second half of the year.',
  '夜間團練、配速感與有氧能力': 'Evening group runs, pacing, and aerobic fitness',
  '提升跑步效率，持續建立速度基礎': 'Improve running efficiency and develop a foundation for speed',
  '強化有氧能力與配速掌控': 'Strengthen aerobic fitness and pace control',
  '專業指導，協助穩定進步': 'Make steady progress with professional guidance',
  '培養配速感，掌握快慢節奏': 'Learn to judge your pace at different intensities',
  '強化有氧能力，累積賽事所需耐力': 'Build the aerobic fitness and endurance needed for racing',
  '改善跑步效率，讓每次訓練更扎實': 'Improve running efficiency and get more from each session',
  '已有跑步習慣，想更進階': 'Regular runners ready for the next level',
  '下半年有賽事目標': 'Runners targeting a race in the second half of the year',
  '我們陪你養成晨跑習慣 ─ 持續提升整體表現': 'Build a morning running habit and improve your overall performance',
  '晚上沒有時間、想在早晨運動，並希望培養跑步習慣或突破 PB 的跑者。': 'For runners with busy evenings who want to train in the morning, build a routine, or achieve a new PB.',
  '晨間團練、長距離基礎與賽事準備': 'Morning group runs, distance foundations, and race preparation',
  '早晨訓練，穩定養成紀律': 'Build discipline through consistent morning training',
  '累積有氧與速度，強化基礎能力': 'Strengthen your foundation with aerobic and speed training',
  '專業指導，避免走錯方向': 'Stay on track with professional guidance',
  '固定週末晨練，延續每週運動節奏': 'Keep a weekly routine with weekend morning sessions',
  '理解訓練原則，讓練習更有方向': 'Understand training principles and practise with purpose',
  '精進跑步技巧，累積個人目標所需能力': 'Refine your technique and build the fitness for your goals',
  '晚上沒空，想在早晨運動': 'Runners with busy evenings who prefer morning exercise',
  '希望培養跑步習慣或突破 PB': 'Runners seeking a regular habit or a new PB',
  '未滿五人不開班': 'At least five participants are required for the class to run',
  '我們陪你踏出第一步 ─ 在本季穩定成長，邁向進步': 'Take your first step with us and build steadily this season',
  '零基礎走跑入門、呼吸節奏、跑姿觀念與運動習慣建立': 'Run–walk basics, breathing rhythm, running form, and exercise habits',
  '從零開始，建立跑步習慣': 'Start from scratch and build a running habit',
  '循序訓練，培養穩定能力': 'Develop consistent fitness through gradual training',
  '專業課表，帶你安全入門': 'Start safely with a structured training plan',
  '從走跑練習開始，熟悉身體感受': 'Start with run–walk sessions and learn how your body feels',
  '學會呼吸與強度判斷，找到合適步調': 'Learn to judge breathing and intensity to find your pace',
  '建立跑步觀念，累積起跑信心': 'Learn running fundamentals and gain confidence to get started',
  '與你一同跨出起點 ─ 在本季穩定發揮，追求更好': 'Start with us and work toward consistent progress this season',
  '穩健起步，讓跑步融入日常': 'Start steadily and make running part of daily life',
  '扎根訓練，建立穩定的跑步基礎': 'Build a dependable running foundation',
  '專業課表，帶你安心起步': 'Begin confidently with a structured training plan',
  '課程與商品諮詢，歡迎聯絡好運 Instagram。': 'Contact Nurture Running Team on Instagram for class and product enquiries.',
  '從認識跑步、建立習慣，到準備賽事、挑戰自己，好運陪你一步一步訓練與規劃。\n透過有計畫的訓練與教練指導，和夥伴一起累積，跑向自己的目標。': 'From discovering running and building a routine to preparing for races and new challenges, Nurture Running Team supports you at every step.\nWork toward your goals with a structured plan, professional coaching, and teammates by your side.',
  '近期更新': 'Latest updates',
  '好運跑班如何陪你進步？': 'How does Nurture Running Team help you progress?',
  '從第一次規律跑步到站上賽道，我們把課表、團練、回饋與社群放在同一個訓練節奏裡': 'From your first running routine to race day, our plans, group sessions, feedback, and community support work together.',
  '初心到菁英都能加入': 'From beginners to experienced athletes',
  '依照程度安排初心補習班、初階班、夜跑班、早鳥班與 PB 班': 'Choose beginner, evening, early bird, or PB-focused classes to suit your level.',
  '清楚的週期訓練': 'Structured training cycles',
  '以 12 週為一個節奏，逐步建立體能、速度、耐力與賽事狀態': 'Build fitness, speed, endurance, and race readiness through a 12-week cycle.',
  '台灣多地團練': 'Group training across Taiwan',
  '本期整理台北、新竹、竹北、竹南等班級資訊': 'Explore this season’s classes in Taipei, Hsinchu, Zhubei, Zhunan, and more.',
  '現場動作與配速指導': 'On-site form and pacing guidance',
  '教練在團練現場觀察跑姿、節奏與完成狀況，提供當下建議': 'Coaches observe your form, rhythm, and progress during group sessions and offer immediate feedback.',
  '目標導向訓練': 'Training for your goals',
  '依照 5000m、10000m、半馬、全馬與 PB 目標安排訓練重點': 'Training priorities follow your 5K, 10K, half marathon, marathon, or PB goals.',
  '跑者社群陪伴': 'A supportive running community',
  '讓每一位跑者認識跑步、嘗試跑步，最後真正愛上跑步': 'Helping every runner discover running, give it a try, and grow to love it.',
  '速度與耐力': 'Speed and endurance',
  '節奏與配速': 'Rhythm and pacing',
  '半馬': 'Half marathon',
  '全馬': 'Marathon',
  '穩定完賽': 'Finish with confidence',
  '週期備賽': 'Periodized race preparation',
  '訓練日程': 'Training schedule',
  '週日紫色Logo': 'Nurture Running Team purple logo',
  '好運跑班品牌精神': 'The Nurture Running Team philosophy',
  '好運跑班教練與跑者賽前集結': 'Nurture Running Team coaches and runners gathering before a race',
}
