// Server-returned attendance and substitution messages shown in coach/admin workspaces.
export const coachActionEnglishCopy: Record<string, string> = {
  '目前帳號沒有教練權限。': 'This account does not have coach access.',
  '未命名教練': 'Unnamed coach',
  '缺少課次安排。': 'A session assignment is required.',
  '找不到課次安排。': 'Session assignment not found.',
  '找不到課程開始時間。': 'Class start time not found.',
  '本堂已完成簽到，不能再變更代班。': 'Check-in is complete. The substitute can no longer be changed.',
  '不支援的操作。': 'This action is not supported.',
  '更新教練到課資料失敗。': 'Unable to update coach attendance.',
  '請先切換至教練測試模式。': 'Switch to coach test mode first.',
  '找不到帳號資料。': 'Account details not found.',
  '測試學員': 'Test student',
  '測試聯絡人': 'Test contact',
  '測試教練': 'Test coach',
  '班級或課次無效。': 'Invalid class or session.',
  '測試停課': 'Test cancellation',
  '測試課次已標記停課，不影響正式課表。': 'Test session cancelled. Live schedules are unchanged.',
  '測試課次已恢復。': 'Test session restored.',
  '沒有可儲存的測試點名資料。': 'No test attendance records to save.',
  '本堂已標記為停課；原班學員不列為請假或扣除，受影響的補課學員可重新選擇課次。': 'Session cancelled. Original class students are not marked on leave or charged a session; affected makeup students can choose another session.',
  '已恢復本堂課程，可重新進行點名。': 'Session restored. Attendance can be recorded again.',
  '尚未開始的課次不能提前點名。': 'Attendance cannot be recorded before the session starts.',
  '沒有可儲存的點名資料。': 'No attendance records to save.',
  '本堂目前標記為停課，請先恢復開課再儲存點名。': 'This session is cancelled. Restore it before saving attendance.',
  '已有請假或補課安排，原班請假紀錄必須保留。若需更正，請先由管理員核對補課狀態。': 'A leave or makeup arrangement already exists. Keep the original class leave record. Ask an administrator to check the makeup status before correcting it.',
  '點名名單包含不屬於本班、也未安排本堂補課的學員。': 'The roster includes students who are neither enrolled in this class nor scheduled for this makeup session.',
  '測試課次無效。': 'Invalid test session.',
  '目前不在簽到開放時間內；簽到僅限課前 15 分鐘至開課後 15 分鐘。': 'Check-in is closed. It is available from 15 minutes before until 15 minutes after the class starts.',
  '測試沙盒已記錄準時簽到。': 'On-time check-in recorded in the test sandbox.',
  '測試沙盒已記錄遲到簽到。': 'Late check-in recorded in the test sandbox.',
  '請填寫請假原因。': 'Enter a reason for leave.',
  '測試請假已寫入獨立沙盒，不會通知真實管理員或教練。': 'Test leave recorded in the isolated sandbox. No real administrators or coaches will be notified.',
  '這項測試操作目前不適用。': 'This test action is not currently available.',
  '這堂課已不在你的任課或代班授權範圍。': 'You are no longer authorized to teach or substitute for this session.',
  '只有本堂實際授課教練或管理員可以完成到課簽到。': 'Only the assigned teaching coach or an administrator can check in for this session.',
  '管理員代登簽到必須填寫原因。': 'A reason is required for an administrator to record check-in.',
  '本堂尚未設定簽到判定開始時間，請聯絡管理員補齊。': 'The check-in start time is missing. Ask an administrator to set it.',
  '本堂已停課，不需要簽到。': 'This session is cancelled. Check-in is not required.',
  '本堂已經完成簽到。': 'Check-in is already complete for this session.',
  '課次狀態已變更，請重新整理後再操作。': 'The session status has changed. Refresh before continuing.',
  '簽到狀態已變更，請重新整理。': 'The check-in status has changed. Refresh to continue.',
  '已為本堂實際授課教練代登準時到課。': 'On-time attendance recorded for the assigned teaching coach.',
  '已為本堂實際授課教練代登遲到到課。': 'Late attendance recorded for the assigned teaching coach.',
  '已完成準時簽到。': 'On-time check-in completed.',
  '已完成遲到簽到。': 'Late check-in completed.',
  '只有原定教練或管理員可以提出本堂請假。': 'Only the scheduled coach or an administrator can request leave for this session.',
  '本堂已經完成簽到，不能再提出一般請假。': 'Check-in is complete. A regular leave request can no longer be submitted.',
  '本堂已停課，不能提出請假或代班變更。': 'This session is cancelled. Leave and substitution changes are not available.',
  '課次已結束；只有管理員可填寫原因進行異常處理。': 'The session has ended. Only an administrator can handle exceptions with a recorded reason.',
  '代班狀態已更新，請重新整理後再操作。': 'The substitution status has changed. Refresh before continuing.',
  '本堂已有正在處理或已生效的代班安排。': 'This session already has a pending or confirmed substitution.',
  '受邀帳號目前沒有教練權限。': 'The invited account does not currently have coach access.',
  '已為本堂原定教練登記請假並送出代班邀請。': 'Leave recorded for the scheduled coach and a substitute invitation sent.',
  '請假與代班邀請已送出，等待受邀教練回覆。': 'Leave and substitute invitation submitted. Awaiting the invited coach’s reply.',
  '請假已送出，等待管理員安排代班。': 'Leave submitted. Awaiting an administrator’s substitute arrangement.',
  '代班回覆無效。': 'Invalid substitution response.',
  '這堂課目前沒有等待你回覆的代班邀請。': 'No substitution invitation for this session is awaiting your reply.',
  '目前帳號沒有教練權限，不能回覆代班邀請。': 'This account cannot reply to substitution invitations without coach access.',
  '本堂已停課，不能再回覆代班。': 'This session is cancelled. Substitution replies are closed.',
  '課次已結束或尚未設定開始時間，請由管理員進行異常處理。': 'The session has ended or has no start time. Ask an administrator to handle the exception.',
  '代班邀請已被處理，請重新整理後確認最新狀態。': 'This substitution invitation has already been handled. Refresh to check the latest status.',
  '已接受代班邀請；代班已生效，並同步至管理員後台。': 'Substitution accepted and confirmed. The administrator workspace has been updated.',
  '已接受管理員指派的代班邀請，等待管理員最終確認。': 'Administrator-assigned substitution accepted. Awaiting final administrator confirmation.',
  '已拒絕代班邀請；原教練可以重新邀請其他教練。': 'Substitution declined. The original coach can invite another coach.',
  '已拒絕管理員指派的代班邀請，管理員將重新安排。': 'Administrator-assigned substitution declined. An administrator will arrange another coach.',
  '不能邀請自己代班。': 'You cannot invite yourself as a substitute.',
  '請選擇要邀請的代班教練。': 'Choose a substitute coach to invite.',
  '只有受邀教練可以回覆代班邀請。': 'Only the invited coach can reply to the substitution invitation.',
}
