// Complete interface strings for season enrollment review; authored notes are preserved.
export const adminEnrollmentEnglishCopy: Record<string, string> = {
  '報名編號': 'Registration number',
  '報名時點': 'Enrollment timing',
  '計價方式': 'Pricing method',
  '計費起始課次': 'Billing start session',
  '收費課次': 'Billable sessions',
  '緊急聯絡人電話': 'Emergency contact phone',
  '推薦資格': 'Referral eligibility',
  '發票方式': 'Invoice method',
  '載具或信箱': 'Invoice carrier or email',
  '教練代課同意': 'Coach substitution consent',
  '課程規範同意': 'Class rules consent',
  '報名最終同意': 'Final registration consent',
  '課程條款版本': 'Class terms version',
  '退費政策版本': 'Refund policy version',
  '隱私政策版本': 'Privacy policy version',
  '發票說明版本': 'Invoice information version',
  '報價鎖定至': 'Quote locked until',
  '已扣除課次': 'Excluded sessions',
  '報名備註': 'Registration note',
  '招生中': 'Enrolling',
  '季度招生總覽': 'Season enrollment overview',
  '（前台招生）': '(Public enrollment)',
  '報名記錄': 'Registrations',
  '新生 / 舊生': 'New / Returning students',
  '已知報名金額': 'Known registration total',
  '所有金額已計入': 'All amounts included',
  '班級名額': 'Class capacity',
  '平均': 'Average',
  '｜中位數': ' | Median',
  '報名趨勢': 'Registration trend',
  '名單與審核': 'Roster and review',
  '在同一份緊湊名單中查看資料、核對匯款與處理異常。': 'Review registrations, check transfers, and resolve exceptions in one roster.',
  '在同一份緊湊名單中核對商城匯款並安排跑班自取。': 'Review shop transfers and arrange team pickup in one roster.',
  '商城訂單': 'Shop orders',
  '全部班級': 'All classes',
  '全部身分': 'All student types',
  '全部點名核對': 'All attendance reviews',
  '計費異常待處理': 'Billing exceptions to review',
  '匯出完整資料': 'Export all details',
  '身分': 'Student type',
  '搜尋姓名、信箱或後五碼': 'Search name, email, or last five digits',
  '搜尋顧客、訂單編號或商品': 'Search customer, order number, or product',
  '跑班自取': 'Team pickup',
  '已確認商城匯款入帳，請聯絡顧客安排跑班自取。': 'Shop payment confirmed. Contact the customer to arrange team pickup.',
  '報名時間': 'Registration time',
  '查看': 'View',
  '訂單已建立，尚未提交匯款帳號後五碼。': 'Order created; the last five digits of the transfer account have not been submitted.',
  '已提交後五碼，等待財務核對銀行入帳。': 'Last five digits submitted; awaiting bank payment verification.',
  '已確認入帳，可聯絡顧客安排跑班自取。': 'Payment confirmed. Contact the customer to arrange team pickup.',
  '匯款資料需要補充或重新核對。': 'Transfer details need more information or another review.',
  '類型': 'Type',
  '季度': 'Season',
  '訂單編號': 'Order number',
  '班級或商品': 'Class or product',
  '取貨方式': 'Collection method',
  '管理備註': 'Administrator note',
  '商城': 'Shop',
  '請在管理備註填寫核對依據，例如入帳日期、實收金額與銀行交易參考號。': 'Enter the verification evidence in the administrator note, such as the payment date, received amount, and bank reference.',
  '無法取得同步程式。': 'Unable to load the synchronization script.',
  '商品': 'Product',
  '庫存': 'Stock',
  '已預留': 'Reserved',
  '未預留': 'Not reserved',
  '報名班級': 'Registered class',
  'Google 表格同步': 'Google Sheets synchronization',
  '同步異常': 'Synchronization error',
  '同步正常': 'Synchronization up to date',
  '已連結': 'Connected',
  '等待第一次自動同步': 'Awaiting first automatic synchronization',
  '開啟表格': 'Open spreadsheet',
  '同步設定': 'Synchronization settings',
  '教練已點名到課，但到課日期早於學員選擇的計費起點。': 'The coach recorded attendance before the student’s selected billing start date.',
  '本季度尚無報名資料。': 'No registrations for this season yet.',
  '顧客': 'Customer',
  '訂單 / 商品': 'Order / Product',
  '後五碼 / 取貨': 'Last five digits / Collection',
  '未載入商品': 'Products not loaded',
  '計費異常': 'Billing exception',
  '訂單': 'Order',
  '未指定班級': 'No class assigned',
  '匯款／取貨': 'Transfer / Collection',
  '商城訂單詳情': 'Shop order details',
  '學員報名詳情': 'Student registration details',
  '此季度已封存，僅供查閱，不再修改帳單。': 'This season is archived. Records are read-only and bills cannot be changed.',
  '客戶備註': 'Customer note',
  '點名與計費起點核對': 'Attendance and billing start review',
  '已到課，早於計費起點': 'Attendance recorded before billing start',
  '已處理：': 'Resolved: ',
  '補繳完成': 'Additional payment received',
  '免除補繳': 'Additional payment waived',
  '重新開啟': 'Reopen',
  '處理備註（選填）': 'Resolution note (optional)',
  '已補繳': 'Additional payment received',
  '記錄匯款核對、自取時間或聯絡結果': 'Record payment verification, pickup time, or contact outcome',
  '記錄核對結果或需要補充的資料': 'Record verification results or required information',
  '商城使用銀行匯款付款，入帳後再安排跑班自取；可在銀行對帳頁核對，也可於此人工確認。': 'Shop orders use bank transfers and team pickup after payment. Verify payments in Bank reconciliation or confirm them here.',
  '財務可透過銀行對帳確認；超級管理員亦可核實實際入帳後，填寫管理備註並人工確認。系統保留操作人、時間及核對依據，財務之後仍可補登銀行對帳。': 'Finance can confirm through Bank reconciliation. Super administrators can also verify receipt, record the evidence in an administrator note, and confirm manually. The actor, time, and evidence are recorded; finance can add the bank reconciliation later.',
  '確認入帳（管理員）': 'Confirm payment (administrator)',
  '確認匯款並安排自取': 'Confirm transfer and arrange pickup',
  '補件通知與紀錄': 'Information requests and history',
  '標記匯款資料需補充': 'Request more transfer details',
  '刪除記錄': 'Delete record',
  'Google 表格同步設定': 'Google Sheets synchronization settings',
  '季度名單': 'Season roster',
  'Google 表格自動同步': 'Automatic Google Sheets synchronization',
  '在所選季度表格開啟「擴充功能 → Apps Script」': 'Open Extensions → Apps Script in the selected season spreadsheet',
  '貼上以下程式並儲存': 'Paste the script below and save',
  '執行 setupGoodLuckRosterSync 並授權一次': 'Run setupGoodLuckRosterSync and authorize it once',
  'Google 表格同步程式': 'Google Sheets synchronization script',
  '複製同步程式': 'Copy synchronization script',
}
