// Administrator navigation, account management, and season overview copy.
export const adminEnglishCopy: Record<string, string> = {
  '總覽': 'Overview',
  '掌握待處理事項、報名與營運概況。': 'Review pending tasks, registrations, and operations.',
  '學員管理': 'Students',
  '查找學員、課程、匯款與課表權限。': 'Find students, classes, transfers, and training access.',
  '教練管理': 'Coaches',
  '管理教練身份、到課、請假與代班。': 'Manage coach accounts, attendance, leave, and substitutions.',
  '季度管理': 'Seasons',
  '管理招生季度、課程資料與學員名單。': 'Manage enrollment seasons, class details, and student rosters.',
  '商城商品': 'Products',
  '維護商品內容、庫存與上下架狀態。': 'Manage product details, stock, and availability.',
  '內容中心': 'Site content',
  '更新網站圖片、文字與公開頁面內容。': 'Update website images, copy, and public pages.',
  '匯入銀行資料並完成人工入帳核對。': 'Import bank records and review payments.',
  '收款帳戶': 'Payment accounts',
  '維護課程匯款所使用的官方帳戶。': 'Manage official accounts used for class payments.',
  '暫無資料': 'No data yet',
  '讀取管理員後台失敗。': 'Unable to load the administrator workspace.',
  '變更已儲存，但重新讀取失敗。請重新整理確認最新資料，不必重複提交。': 'Changes were saved, but the updated data could not be loaded. Refresh to check the latest data; do not submit again.',
  '操作已完成。': 'Action completed.',
  '已依入帳班級自動關聯。': 'Linked automatically by confirmed paid class.',
  '尚無已入帳班級關聯。': 'No confirmed paid class assignment yet.',
  '如需調整任課教練，請到季度管理修改班級；臨時代班請在教練管理處理。': 'To change a class coach, edit the class in Seasons. Manage temporary substitutions in Coaches.',
  '正在讀取管理員後台...': 'Loading administrator workspace…',
  '集中管理學員、教練、季度、網站內容與課程匯款資料。': 'Manage students, coaches, seasons, website content, and class payment details in one place.',
  '目前工作區': 'Current workspace',
  '管理員後台導航': 'Administrator navigation',
  '正式資料已連線': 'Connected to live data',
  '營運工作台': 'Operations workspace',
  '商品有未儲存的變更。確定放棄並切換工作區？': 'This product has unsaved changes. Discard them and switch workspaces?',
  '超級管理員': 'Super administrator',
  '顯示所有學員、綁定教練、匯款狀態、課表狀態與最近訓練回饋。': 'View all students, assigned coaches, payment status, training access, and recent feedback.',
  '搜尋姓名、信箱、教練或課程': 'Search name, email, coach, or class',
  '全部課表': 'All training access',
  '已開通': 'Enabled',
  '未開通': 'Not enabled',
  '未提供信箱': 'Email not provided',
  '課表已開通': 'Training access enabled',
  '課表未開通': 'Training access not enabled',
  '綁定教練': 'Assigned coach',
  '尚未綁定': 'Not assigned',
  '尚無課程': 'No class yet',
  '匯款狀態': 'Transfer status',
  '建立時間': 'Created at',
  '綁定操作': 'Assignment actions',
  '信箱': 'Email',
  '課表': 'Training plan',
  '沒有符合條件的學員。': 'No students match these filters.',
  '教練帳號登記': 'Coach account registration',
  '管理員只需登記既有公開教練資料的登入信箱；已註冊帳號會在信箱已驗證後原子連結，未註冊者會等首次登入，不會替他建立帳號或寄送郵件。': 'Register the sign-in email for an existing public coach profile. Existing accounts are linked after email verification; unregistered coaches are linked on first sign-in. This does not create accounts or send emails.',
  '已啟用': 'Enabled',
  '共': 'Total',
  '筆登記': 'registrations',
  '選擇要登記的公開教練身份': 'Choose a public coach profile to register',
  '選擇要登記的教練': 'Choose a coach to register',
  '目前沒有待登記的公開教練': 'No public coach profiles awaiting registration',
  '教練登入信箱': 'Coach sign-in email',
  '登記教練帳號': 'Register coach account',
  '名冊會顯示全部已登記信箱，包括尚未註冊、尚未驗證及明確停用的帳號。停用不會因日後登入自動恢復。': 'The roster includes every registered email, including accounts that are not yet created, unverified, or disabled. Signing in does not automatically restore a disabled account.',
  '搜尋姓名、信箱或課程': 'Search name, email, or class',
  '篩選教練帳號狀態': 'Filter coach account status',
  '教練已啟用': 'Coach access enabled',
  '帳號狀態暫不可查': 'Account status temporarily unavailable',
  '已註冊 · 信箱已驗證': 'Registered · Email verified',
  '已註冊 · 等待信箱驗證': 'Registered · Awaiting email verification',
  '尚未註冊，等待首次登入': 'Not registered; awaiting first sign-in',
  '· 管理員權限保留': '· Administrator access retained',
  '負責課程': 'Assigned classes',
  '公開教練身份': 'Public coach profile',
  '的公開教練身份': 'public coach profile',
  '尚未連結': 'Not linked',
  '（已連結其他帳號）': '(Linked to another account)',
  '保留管理員權限（不可停用）': 'Administrator access retained (cannot disable)',
  '完成資料庫登記後可管理狀態': 'Status can be managed after registration is complete',
  '重新啟用': 'Re-enable',
  '停用教練帳號': 'Disable coach account',
  '檢查並啟用': 'Check and enable',
  '目前沒有符合條件的教練帳號。': 'No coach accounts match these filters.',
  '季度設定、課程資料、歷史學員與招生統計集中在這裡。': 'Find season settings, class details, historical rosters, and enrollment statistics here.',
  '季度管理內容': 'Season management sections',
  '學員與統計': 'Students and statistics',
  '季度設定': 'Season settings',
  '新增收款帳戶': 'Add payment account',
  '帳戶池供管理員整理銀行對帳通道；商城買家會在結帳頁看到目前的好運官方匯款資料，不會看到內部帳戶分配結果。': 'The account pool organizes internal reconciliation channels. Shop buyers see the current official transfer details at checkout, not internal account assignments.',
  '通道名稱，例如 A 帳戶': 'Channel name, for example Account A',
  '銀行代碼，可留空': 'Bank code (optional)',
  '收款帳號': 'Receiving account number',
  '分配權重': 'Assignment weight',
  '新增帳戶': 'Add account',
  '收款帳戶池': 'Payment account pool',
  '供課程與商城匯款對帳使用；商城付款完成後仍採跑班自取。': 'Used for class and shop transfer reconciliation. Shop orders are still collected from the running team after payment.',
  '還沒有收款帳戶。': 'No payment accounts yet.',
  '啟用中': 'Active',
  '權重': 'Weight',
  '最近分配：': 'Last assigned: ',
  '停用': 'Disable',
  '啟用': 'Enable',
  '學員': 'Student',
  '營運總覽': 'Operations overview',
  '商品正在儲存，完成後才能離開。': 'The product is being saved. Wait for it to finish before leaving.',
  '商品仍有未儲存變更，確定要放棄並離開嗎？': 'This product has unsaved changes. Discard them and leave?',
  '操作未完成，請查看錯誤提示後再試一次。': 'The action did not complete. Review the error and try again.',
  '請先選擇教練身份並填寫登入信箱。': 'Choose a coach profile and enter the sign-in email first.',
  '請填寫通道名稱、戶名、銀行名稱與收款帳號。': 'Enter the channel name, account holder, bank name, and account number.',
  '學員詳情': 'Student details',
  '手機管理員後台': 'Mobile administrator workspace',
  '好運跑班，返回首頁': 'Nurture Running Team, back to home',
  '商品仍有未儲存變更，確定要放棄並返回首頁嗎？': 'This product has unsaved changes. Discard them and return home?',
  '開啟更多管理功能': 'Open more administration tools',
  '同步異常，請查看提示': 'Update issue — check the message',
  '返回總覽': 'Back to overview',
  '快速找到學員': 'Find a student quickly',
  '搜尋學員': 'Search students',
  '姓名、信箱、教練或課程': 'Name, email, coach, or class',
  '學員篩選': 'Student filters',
  '待開通課表': 'Training access pending',
  '未綁教練': 'No coach assigned',
  '匯款待核對': 'Transfers awaiting review',
  '課表待處理': 'Training plans to review',
  '付款狀態': 'Payment status',
  '查看資料': 'View details',
  '調整教練': 'Review coach assignment',
  '返回學員列表': 'Back to students',
  '帳號資料': 'Account details',
  '加入時間': 'Joined at',
  '課表權限': 'Training plan access',
  '尚未開通': 'Not enabled yet',
  '學員詳情頁籤': 'Student detail tabs',
  '課程與權限': 'Classes and access',
  '付款紀錄': 'Payment history',
  '目前課程': 'Current classes',
  '教練與課表權限': 'Coach and training access',
  '目前教練': 'Current coach',
  '已開通（由現有付款／課表資料判定）': 'Enabled (based on existing payment / plan records)',
  '目前可用範圍：': 'Currently available: ',
  '後台目前沒有獨立編輯學員資料或切換課表權限的操作；此處保留真實狀態與教練綁定功能，不顯示未實際完成的切換。': 'This workspace currently has no separate student-profile editor or training-access toggle. It displays the recorded status and coach assignment.',
  '筆': 'records',
  '目前沒有與此信箱相符的付款紀錄。': 'No payment records match this email.',
  '這裡只提供最近回饋時間；完整內容請到既有教練／學員頁面查看。': 'Only the latest feedback time is shown here. View the full content in the coach or student workspace.',
  '管理員備註': 'Administrator notes',
  '後台目前沒有提供備註欄位的儲存功能，因此手機端暫不提供可能無法保留的輸入框。': 'Saving administrator notes is not currently supported, so this mobile view does not offer a notes input.',
  '只登記既有公開教練資料的登入信箱；未註冊者等首次登入，已停用者不會自動恢復。': 'Register sign-in emails for existing public coach profiles. New users are linked on first sign-in; disabled accounts are not restored automatically.',
  '登入信箱': 'Sign-in email',
  '帳號狀態': 'Account status',
  '教練帳號狀態篩選': 'Coach account status filter',
  '信箱已驗證': 'Email verified',
  '待驗證': 'Awaiting verification',
  '待首次登入': 'Awaiting first sign-in',
  '管理員權限保留：': 'Administrator access retained: ',
  '不可用教練停用操作。': 'The coach disable action is not available.',
  '完成資料庫登記後可管理狀態。': 'Status can be managed after registration is complete.',
  '沒有符合條件的教練帳號。': 'No coach accounts match these filters.',
  '季度管理分段': 'Season management sections',
  '未儲存保護：': 'Unsaved changes: ',
  '目前商品有未儲存變更，請先儲存或放棄後再離開。': 'This product has unsaved changes. Save or discard them before leaving.',
  '商品編輯器沿用現有圖片裁切、規格、上下架與刪除保護。': 'The product editor includes image cropping, variants, availability, and deletion safeguards.',
  '＋ 新增': '+ Add',
  '上方維護對外匯款資料，下方帳戶池供內部對帳使用。': 'Manage customer transfer details above. The account pool below is for internal reconciliation.',
  '＋ 新增收款帳戶': '+ Add payment account',
  '管理員主要導航': 'Main administrator navigation',
  '對帳': 'Reconciliation',
  '更多': 'More',
  '更多管理功能': 'More administration tools',
  '季度、商品、內容與收款帳戶集中在這裡。': 'Find seasons, products, site content, and payment accounts here.',
  '關閉更多管理功能': 'Close administration tools',
  '招生季度、課程與統計': 'Enrollment seasons, classes, and statistics',
  '內容、規格、庫存與上下架': 'Product details, variants, stock, and availability',
  '首頁、公開頁面與教練資料': 'Homepage, public pages, and coach profiles',
  '通道、權重與啟用狀態': 'Channels, weights, and active status',
  '任課教練關聯': 'Class coach assignment',
  '依入帳班級自動關聯': 'Assigned automatically by confirmed paid class',
  '尚無正式教練關聯': 'No official coach assignment yet',
  '請在季度管理調整班級任課教練；臨時代班請在教練管理處理。不再單獨新增或解除綁定。': 'Change class coaches in Seasons and manage temporary substitutions in Coaches. Individual coach links are no longer added or removed separately.',
  '建立後加入對帳帳戶池，可隨時停用。': 'The account is added to the reconciliation pool and can be disabled at any time.',
  '關閉新增收款帳戶': 'Close add payment account',
  '通道名稱 *': 'Channel name *',
  '例如 A 帳戶': 'For example, Account A',
  '戶名 *': 'Account holder *',
  '輸入銀行戶名': 'Enter the bank account holder',
  '銀行名稱 *': 'Bank name *',
  '銀行': 'Bank',
  '收款帳號 *': 'Receiving account number *',
  '輸入完整帳號': 'Enter the full account number',
  '待匯款': 'Awaiting transfer',
  '需補充／重複待處理': 'More information needed / Duplicate to review',
  '本季報名學員': 'Students registered this season',
  '本季班級': 'Classes this season',
  '季度總覽': 'Season overview',
  '各季獨立統計；商城訂單請至銀行對帳查看。': 'Seasons are counted separately. View shop orders in Bank reconciliation.',
  '（當前招生）': '(Currently enrolling)',
  '尚未建立季度。': 'No seasons created yet.',
  '歷史資料僅供查閱，已停止報名、同步與修改。': 'Historical records are read-only. Registration, synchronization, and editing are closed.',
  '下方數字與名單僅包含這一季。': 'The figures and roster below cover this season only.',
  '報名學員依信箱去重，排除需補充／重複記錄；入帳數為課程報名筆數。': 'Students are counted by unique email, excluding records needing more information or marked as duplicates. Paid totals count class registrations.',
  '封存核對紀錄': 'Archive reconciliation record',
  '本季待核對': 'Awaiting review this season',
  '本季沒有待核對款項。': 'No payments are awaiting review this season.',
  '本季班級入帳概況': 'Class payments this season',
  '教練簽到、請假與代班': 'Coach attendance, leave, and substitutions',
  '待處理': 'Pending',
  '異常': 'Exceptions',
  '原教練可直接邀請代班；受邀教練接受後立即生效，管理員保留查看與修正權限。': 'Coaches can invite substitutes directly. The substitution takes effect when accepted; administrators can review and correct it.',
  '學員出勤與跨班補課核對': 'Student attendance and cross-class makeup review',
  '查看學員自主簽到、教練現場點名及補課來源。管理員可核對全部班級，但不能冒充學員自主簽到。': 'Review student check-ins, coach roll calls, and makeup class origins. Administrators can review all classes but cannot check in as students.',
  '開啟課程出勤核對': 'Open class attendance review',
  '期間應到': 'Expected attendance',
  '準時': 'On time',
  '遲到': 'Late',
  '請假代班完成': 'Leave covered by substitute',
  '待安排代班': 'Substitute needed',
  '未簽到待確認': 'Missing check-in to review',
  '資料會每 45 秒自動更新；需要立即核對時可手動刷新。': 'Updates automatically every 45 seconds. Refresh manually for the latest records.',
  '刷新教練出勤': 'Refresh coach attendance',
  '優先查看': 'Priority view',
  '全部年份': 'All years',
  '全部月份': 'All months',
  '全部課程': 'All classes',
  '全部教練': 'All coaches',
  '全部排班': 'All assignments',
  '只看請假': 'Leave only',
  '只看代班': 'Substitutions only',
  '原定出勤': 'Original assignments',
  '只看異常': 'Exceptions only',
  '未簽到待確認（代班）': 'Substitute check-in to review',
  '目前沒有符合篩選條件的課次。': 'No sessions match these filters.',
  '課酬目前只預留事實來源與狀態欄位，所有課次統一顯示「待設定課酬」；尚未啟用金額、扣薪、結算或付款。': 'Compensation currently records only the source and status. All sessions show “Compensation not configured”; amounts, deductions, settlement, and payments are not enabled.',
  '優先篩選': 'Priority filter',
  '年份篩選': 'Year filter',
  '月份篩選': 'Month filter',
  '商品管理': 'Product management',
  '件商品': 'products',
  '新增商品': 'Add product',
  '全部商品': 'All products',
  '已上架': 'Published',
  '已下架': 'Unpublished',
  '低庫存（5 件以下）': 'Low stock (5 or fewer)',
  '件': 'items',
  '目前還沒有商品': 'No products yet',
  '建立第一件商品': 'Create the first product',
  '從第一件商品開始': 'Start with your first product',
  '填寫簡介、設定尺碼，再上傳主圖即可建立。': 'Add a description, configure sizes, and upload a main image to create a product.',
  '商城商品工作區': 'Shop product workspace',
  '商品清單': 'Product list',
  '搜尋商品': 'Search products',
  '篩選商品狀態': 'Filter product status',
  '可捲動商品清單': 'Scrollable product list',
  '首頁與活動': 'Homepage and events',
  '內容總覽': 'Content overview',
  '查看可管理區域': 'View editable sections',
  '首頁輪播': 'Homepage slideshow',
  '圖片與排序': 'Images and order',
  '首頁文案': 'Homepage copy',
  '近期報名與課程預覽': 'Recent enrollment and class previews',
  '活動入口': 'Event links',
  '報名與活動連結': 'Registration and event links',
  '公開頁面': 'Public pages',
  '訓練日程頁': 'Training schedule page',
  '首屏、加入流程與常見問題': 'Hero, joining process, and FAQs',
  '團隊與教練照片': 'Team and coach photos',
  '課程頭像、團隊照與介紹': 'Class portraits, team photos, and introductions',
  '商店與週年': 'Shop and anniversary',
  '主視覺與商店文案': 'Hero imagery and shop copy',
  '品牌故事與對象': 'Brand story and audience',
  '首屏、影片與成長路徑': 'Hero, video, and progress stories',
  '系列文案與圖片': 'Series copy and images',
  '週年活動': 'Anniversary event',
  '活動文案與報名提示': 'Event copy and registration guidance',
  '全站設定': 'Site-wide settings',
  '品牌與聯絡': 'Brand and contact',
  '頁尾 Logo、社群與聯絡': 'Footer logo, social links, and contact',
  '目前顯示：': 'Currently showing: ',
  '網站內容中心': 'Website content center',
  '所有日常可替換的圖片與文案集中在這裡。商品本身請到「商城商品」管理。': 'Manage website images and copy here. Manage products in Products.',
  '發布位置：': 'Published on: ',
  '首頁首屏輪播': 'Homepage hero slideshow',
  '首頁近期報名、課程預覽': 'Homepage enrollment and class previews',
  '首頁近期報名入口': 'Homepage enrollment links',
  '完整訓練日程頁': 'Full training schedule page',
  '課程詳情與團隊陣容頁面': 'Class details and team pages',
  '商店與週年活動頁': 'Shop and anniversary pages',
  '關於我們完整頁面': 'Full About us page',
  '學員見證完整頁面': 'Full student stories page',
  '榮耀徽章完整頁面': 'Full achievement badges page',
  '週年活動頁': 'Anniversary event page',
  '頁尾與聯絡入口': 'Footer and contact links',
}
