// Coach workspace interface and system messages, separate from coach-authored notes.
export const coachWorkspaceEnglishCopy: Record<string, string> = {
  '報名姓名': 'Registrant name',
  '學員身分': 'Student type',
  '新學員': 'New student',
  '舊學員': 'Returning student',
  '推薦人': 'Referrer',
  '病史或運動傷害': 'Medical history or sports injuries',
  '起算上課日': 'Billing start date',
  '曾提前上課': 'Attended before the billing start',
  '發票寄送方式': 'Invoice delivery method',
  '發票寄送資料': 'Invoice delivery details',
  '統編與抬頭': 'Tax ID and invoice title',
  '同意教練代課': 'Coach substitution consent',
  '同意課程規則': 'Class rules consent',
  '最終確認': 'Final confirmation',
  '同意時間': 'Consent time',
  '最近回饋': 'Recent feedback',
  '全部狀態': 'All statuses',
  'Supabase 尚未設定。': 'The account service is not configured.',
  '請先登入。': 'Sign in first.',
  '緊急聯絡人': 'Emergency contact',
  '請先登入教練帳號。': 'Sign in with your coach account.',
  '請先登入教練或管理員帳號。': 'Sign in with a coach or administrator account.',
  '請先登入教練或超級管理員帳號。': 'Sign in with a coach or super administrator account.',
  '讀取學員失敗。': 'Unable to load students.',
  '讀取團練報名失敗。': 'Unable to load group training registrations.',
  '讀取教練資料失敗。': 'Unable to load coach details.',
  '讀取教練工作台失敗。': 'Unable to load the coach workspace.',
  '早安': 'Good morning',
  '午安': 'Good afternoon',
  '晚安': 'Good evening',
  '此頁面只供已認證教練使用': 'This page is for verified coaches',
  '教練信箱由管理員登記後，使用該信箱正常登入即可，不需要認證碼。若剛完成登記，請先確認信箱驗證，再重新登入。': 'Once an administrator registers your coach email, sign in with that email. No verification code is needed. If you were just registered, verify your email and sign in again.',
  '今天有': 'Today you have',
  '位名下學員，': 'assigned students and',
  '項團練報名待跟進。': 'group training registrations to follow up.',
  '名下學員': 'Assigned students',
  '待跟進': 'To follow up',
  '班級學員關聯': 'Class student assignments',
  '學員確認入帳後，依任課班級自動列入名單。補課學員請在「課程點名」選擇接收班級與補課日期查看；不需要手動綁定。': 'Students are listed automatically by class once payment is confirmed. To view makeup students, select the receiving class and makeup date under Class attendance. No manual linking is needed.',
  '尚未填寫目標': 'No goal provided',
  '目前任課班級尚無已確認入帳的學員。': 'Your assigned classes have no students with confirmed payments yet.',
  '查看名單': 'View list',
  '目前沒有團練報名資料。': 'No group training registrations yet.',
  '尚未選擇課次': 'No session selected',
  '讀取點名資料失敗。': 'Unable to load attendance details.',
  '儲存點名資料失敗。': 'Unable to save attendance.',
  '點名結果已儲存。': 'Attendance saved.',
  '更新停課狀態失敗。': 'Unable to update the cancellation status.',
  '停課狀態已更新。': 'Cancellation status updated.',
  '課程管理': 'Class management',
  '本頁對照學員自主簽到與教練現場點名，兩份證據獨立保存。補課學員會列出原班與請假日期；雙方確認後補課才完成。教練本人上班簽到仍在工作台辦理。': 'Compare student check-in with coach attendance; both records are stored separately. Makeup students show their original class and leave date. A makeup session is completed only after both confirmations. Use the workspace for your own coach check-in.',
  '更新簽到與補課名單': 'Refresh check-ins and makeup roster',
  '請先儲存點名，再更新名單。': 'Save attendance before refreshing the roster.',
  '正在讀取課程名單': 'Loading class roster',
  '目前沒有指派給你的招生中課程。': 'No enrolling classes are currently assigned to you.',
  '請由超級管理員在季度課程中指定教練。': 'Ask a super administrator to assign coaches in the season’s classes.',
  '點名課次': 'Attendance session',
  '｜未開始': '| Not started',
  '名單': 'Roster',
  '本堂已停課': 'This session is cancelled',
  '本堂正常開課': 'This session is running as scheduled',
  '停課是整堂課的狀態，不需要逐位學員點選。': 'Cancellation applies to the whole session. You do not need to mark each student separately.',
  '停課原因（選填）': 'Cancellation reason (optional)',
  '恢復開課': 'Restore session',
  '標記停課': 'Cancel session',
  '補課學生': 'Makeup students',
  '學員名單': 'Student roster',
  '補課學員｜來自': 'Makeup student | From',
  '｜原請假日期：': '| Original leave date: ',
  '原班請假保留｜': 'Leave in original class retained |',
  '補課已完成': 'Makeup completed',
  '尚未安排補課': 'No makeup session scheduled',
  '計費起點：': 'Billing starts: ',
  '未設定': 'Not set',
  '緊急聯絡：': 'Emergency contact: ',
  '未填姓名': 'Name not provided',
  '本次到課早於學員選擇的計費起點，儲存後會交由管理員處理補繳或免除。': 'This attendance is before the student’s selected billing start. After saving, an administrator will review the additional charge or waiver.',
  '這堂是學員申報的補繳課次；點名結果會自動完成到課核對。': 'The student declared an additional payment for this session. Saving attendance will complete the attendance review automatically.',
  '課次尚未開始': 'Session has not started',
  '點名備註（選填）': 'Attendance note (optional)',
  '本堂所有學員皆已完成點名。': 'Attendance is recorded for every student in this session.',
  '目前沒有符合此篩選的學員。': 'No students match this filter.',
  '課次開始後才可點名': 'Attendance can be recorded after the session starts',
  '目前沒有未儲存變更': 'No unsaved changes',
  '儲存本堂紀錄': 'Save session records',
  '讀取到課資料失敗。': 'Unable to load coach attendance.',
  '操作失敗，請重新整理後再試。': 'The action failed. Refresh and try again.',
  '操作已完成，畫面已從伺服器更新。': 'Action completed. The latest status is now displayed.',
  '操作已送出，但目前無法取得最新狀態，請重新整理確認。': 'The action was submitted, but the latest status could not be loaded. Refresh to confirm.',
  '今日課程': 'Today’s classes',
  '下一堂課': 'Next class',
  '堂課｜時間以伺服器資料為準': 'classes | Times follow the server record',
  '最近一堂：': 'Next session: ',
  '｜時間以伺服器資料為準': '| Times follow the server record',
  '目前沒有需要簽到或處理的授課課次。': 'No teaching sessions currently need a check-in or action.',
  '本人到課工作台': 'My teaching attendance',
  '近期課程': 'Upcoming classes',
  '今天先把到課記好': 'Record your attendance today',
  '可直接完成簽到': 'Check-in is available',
  '下一堂課時間以伺服器資料為準': 'The next class time follows the server record',
  '。本人簽到與學員出席核實是兩份獨立紀錄。': '. Your check-in and student attendance verification are separate records.',
  '上次更新': 'Last updated',
  '等待伺服器時間': 'Waiting for server time',
  '重新整理到課資料': 'Refresh attendance',
  '工作台檢視': 'Workspace view',
  '今日／近期': 'Today / Upcoming',
  '日曆': 'Calendar',
  '正在讀取今日課程': 'Loading today’s classes',
  '地點待確認': 'Location to be confirmed',
  '本人角色：': 'My role: ',
  '主教練': 'Lead coach',
  '助教': 'Assistant coach',
  '代班教練': 'Substitute coach',
  '管理員登記時間': 'Administrator record time',
  '伺服器時間': 'Server time',
  '未簽到，待管理員確認；不等同未到課。': 'Not checked in; awaiting administrator confirmation. This does not mean absent.',
  '查看詳情': 'View details',
  '本人到課簽到': 'Check in for teaching',
  '開啟詳情填寫補登原因': 'Open details to explain the manual entry',
  '已由管理員登記到課': 'Attendance recorded by an administrator',
  '已完成本人到課簽到': 'Teaching check-in complete',
  '可在詳情中申請請假': 'Request leave in session details',
  '目前沒有可執行的簽到任務': 'No check-in tasks available now',
  '代班待回覆': 'Substitution awaiting reply',
  '請假／代班': 'Leave / Substitution',
  '目前沒有下一堂授課安排': 'No upcoming teaching session scheduled',
  '若管理員新增課次，重新整理後會在這裡顯示。': 'If an administrator adds a session, refresh to see it here.',
  '待回覆代班': 'Substitution invitations',
  '部分邀請接受後仍需管理員最終確認，請先確認時間。': 'Some invitations still require administrator confirmation after you accept. Check the time first.',
  '接受後會成為實際授課教練，請先確認時間。': 'Accepting assigns you as the teaching coach. Check the time first.',
  '未設定時間': 'Time not set',
  '邀請人：': 'Invited by: ',
  '接受': 'Accept',
  '拒絕': 'Decline',
  '目前沒有待回覆的代班邀請。': 'No substitution invitations awaiting your reply.',
  '日曆是補充入口；今天與近期課程已先列在上方。': 'The calendar is an additional view. Today’s and upcoming classes are listed above.',
  '今天': 'Today',
  '上個月': 'Previous month',
  '日曆載入中': 'Loading calendar',
  '下個月': 'Next month',
  '正在讀取日曆': 'Loading calendar',
  '堂授課日程': 'teaching sessions',
  '授課安排': 'Teaching schedule',
  '記錄每堂課的實際到課情況，並由系統核對學員計費起點。': 'Record attendance for each session so the system can check the student’s billing start.',
  '正在確認教練身分': 'Checking coach access',
  '此頁面需要教練權限': 'Coach access required',
  '請使用管理員已登記的教練帳號；若剛完成登記，請重新登入。': 'Use a coach account registered by an administrator. If it was just registered, sign in again.',
  '前往我的帳戶': 'Go to my account',
  '好運跑班教練端，用於管理名下學員、團練報名、到課簽到與課程點名。': 'The Nurture Running Team coach workspace for students, group registrations, coach check-in, and class attendance.',
  '讀取課表失敗。': 'Unable to load training plans.',
  'CSV 已匯出': 'CSV exported',
  '匯出 CSV': 'Export CSV',
  '4 週年活動': 'Fourth anniversary event',
  '讀取報名資料失敗。': 'Unable to load registrations.',
  '更新報名狀態失敗。': 'Unable to update registration status.',
  '來源': 'Source',
  '想報名的團練': 'Requested group training',
  '緊急聯絡電話': 'Emergency phone',
  '同行人數': 'Party size',
  '跑步經驗': 'Running experience',
  '目標': 'Goal',
  '提交時間': 'Submitted at',
  '報名名單': 'Registration roster',
  '課程報名資料': 'Class registrations',
  '查看負責課程已確認入帳的完整報名資料。匯款由超級管理員或財務核對；尚未建立帳號的報名者也會列在這裡。': 'View complete registrations for your assigned classes after payment confirmation. Transfers are reviewed by a super administrator or finance. Registrants without accounts are also listed here.',
  '全部資料': 'All records',
  '搜尋姓名、電話、IG、目標或備註': 'Search name, phone, Instagram, goal, or notes',
  '全部來源': 'All sources',
  '讀取報名資料中...': 'Loading registrations…',
  '還沒有符合條件的資料': 'No matching records',
  '負責課程的報名經後台確認入帳後會出現在這裡。': 'Registrations for your assigned classes appear here after payment is confirmed.',
  '電話：': 'Phone: ',
  '匯款與核准狀態請由管理員後台處理。': 'Manage transfer and approval status in the administrator workspace.',
  '想報名': 'Interested in',
  '查看好運跑班活動與團練報名資料。': 'View Nurture Running Team event and group training registrations.',
  '讀取學員失敗，請稍後再試。': 'Unable to load students. Try again later.',
  '課程確認入帳後，這裡會顯示由你負責且已建立帳號的學員、完整報名資料與最近回饋。': 'After payment confirmation, students in your classes who have accounts appear here with their registration details and recent feedback.',
  '搜尋姓名、班級或目標': 'Search name, class, or goal',
  '目前無法讀取學員綁定資料。請確認帳號已啟用教練權限。資訊：': 'Unable to load student assignments. Check that coach access is enabled for your account. Details: ',
  '讀取學員中...': 'Loading students…',
  '學員尚未設定姓名': 'Student name not set',
  '尚未填寫': 'Not provided',
  '學員未填寫文字感受。': 'The student did not add written feedback.',
  '學員還沒有提交訓練回饋。可以提醒他完成訓練後到學員中心填寫 RPE、睡眠、疲勞與不適位置。': 'The student has not submitted training feedback yet. Remind them to report RPE, sleep, fatigue, and any discomfort in the student dashboard after training.',
  '查看回饋': 'View feedback',
  '尚未綁定真實學員': 'No students linked yet',
  '請先讓學員註冊帳號，再用上方欄位輸入對方信箱。綁定成功後，這裡會出現真實學員資料。': 'Ask the student to create an account, then enter their email above. Their details will appear here after the account is linked.',
  '查看好運跑班學員周數、目標、最近回饋與訓練風險。': 'View Nurture Running Team students’ training weeks, goals, recent feedback, and training concerns.',
  '找不到': 'Not found',
  '權限': 'Access',
  '工作台': 'Workspace',
  '教練端內部導航': 'Coach workspace navigation',
  '· 待啟用': '· Pending activation',
  '請補齊開始時間': 'Add the start time',
  '待安排': 'Awaiting scheduling',
  '已拒絕': 'Declined',
  '現在可簽到': 'Check in now',
  '準時簽到': 'Checked in on time',
  '遲到簽到': 'Checked in late',
  '未簽到，待確認': 'Not checked in; awaiting confirmation',
  '代班未簽到，待確認': 'Substitute not checked in; awaiting confirmation',
  '已請假，待完成代班': 'On leave; substitution pending',
  '已完成遲到簽到': 'Late check-in complete',
  '已完成準時簽到': 'On-time check-in complete',
  '確認教練到課': 'Confirm coach attendance',
  '尚未設定簽到時間': 'Check-in time not set',
  '簽到時間已結束': 'Check-in window closed',
  '簽到尚未開放': 'Check-in not open yet',
  '已核准': 'Approved',
  '關閉課程詳情': 'Close session details',
  '同日': 'Same day',
  '堂課': 'classes',
  '同日課程': 'Classes on this day',
  '未設定開始時間': 'Start time not set',
  '原定教練：': 'Scheduled coach: ',
  '實際授課：': 'Teaching coach: ',
  '管理員操作會留下「管理員登記／補登」紀錄；本人簽到與學員出席核實仍是兩份獨立紀錄。': 'Administrator actions create an administrator entry record. Coach check-in and student attendance verification remain separate records.',
  '等待管理員處理': 'Awaiting administrator action',
  '管理員已確認': 'Confirmed by administrator',
  '伺服器簽到時間': 'Server check-in time',
  '簽到開放時間：': 'Check-in window: ',
  '管理員補登原因': 'Reason for administrator entry',
  '請說明本堂補登原因（必填）': 'Explain why this session needs a manual entry (required)',
  '尚未簽到不等於未到課；目前標記為待確認。': 'No check-in does not mean absence. Attendance is currently awaiting confirmation.',
  '代班邀請待回覆': 'Substitution invitation awaiting reply',
  '接受代班': 'Accept substitution',
  '拒絕代班': 'Decline substitution',
  '重新邀請代班教練': 'Invite a substitute again',
  '請假與代班安排': 'Leave and substitution',
  '可選擇由管理員安排': 'You can ask an administrator to arrange this',
  '請假原因': 'Reason for leave',
  '請填寫請假原因（必填）': 'Enter the reason for leave (required)',
  '原因會保留在本堂課審計紀錄中。': 'The reason is kept in this session’s audit history.',
  '邀請代班（選填）': 'Invite a substitute (optional)',
  '不指定，由管理員安排': 'No preference — administrator will arrange',
  '重新送出安排': 'Resubmit arrangement',
  '送出請假申請': 'Submit leave request',
  '查看完整報名資料': 'View complete registration',
  '未填寫': 'Not provided',
}
