// Loading, not-found and error-boundary interface copy.
export const systemEnglishCopy: Record<string, string> = {
  '圖片尺寸或裁切比例無效。': 'The image dimensions or crop ratio are invalid.',
  '請先登入後查看通知。': 'Sign in to view your notifications.',
  '讀取通知失敗，請稍後重試。': 'Unable to load notifications. Try again later.',
  '收款資料服務尚未設定。': 'Payment details are not configured.',
  '收款資料暫時無法讀取，請稍後重試。': 'Payment details are temporarily unavailable. Try again later.',
  '無法確認季度狀態，未執行修改。': 'The season status could not be verified. No changes were made.',
  '此季度已封存，歷史資料僅供查閱，不能修改或同步。': 'This season is archived. Historical records are read-only and cannot be edited or synchronized.',
  '讀取報名狀態失敗，請稍後再試。': 'Unable to load your registration status. Try again later.',
  '讀取最近回饋失敗，請稍後再試。': 'Unable to load recent feedback. Try again later.',
  '讀取賽事失敗。': 'Unable to load races.',
  '刪除賽事失敗。': 'Unable to delete the race.',
  '讀取帳號角色失敗。': 'Unable to load your account role.',
  '登入狀態已失效。': 'Your session has expired. Sign in again.',
  '網站內容暫時無法更新。': 'Website content could not be updated right now.',
  '網站內容暫時無法更新，請稍後重試。': 'Website content could not be updated right now. Try again later.',
  '通知清單格式不正確。': 'The notification list format is invalid. Refresh and try again.',
  '建立教練公開資料失敗。': 'Unable to create the public coach profile.',
  '讀取教練公開資料失敗。': 'Unable to load the public coach profile.',
  '教練照片由超級管理員統一維護，教練帳號不可自行上傳。': 'Coach photos are managed by the administrator. Coach accounts cannot upload them directly.',
  '讀取正式報名資料失敗，請稍後再試。': 'Unable to load registration records. Try again later.',
  '好運教練': 'Nurture Running coach',
  '課表週參數格式錯誤。': 'The training week parameter is invalid.',
  '課表周参數格式錯誤。': 'The training week parameter is invalid.',
  '好運跑班官方匯款帳戶': 'Nurture Running official bank account',
  '商品資料暫時無法載入。': 'Product information is temporarily unavailable.',
  '商品資料服務尚未設定。': 'The product information service is not configured.',
  '課程或 Google 表單回覆編號無效。': 'The class or Google Forms response ID is invalid.',
  '表單串接憑證無效。': 'The form integration credentials are invalid.',
  'Google 表單必須收集電子信箱，才能建立匯款狀態。': 'Google Forms must collect an email address to create a payment record.',
  '更新匯款資料失敗。': 'Unable to update the transfer details.',
  '尚未申報金額': 'Amount not reported',
  '建立報名付款記錄失敗。': 'Unable to create the registration payment record.',
  '同步資料超過大小限制。': 'The synchronization data exceeds the size limit.',
  '季度或 Google 表格編號無效。': 'The season or Google Sheets ID is invalid.',
  '這份 Google 表格尚未連結到季度。': 'This Google Sheet is not linked to a season.',
  '季度連結資料不一致。': 'The season link does not match.',
  '此季度已封存，已停止同步。': 'This season is archived. Synchronization has stopped.',
  '表格同步憑證無效。': 'The spreadsheet synchronization credentials are invalid.',
  '同步資料缺少正式班級分表。': 'The synchronization data is missing a class sheet.',
  '表格中沒有可同步的學員資料，或資料筆數異常。': 'The spreadsheet has no student records to synchronize, or its record count is invalid.',
  '讀取季度資料失敗。': 'Unable to load season data.',
  '表格中的班級沒有對應季度設定。': 'A class in the spreadsheet has no matching season settings.',
  'Google 表格偵測到同班級、同姓名與同信箱的重複報名，請人工處理。': 'Google Sheets found duplicate registrations with the same class, name and email. Manual review is required.',
  '已由財務確認入帳；Google 表格僅同步報名資料。': 'Finance has confirmed payment. Google Sheets only synchronizes registration details.',
  '由 Google 表格同步；付款仍依銀行對帳結果判定。': 'Synchronized from Google Sheets. Payment confirmation still depends on bank reconciliation.',
  '同步學員資料失敗。': 'Unable to synchronize student records.',
  '學員資料已同步，但同步狀態更新失敗。': 'Student records were synchronized, but the synchronization status could not be updated.',
  '出現了一點問題': 'Something went wrong',
  '我們遇到了一個意外錯誤。請稍後重試，或者返回首頁。': 'An unexpected error occurred. Try again or return to the homepage.',
  '重新嘗試': 'Try again',
  '隱藏詳細資訊': 'Hide details',
  '顯示詳細資訊': 'Show details',
  '錯誤 ID:': 'Error ID:',
  '需要幫助？請': 'Need help? ',
  '聯絡客服': 'Contact support',
  '頁面未找到': 'Page not found',
  '抱歉，您訪問的頁面不存在或已被移除。讓我們幫您重新回到正軌。': 'This page does not exist or has been removed. Let’s get you back on track.',
  '返回上頁': 'Go back',
  '💪 繼續加油！讓我們一起跑向成功！': '💪 Keep going. Let’s run toward our goals together!',
  '正在載入網站內容…': 'Loading website content…',
  '網站內容暫時無法載入': 'Website content is temporarily unavailable',
  '請確認網路連線後重試，我們不會以舊版資料取代目前內容。': 'Check your connection and try again. Outdated content will not replace the current version.',
  '重新載入': 'Reload',
}
