// Finance interface copy; bank records and user-entered notes are not rewritten.
export const financeEnglishCopy: Record<string, string> = {
  '選擇銀行明細檔案': 'Choose a bank statement file',
  '選擇檔案': 'Choose file',
  '尚未選擇檔案': 'No file selected',
  '12 至 128 個字元，至少包含一個英文字母與一個數字。': 'Use 12–128 characters, including at least one English letter and one number.',
  '讀取財務權限狀態失敗。': 'Unable to load finance access status.',
  '只有指定的財務主管可以變更財務密碼。': 'Only the designated finance manager can change the finance password.',
  '目前的財務密碼不正確。': 'The current finance password is incorrect.',
  '財務密碼已更新，其他已解鎖的工作階段已失效。': 'Finance password updated. Other unlocked sessions have been revoked.',
  '只有指定的財務主管可以設定財務密碼。': 'Only the designated finance manager can set the finance password.',
  '只有指定的財務主管可以建立財務密碼。': 'Only the designated finance manager can create the finance password.',
  '財務密碼已建立，請直接解鎖。': 'A finance password already exists. Use it to unlock access.',
  '建立財務密碼失敗。': 'Unable to create the finance password.',
  '財務密碼已建立，對帳區已解鎖 30 分鐘。': 'Finance password created. Reconciliation is unlocked for 30 minutes.',
  '財務權限操作無效。': 'Invalid finance access action.',
  '財務密碼尚未建立。': 'No finance password has been created.',
  '財務密碼輸入錯誤次數過多，請稍後再試。': 'Too many incorrect finance password attempts. Try again later.',
  '財務密碼連續輸入錯誤，已鎖定 15 分鐘。': 'Repeated incorrect finance passwords. Access is locked for 15 minutes.',
  '財務對帳區已解鎖 30 分鐘。': 'Finance reconciliation is unlocked for 30 minutes.',
  '請選擇銀行下載的 XLSX 或 CSV 檔案。': 'Select an XLSX or CSV file downloaded from your bank.',
  '此批次不屬於選擇的季度，或不在最近 20 個批次中。': 'This batch is not in the selected season or among its 20 most recent batches.',
  '讀取對帳資料失敗。': 'Unable to load reconciliation data.',
  '請先選擇對帳季度。': 'Select a reconciliation season first.',
  '這份銀行檔案已匯入過，請直接查看原有批次。': 'This bank file was already imported. Open the existing batch.',
  '未指定收款帳戶': 'No receiving account specified',
  '選擇的收款帳戶不存在。': 'The selected receiving account does not exist.',
  '建立對帳批次失敗。': 'Unable to create a reconciliation batch.',
  '沒有找到後五碼相同且已回報、待人工核對的記錄。': 'No submitted records awaiting review have matching last five account digits.',
  '這是支出交易，不列入收款對帳。': 'This is a debit transaction and is excluded from incoming payment reconciliation.',
  '多人使用相同後五碼，需由財務確認正確訂單。': 'Several people share these last five digits. Finance must identify the correct order.',
  '後五碼與金額唯一相符；記錄先前已確認入帳，可補登銀行依據。': 'The last five digits and amount match uniquely. Payment was already confirmed; you can add the bank transaction as supporting evidence.',
  '後五碼與金額唯一相符，可以確認入帳。': 'The last five digits and amount match uniquely. Payment can be confirmed.',
  '找到後五碼相同的訂單，但金額不同，需人工核對。': 'An order has matching last five digits but a different amount. Manual review is required.',
  '銀行對帳發現金額不符或後五碼重複，請由財務人工處理。': 'Reconciliation found an amount mismatch or duplicate last five digits. Finance must review it manually.',
  '部分異常訂單未能更新狀態，請依對帳批次人工檢查。': 'Some orders with issues could not be updated. Review them manually in the reconciliation batch.',
  '匯入銀行檔案失敗。': 'Unable to import the bank file.',
  '找不到對帳批次。': 'Reconciliation batch not found.',
  '此批次沒有季度資料，請由管理員檢查。': 'This batch has no season information. Ask an administrator to check it.',
  '缺少交易或訂單資料。': 'Transaction or order information is missing.',
  '已更新這筆交易的對應訂單。': 'The matching order for this transaction has been updated.',
  '缺少交易資料。': 'Transaction information is missing.',
  '已將這筆交易標記為不需對帳。': 'This transaction has been excluded from reconciliation.',
  '這筆銀行款項已完成對帳。': 'This bank payment has been reconciled.',
  '缺少對帳批次。': 'Reconciliation batch is missing.',
  '季度已封存或無法確認季度狀態，未執行修改。': 'The season is archived or its status could not be verified. No changes were made.',
  '對帳操作無效。': 'Invalid reconciliation action.',
  '對應班級已達名額上限，這筆款項需由管理員人工處理。': 'The class is full. An administrator must review this payment manually.',
  '銀行對帳': 'Bank reconciliation',
  '財務密碼更新失敗。': 'Unable to update the finance password.',
  '財務權限驗證失敗。': 'Finance access verification failed.',
  '銀行檔案預覽失敗。': 'Unable to preview the bank file.',
  '對帳操作失敗。': 'Reconciliation action failed.',
  '重新嘗試': 'Try again',
  '目前帳號沒有銀行對帳查閱權限。請從「我的帳戶」登出，再使用獲授權的帳號登入。': 'This account cannot view bank reconciliation. Sign out from My account, then sign in with an authorized account.',
  '唯一相符': 'Unique match',
  '多筆待選': 'Multiple candidates',
  '金額不同': 'Amount mismatch',
  '找不到訂單': 'No order found',
  '已確認待補登': 'Already confirmed; record pending',
  '人工已選': 'Manually selected',
  '重複交易': 'Duplicate transaction',
  '不需對帳': 'Excluded from reconciliation',
  '對帳完成': 'Reconciled',
  '入帳金額': 'Amount received',
  '匯款帳號／後五碼': 'Sender account / Last five digits',
  '交易日期': 'Transaction date',
  '交易時間': 'Transaction time',
  '匯款人': 'Sender',
  '交易序號': 'Transaction reference',
  '摘要': 'Description',
  '收支方向': 'Credit / Debit',
  '未提供': 'Not provided',
  '讀取財務權限失敗。': 'Unable to load finance access.',
  '兩次輸入的財務密碼不一致。': 'The finance passwords do not match.',
  '財務權限解鎖失敗。': 'Unable to unlock finance access.',
  '財務對帳區已解鎖。': 'Finance reconciliation unlocked.',
  '兩次輸入的新財務密碼不一致。': 'The new finance passwords do not match.',
  '財務密碼已更新。': 'Finance password updated.',
  '請選擇尚未封存的對帳季度。': 'Select a reconciliation season that is not archived.',
  '請先指定入帳金額與匯款帳號／後五碼欄位。': 'Map the amount received and sender account / last five digits columns first.',
  '銀行交易已匯入。': 'Bank transactions imported.',
  '銀行檔案匯入失敗。': 'Unable to import the bank file.',
  '對帳操作已完成。': 'Reconciliation action completed.',
  '無法讀取財務權限': 'Unable to load finance access',
  '建立財務專用密碼': 'Create a finance password',
  '解鎖銀行對帳': 'Unlock bank reconciliation',
  '銀行檔案、匹配結果與確認操作另有一層財務權限；解鎖有效 30 分鐘。': 'Bank files, matching results, and confirmation actions require separate finance access. Unlocking grants access for 30 minutes.',
  '財務密碼尚未建立，請由指定的財務主管帳號先完成設定。': 'No finance password has been created. The designated finance manager must set it up first.',
  '財務密碼': 'Finance password',
  '設定至少 12 個字元': 'Use at least 12 characters',
  '輸入財務密碼': 'Enter finance password',
  '再次輸入': 'Confirm password',
  '再次輸入財務密碼': 'Enter finance password again',
  '建立並解鎖': 'Create and unlock',
  '解鎖對帳區': 'Unlock reconciliation',
  '財務權限已解鎖': 'Finance access unlocked',
  '後五碼與整數金額皆唯一相符時才會建議自動確認。': 'Bulk confirmation is suggested only when the last five account digits and whole-dollar amount both match uniquely.',
  '立即鎖定': 'Lock now',
  '對帳季度': 'Reconciliation season',
  '讀取季度失敗。': 'Unable to load seasons.',
  '正在讀取季度…': 'Loading seasons…',
  '（已封存）': '(Archived)',
  '此季度已封存，僅供查閱，不能匯入或修改對帳。': 'This season is archived and read-only. Transactions cannot be imported or reconciliation changed.',
  '上傳前請確認季度。銀行明細只會比對此季度的課程報名；唯一相符也需確認入帳後才列為已繳費。': 'Check the season before uploading. Bank transactions are matched only against registrations in that season. Even unique matches count as paid only after payment confirmation.',
  '查看新報名、請學生補充資料或回報匯款': 'Review new registrations or ask students for information or transfer details',
  '財務密碼設定': 'Finance password settings',
  '目前密碼': 'Current password',
  '新密碼': 'New password',
  '再次輸入新密碼': 'Confirm new password',
  '更新後，其他已解鎖的財務工作階段會立即失效。': 'Updating the password immediately revokes other unlocked finance sessions.',
  '更新財務密碼': 'Update finance password',
  '匯入銀行明細': 'Import bank transactions',
  '支援 XLSX、CSV，單檔最多 10 MB。': 'Supports XLSX and CSV files, up to 10 MB each.',
  '原始銀行檔案只在本次匯入時解析，不會保留在網站；系統僅保存對帳所需欄位、後五碼與檔案指紋。': 'The original bank file is processed for this import and is not retained on the website. Only the fields needed for reconciliation, the last five account digits, and a file fingerprint are saved.',
  '正在辨識銀行欄位...': 'Detecting bank columns…',
  '工作表': 'Worksheet',
  '標題列': 'Header row',
  '重讀': 'Reload',
  '入帳收款帳戶': 'Receiving account',
  '未指定': 'Not specified',
  '不使用': 'Do not use',
  '匯入並開始比對（約': 'Import and match (about',
  '列）': 'rows)',
  '對帳批次': 'Reconciliation batches',
  '保留匯入、人工選擇與確認紀錄，方便日後追查。': 'Import, manual selection, and confirmation records are kept for later review.',
  '尚未匯入銀行明細': 'No bank transactions imported yet',
  '完成第一份檔案匯入後，批次摘要會顯示在這裡。': 'Batch summaries appear here after your first file import.',
  '目前批次': 'Current batch',
  '讀取批次失敗。': 'Unable to load the batch.',
  '匯入交易': 'Imported transactions',
  '可直接確認': 'Ready to confirm',
  '需人工處理': 'Needs manual review',
  '第一步：確認全部唯一相符款項': 'Step 1: Review all unique matches',
  '請再次確認批次入帳': 'Confirm batch payments',
  '系統會將本批次所有唯一相符款項標記為已入帳，並依現有規則更新訂單與課表權限。': 'All unique matches in this batch will be marked as paid. Orders and training plan access will be updated under the existing rules.',
  '再檢查': 'Review again',
  '第二步：確認入帳': 'Step 2: Confirm payments',
  '交易比對結果': 'Transaction matching results',
  '僅供查閱，無法變更比對結果或確認入帳。': 'Read-only. Matching results cannot be changed and payments cannot be confirmed.',
  '人工選擇金額不同的訂單後，仍需再次按下確認才會核准。': 'After manually selecting an order with a different amount, you must confirm it again to approve the payment.',
  '銀行交易': 'Bank transaction',
  '金額': 'Amount',
  '比對狀態': 'Match status',
  '對應訂單': 'Matched order',
  '操作': 'Actions',
  '目前篩選沒有交易。': 'No transactions match this filter.',
  '選擇對應訂單': 'Select a matching order',
  '沒有後五碼相同的訂單': 'No orders share these last five digits',
  '僅供查閱': 'Read-only',
  '確認入帳': 'Confirm payment',
  '財務人工判定不需列入本次收款對帳。': 'Finance manually excluded this transaction from the current reconciliation.',
  '略過': 'Skip',
  '請再次確認入帳': 'Confirm this payment',
  '學員／買家：': 'Student / Buyer: ',
  '課程／商品訂單：': 'Class / Product order: ',
  '尚未選擇對應訂單': 'No matching order selected',
  '回報金額：': 'Reported amount: ',
  '· 銀行實際入帳：': '· Amount received by bank: ',
  '轉出後五碼：': 'Sender’s last five digits: ',
  '· 入帳時間：': '· Received at: ',
  '請確認金額、後五碼與訂單資料一致。': 'Check that the amount, last five digits, and order details match.',
  '收入': 'Credit',
  '支出': 'Debit',
  '未提供戶名': 'Account name not provided',
  '後五碼': 'Last five digits',
  '登入服務尚未設定。': 'The sign-in service is not configured.',
  '收款資料讀取失敗。': 'Unable to load payment details.',
  '收款資料操作失敗。': 'Unable to update payment details.',
  '匯款二維碼': 'Bank transfer QR code',
  '只有超級管理員可修改對外匯款資料。': 'Only super administrators can change customer transfer details.',
  '收款資料讀取失敗，請稍後重試。': 'Unable to load transfer details. Try again later.',
  '收款資料格式不正確。': 'Invalid transfer details format.',
  '請先核對帳號及二維碼後再發布。': 'Check the account and QR code before publishing.',
  '請重新讀取收款資料。': 'Reload the transfer details.',
  '另一位管理員已更新資料，請重新讀取後再修改。': 'Another administrator updated these details. Reload before editing.',
  '收款資料儲存失敗，請稍後重試。': 'Unable to save transfer details. Try again later.',
  '已發布至課程報名與商城結帳頁。': 'Published to class registration and shop checkout.',
  '收款資料已儲存，但重新讀取失敗；請重新讀取確認，不必重複發布。': 'Transfer details were saved, but reloading failed. Reload to confirm; do not publish again.',
  '收款資料服務暫時無法使用。': 'The transfer details service is temporarily unavailable.',
  '請填寫銀行名稱、三位銀行代碼與 6 至 24 位數字帳號。': 'Enter the bank name, a 3-digit bank code and an account number with 6–24 digits.',
  '二維碼圖片請使用 HTTPS 網址，或留空不顯示。': 'Use an HTTPS image URL for the QR code, or leave it blank to hide it.',
  '二維碼網址不能包含登入資訊。': 'The QR code URL cannot contain sign-in credentials.',
  '銀行資料已變更，請清除舊二維碼並提供新圖片或留空。': 'The bank details have changed. Remove the old QR code and provide a new image, or leave it blank.',
  '對外匯款資料設定': 'Customer transfer details settings',
  '對外匯款資料': 'Customer transfer details',
  '發布後，課程報名與商城結帳將使用這組資料。下方帳戶池只供內部對帳。更換銀行或帳號會清除原二維碼，請貼上新圖片網址或留空。': 'Published details are used for class registrations and shop checkout. The account pool below is for internal reconciliation only. Changing the bank or account clears the old QR code; enter a new image URL or leave it blank.',
  '銀行代碼（三位數）': 'Bank code (3 digits)',
  '二維碼圖片 HTTPS 網址（可留空）': 'QR code image HTTPS URL (optional)',
  '發布預覽': 'Publication preview',
  '・尚未儲存': '· Unsaved',
  '我已核對銀行、帳號及二維碼，確認可供學員及買家匯款。': 'I have checked the bank, account, and QR code and confirm that students and buyers can use them for transfers.',
  '處理中…': 'Processing…',
  '儲存並發布匯款資料': 'Save and publish transfer details',
  '重新讀取會捨棄未儲存的收款資料，確定繼續？': 'Reloading will discard unsaved payment details. Continue?',
  '重新讀取': 'Reload',
  '已確認繳費': 'Payment confirmed',
  '待繳費／未回報': 'Awaiting payment / Not reported',
  '已回報待核對': 'Reported / Awaiting review',
  '異常／重複記錄': 'Issues / Duplicate records',
  '本季報名繳費一覽': 'Season registration payment overview',
  '包含未出現在銀行檔案中的報名。未回報或尚未匹配不代表一定未付款，請核對後再確認；異常與重複記錄另列，不算作已繳費。': 'Includes registrations not found in the bank file. Missing reports or matches do not necessarily mean no payment was made. Verify before confirming. Issues and duplicate records are listed separately and are not counted as paid.',
  '搜尋報名姓名、班級或後五碼': 'Search registrant name, class, or last five digits',
  '搜尋姓名、班級或後五碼': 'Search name, class, or last five digits',
  '繳費狀態': 'Payment status',
  '未定價': 'Price not set',
  '未回報': 'Not reported',
  '此篩選沒有報名記錄。': 'No registrations match this filter.',
}
