export const registrationEnglishCopy: Record<string, string> = {
  '課程報價簽名服務尚未設定。': 'Class pricing is temporarily unavailable.',
  '本班尚未完成收費課次設定，請聯絡管理員。': 'Billable sessions have not been configured for this class. Contact the administrator.',
  '請選擇正確的本期計費起始課次。': 'Select a valid first billable session for this season.',
  '課程已開始，請選擇本期計費起始課次。': 'This class has started. Select your first billable session for this season.',
  '補繳只能選擇最近一堂已結束的課次。': 'A catch-up payment can only cover the most recently completed session.',
  '過去的課次必須申明已到課補繳。': 'For a past session, confirm that you attended and need to pay for it.',
  '匯款資料需補充，請查看報名通知。': 'Your transfer details need more information. Check your registration notifications.',
  '報名課程': 'Registered class',
  '舊生': 'Returning student',
  '新生': 'New student',
  '插班報名': 'Late-entry registration',
  '最近一堂到課申報': 'Reported attendance at the latest session',
  '未通過核對': 'Not verified',
  '手機電話': 'Mobile phone',
  '緊急聯絡人姓名': 'Emergency contact name',
  '近期挑戰': 'Recent races and results',
  '近期目標': 'Upcoming goals',
  '跑步近況': 'Current running routine',
  '課程費用計算失敗。': 'Unable to calculate the class fee.',
  '請先登入後再提交匯款資料。': 'Sign in before submitting transfer details.',
  '讀取報名狀態失敗。': 'Unable to load registration status.',
  '第': 'No.',
  '堂': 'sessions',
  '匯款資料提交失敗。': 'Unable to submit transfer details.',
  '匯款資料已送出，目前狀態為「已回報，待人工核對」；銀行流水與申報資料相符並經財務確認後，才會更新為「已確認入帳」。': 'Transfer details submitted. Your status is “Reported, awaiting review”. It will change to “Payment confirmed” only after finance matches your report to the bank records and confirms receipt.',
  '讀取中': 'Loading',
  '本班目前已額滿': 'This class is currently full',
  '如有釋出名額，這裡會自動恢復報名。': 'Registration will reopen here automatically if places become available.',
  '正在準備報名表': 'Preparing the registration form',
  '已收到你的報名資料': 'Your registration details have been received',
  '目前狀態可在右側查看，管理員核對款項後會更新結果。': 'Check your current status in the status panel. It will update after an administrator verifies payment.',
  '報名相關疑問': 'Registration questions',
  '報名相關疑問，可以直接私訊以下任一聯絡窗口。': 'For registration questions, message either of the contacts below.',
  '好運官方 IG': 'Official Nurture Running Instagram',
  '陳盛琦 Facebook': 'Chen Sheng-qi on Facebook',
  '報名與匯款資料已送出，待財務比對銀行流水後更新結果。': 'Registration and transfer details submitted. Results will update after finance checks the bank records.',
  '正在同步狀態': 'Updating status',
  '尚未收到': 'No registration received for',
  '的報名資料，完成左側網站表單後會顯示在這裡。': '. Complete the registration form and it will appear here.',
  '重新檢查狀態': 'Check status again',
  '應付金額': 'Amount payable',
  '依表單說明': 'As shown in the form',
  '本期計費起始': 'Billing start this season',
  '已確認到課': 'Attendance confirmed',
  '待管理員核對': 'Awaiting administrator review',
  '核對說明': 'Review notes',
  '請補充報名資料': 'Provide additional registration details',
  '查看財務說明並補交資料，會沿用這筆報名。': 'Read the finance instructions and add details to this existing registration.',
  '查看說明並補充資料': 'Read instructions and provide details',
  '完成匯款後回報': 'Report your transfer after payment',
  '依下方收款資料完成匯款，再填寫匯款帳號後五碼。': 'Transfer payment using the instructions below, then enter the last five digits of the sender’s account.',
  '例如 12345': 'For example, 12345',
  '備註（選填）': 'Notes (optional)',
  '可填寫匯款時間；請勿輸入完整帳號或信用卡資料': 'You may enter the transfer time. Do not enter a full account number or credit card details.',
  '送出匯款資料': 'Submit transfer details',
  '課程確認': 'Confirm class',
  '規範同意': 'Agree to rules',
  '匯款與發票': 'Transfer and invoice',
  '本期完整報名': 'Full-season registration',
  '你已申報最近一堂有到課並補繳費用；教練完成該堂點名後，系統會自動核對到課紀錄。': 'You have reported attending the latest session and paying for it. The system will verify attendance after the coach completes roll call.',
  '推薦資格已核對，插班費率為每堂 NT$450。': 'Referral eligibility verified. The late-entry rate is NT$450 per session.',
  '目前無法核對推薦資格，插班費率依每堂 NT$500 計算。': 'Referral eligibility could not be verified. The late-entry rate is NT$500 per session.',
  '此金額保留至': 'This quote is valid until',
  '。選定的起始課次是本期計費承諾；之後若該堂請假，不會自動順延計費日期。': '. Your selected first session determines billing for this season. Taking leave for that session does not automatically move the billing start date.',
  '選填': 'Optional',
  '請完成兩項課程規範同意後再繼續。': 'Agree to both class rules before continuing.',
  '請選擇本期計費起始課次。': 'Select your first billable session this season.',
  '請填寫學員姓名與緊急聯絡人資料。': 'Enter the student name and emergency contact details.',
  '請完成所有新生必填資料。沒有成績或傷病時可填寫「無」。': 'Complete all required new-student details. Enter “None” if you have no race results or injuries to report.',
  '請確認系統計算的費用，並填寫匯款帳號後五碼。': 'Confirm the calculated fee and enter the last five digits of the sender’s account.',
  '請完成電子發票資料並確認參與本期訓練營。': 'Complete the invoice details and confirm participation in this season’s camp.',
  '登入狀態已失效，請重新登入後再繼續。': 'Your session has expired. Sign in again to continue.',
  '登入狀態已失效，請重新登入後再送出。': 'Your session has expired. Sign in again before submitting.',
  '報名資料送出失敗。': 'Unable to submit registration details.',
  '網站報名表': 'Online registration form',
  '本次報名課程': 'Your selected class',
  '日期': 'Dates',
  '地點': 'Location',
  '上課日': 'Class day',
  '訓練重點': 'Training focus',
  '負責班級': 'Assigned class',
  '學員權益及課程規範': 'Student rights and class rules',
  '請務必仔細閱讀，以免影響權益。': 'Please read carefully to understand your rights.',
  '我了解教練若因家庭、比賽或活動因素請假，將提前告知，並視實際情況安排代課或完成課程執行。': 'I understand that if a coach takes leave for family reasons, races, or events, advance notice will be given and a substitute or other session arrangements will be made as appropriate.',
  '本人已詳細閱讀上述說明，同意課程規範及學員權益，並以網路同意確認代替紙本。': 'I have read the information above, agree to the class rules and student rights, and give my agreement online in place of a paper signature.',
  '送出即表示同意': 'By submitting, you agree to the',
  '與': 'and',
  '條款': 'Terms',
  '· 退費': '· Refunds',
  '· 隱私': '· Privacy',
  '· 發票': '· Invoices',
  '學員身份': 'Student category',
  '已辨識為好運舊生': 'Recognized as a returning student',
  '本次將以新生身份報名': 'You are registering as a new student',
  '系統依登入信箱': 'Your signed-in email is used for verification:',
  '自動核對，身份與對應價格無需手動選擇。': '. Your student category and price are determined automatically.',
  '本期計費起始課次': 'First billable session this season',
  '課程已開始，請依你實際要開始上課的課次選擇。當日課程會計入堂數。': 'This class has started. Select the session you will begin attending. That session is included in the fee.',
  '本班尚未開始或今天是第一堂，系統會自動從第一堂課開始計費。': 'This class has not started, or today is its first session. Billing begins automatically from the first session.',
  '堂 ·': '·',
  '從本堂起計': 'Sessions from this date:',
  '我已參加最近一堂，現在補繳': 'I attended the latest session and am paying for it now',
  '；教練點名後由系統自動核對。': '; attendance is verified automatically after the coach completes roll call.',
  '第 1 堂 ·': 'Session 1 ·',
  '採本期完整課程價格。': 'The full-season price applies.',
  '正在計算本次費用': 'Calculating your fee',
  '資料僅供好運跑班進行課程聯絡、匯款核對與安全照護使用。': 'Nurture Running Team uses these details only for class communication, transfer verification, and safety.',
  '學員姓名': 'Student name',
  '請留意陌生訊息，教練會將您加入 LINE 群組。': 'Check messages from new contacts. Your coach will add you to the LINE group.',
  '緊急聯絡人聯絡電話': 'Emergency contact phone',
  '推薦人信箱': 'Referrer’s email',
  '請填推薦人的好運跑班報名信箱；若無可留白': 'Enter your referrer’s Nurture registration email, or leave blank.',
  '插班新生的推薦資格會以舊生名單或已確認入帳的報名記錄自動核對。': 'Referral eligibility for late-entry new students is checked against returning-student records or registrations with confirmed payment.',
  '半年內 5K、10K、半馬或全馬成績；沒有可填「無」': '5K, 10K, half marathon, or marathon results from the last six months. Enter “None” if not applicable.',
  '目標賽事、距離或完賽時間': 'Target race, distance, or finish time',
  '過去到現在是否有病史或運動傷害？': 'Do you have any past or current medical conditions or sports injuries?',
  '沒有請填「無」': 'Enter “None” if not applicable',
  '簡單分享現在的跑步感覺': 'Briefly describe how running feels at the moment',
  '匯款資訊': 'Bank transfer instructions',
  '網站只記錄匯款帳號後五碼，不會要求信用卡號、網銀密碼或完整付款帳號。': 'The website records only the last five digits of the sender’s account. It does not ask for credit card numbers, online banking passwords, or full payment account numbers.',
  '系統核算匯款總金額': 'Calculated transfer total',
  '正在核對身份、課次與價格': 'Checking student category, sessions, and price',
  '匯款後五碼': 'Last five transfer account digits',
  '匯款備註請保持空白，並保留轉帳截圖以利後續查詢。': 'Leave the transfer reference field blank and keep a screenshot of your transfer for future enquiries.',
  '電子發票': 'Electronic invoice',
  '電子發票開立方式': 'Invoice delivery method',
  '寄至本次的電子信箱或 Gmail 信箱': 'Send to my registration email or Gmail address',
  '載具條碼或電子信箱': 'Carrier barcode or email address',
  '例如 /HI77HI 或 runner@example.com': 'For example, /HI77HI or runner@example.com',
  '手機載具由「/」開頭，後接 6 碼英文大寫與數字組合。': 'The mobile carrier code starts with “/”, followed by six uppercase letters or digits.',
  '想跟小編說什麼呢？請勿填寫完整匯款帳號或信用卡資料': 'Anything you would like to tell us? Do not include a full bank account number or credit card details.',
  '統一編號與發票抬頭': 'Business tax ID and invoice title',
  '若無可留白': 'Leave blank if not applicable',
  '上一步': 'Back',
  '下一步': 'Next',
  '送出報名與匯款資料': 'Submit registration and transfer details',
  '資料經加密連線送出，僅供報名管理使用': 'Details are sent over an encrypted connection and used only to manage registration.',
  '好運跑班課程報名。': 'Nurture Running Team class registration.',
  '無法自動複製，請長按下方文字選取並複製。': 'Automatic copying is unavailable. Press and hold the text below to select and copy it.',
  '匯款資料': 'Transfer details',
  '原匯款資料卡二維碼': 'Payment information card QR code',
  '銀行機構': 'Bank',
  '已複製': 'Copied',
  '複製': 'Copy',
  '匯款或網銀轉帳時，': 'When making a bank transfer, ',
  '請勿填寫備註欄內容': 'leave the reference field blank',
  '，以免影響款項核對。': ' to help us reconcile the payment.',
  '若遇豪大雨、打雷等足以影響教課安全之氣候狀況，教練團隊將於當日課程前一小時於 LINE 群組決定是否暫停課程乙次，補課訊息另於群組通知。': 'If heavy rain, thunder, or other weather threatens safety, the coaching team will announce in the LINE group one hour before class whether the session is cancelled. Make-up arrangements will be announced separately in the group.',
  '若遇到一般雨勢、或場地因素導致不適合當次訓練，則依教練當日公布更改地點或暫停課程，並於當日課程前於 LINE 群組公告，若暫停需補課，則訊息另於群組通知。': 'If rain or venue conditions make the planned training unsuitable, the coach may change the location or cancel the session, announcing the decision in the LINE group before class. Any make-up arrangements will be announced separately.',
  '若遇到颱風、地震等不可抗拒因素，課程將以當日政府宣布停班停課之公告，若暫停乙次之補課訊息另於群組通知。': 'For typhoons, earthquakes, or other force majeure events, classes will follow government work and school closure announcements. Make-up information for a cancelled session will be posted separately in the group.',
  '因運動安全考量，請學員務必穿著適合運動之裝備、建議善用 GPS 手錶，並於課程中遵守教練、助教指導。': 'For safety, wear appropriate sports gear, consider using a GPS watch, and follow coaches’ and assistants’ instructions during class.',
  '取消與退費政策：報名成功後，第二堂課前若決定取消報名，則退剩餘堂數費用，第三堂課後恕不退費；申請退費者請提供銀行帳戶，退回金額將扣除行政手續費。': 'Cancellation and refund policy: after registration is confirmed, cancellation before the second session receives a refund for the remaining sessions. No refunds are available after the third session. Provide a bank account when applying; administrative fees will be deducted from the refund.',
  '學員若因故無法參與當週課程，可至其他班級進行補課，時效為本期課程期間內，且無法延至下一期課程，或是教練提供該週課表，學員自主完成訓練。': 'If you cannot attend a session, you may make it up in another class within the current season; make-ups cannot carry over to the next season. Alternatively, the coach may provide that week’s plan for you to complete independently.',
  '本課程非大型活動，不具比賽性質，故無保險服務，本人知悉本課程不包含保險，請學員自行斟酌是否另行加保。': 'This class is not a large-scale event or competition and does not include insurance. I understand that insurance is not provided and that students should decide whether to obtain their own coverage.',
  '如您曾發生下列症狀及狀況，屬猝死高危險群，請諮詢醫生專業判斷，慎重考慮自身安全，切勿勉強參加。 A. 不明原因的頭暈、胸部不適（胸悶、胸痛）、呼吸困難 B. 突然失去知覺 C. 高血壓（>140/90mmHg） D. 心臟病 E. 腎功能異常 F. 糖尿病 G. 高血脂（總膽固醇 >240mg/DI） H. 家族心臟病史（一等親在 60 歲前發生心臟病或猝死） I. 癲癇': 'If you have experienced any of the following symptoms or conditions, these rules identify you as at increased risk of sudden death. Consult a doctor, carefully consider your safety, and do not force yourself to participate.\nA. Unexplained dizziness, chest discomfort (tightness or pain), or difficulty breathing\nB. Sudden loss of consciousness\nC. High blood pressure (>140/90 mmHg)\nD. Heart disease\nE. Abnormal kidney function\nF. Diabetes\nG. High blood lipids (total cholesterol >240 mg/DI)\nH. Family history of heart disease (a first-degree relative with heart disease or sudden death before age 60)\nI. Epilepsy',
  '本人是自願參加本活動，並願意承擔自身的意外風險及責任，並無權向主辦單位（包括教練、職員、直接或間接與活動有關人士、工作人員或組織等）、及其它相關機構等，對本人在訓練中、往返活動場地途中、活動中發生或其引致之自身意外、死亡或任何形式的損失索償或追討責任。': 'I participate voluntarily and accept the personal risk and responsibility for accidents. I waive claims against the organizer, including coaches, employees, people, staff, or organizations directly or indirectly involved, and other related institutions for personal accidents, death, or losses of any kind occurring during training, travel to or from the venue, or participation in the activity, or arising from them.',
  '本人聲明：本人身體健康及有能力參加本活動，並經由執業醫生確認本人之體適能合乎參加該活動。': 'I declare that I am healthy and able to participate, and that a licensed doctor has confirmed my fitness for this activity.',
  '本課程無傷停機制，運動具有潛在運動傷害之風險，在課程中，如遇運動傷害之學員，需主動通報教練團，教練團將給予專業醫生及治療師之建議，並於受傷期間的課程中，給予個別化恢復運動能力之訓練及建議。': 'The class has no injury suspension mechanism. Exercise carries a risk of injury. Students who are injured must notify the coaching team, which will recommend professional doctors and therapists and provide individualized training and guidance to rebuild exercise capacity during classes while injured.',
  '本人接受並遵守教練團隊為目標賽事或活動訂立的所有訓練規則；如未能遵守規則，則主辦者有取消本人訓練營資格的權利。若多次未與教練討論並私下參加非目標賽事；未配合訓練營訓練課表，導致影響訓練成效或受傷，主辦者概不負責。': 'I accept and will follow all training rules established by the coaching team for the target race or event. The organizer may cancel my camp eligibility if I do not comply. The organizer is not responsible for reduced training effectiveness or injury resulting from repeatedly entering non-target races without discussing them with the coach or from not following the camp training plan.',
  '本人同意並授權團隊於本跑班中進行拍攝、肖像使用、及公開展示本人之肖像（包含照片及視訊影像）、名字、聲音於本活動作品上。除主辦單位與本課程相關贊助單位，基於宣傳用途之播放、展出或登載行為外，不得另做其他用途。': 'I authorize the team to photograph or record me during this running program and to use and publicly display my likeness, including photographs and video, name, and voice in materials from the activity. These may be broadcast, exhibited, or published for promotion by the organizer and sponsors associated with the class, but may not be used for other purposes.',
  '本人同意授權主辦單位得將前述著作，以各種管道或印刷方式呈現授權內容之全部或部分、並可公開發表，無須再通知或經由本人同意，唯公開發表時必須尊重本人之形象。': 'I authorize the organizer to present all or part of these materials through various channels or in print and to publish them without further notice or consent, provided that public presentation respects my image.',
  '本課程以喜愛跑步運動民眾為招募對象，非跑步教練（師資）培訓班，若發現有學員以電子器材方式或任何形式刻意全程記錄課程內容，經屢勸不聽或不願配合，主辦單位有權謝絕繼續參與課程，剩餘課程退費金額比照一般退費規範。': 'This program is for people who enjoy running and is not a running coach training course. If a student deliberately records entire sessions electronically or by any other means and repeatedly ignores requests to stop, the organizer may refuse further participation. Refunds for remaining sessions follow the standard refund rules.',
  '本課程家人、朋友謝絕旁聽，除教練團與主辦單位相關人員外，如有特殊需求，請洽隨班教練，若因故需暫時離開群體時，務必告知教練，以策安全。': 'Family and friends may not observe classes. Apart from coaches and organizer personnel, special requests should be discussed with the class coach. For safety, tell the coach if you need to leave the group temporarily.',
  '本課程教練配置基本為：一位教練，如總教練為培育其他助教，則將安排一位（或以上）助教協助課程。': 'A class normally has one coach. The head coach may assign one or more assistant coaches to support the class as part of their development.',
  '以上事項如有未盡事宜，得隨時修訂之，本活動單位保有更動修改之權利。': 'The organizer reserves the right to amend these provisions at any time to address matters not covered.',
  '完成報名繳費之參加者，視為同意以上聲明。': 'Participants who complete registration and payment are deemed to agree to the statements above.',
  '手機條碼載具（請於下方欄位填寫）': 'Mobile barcode carrier (enter below)',
  '寄至其他電子信箱（請於下方欄位填寫）': 'Send to another email address (enter below)',
}
