export const adminProductEnglishCopy: Record<string, string> = {
  '請填寫商品名稱、分類並上傳主圖。': 'Enter a product name and category, and upload a main image.',
  '媒體服務尚未設定。': 'Media service is not configured.',
  '無法建立影片上傳憑證。': 'Unable to create a video upload token.',
  '圖片上傳失敗。': 'Image upload failed.',
  '請重新登入管理員帳號。': 'Sign in to your administrator account again.',
  '影片上傳失敗。': 'Video upload failed.',
  '待儲存': 'Unsaved',
  '已保存': 'Saved',
  '未上傳': 'Not uploaded',
  '上傳成功。儲存商品後，變更才會顯示於商店。': 'Upload complete. Save the product to show the changes in the shop.',
  '媒體上傳失敗，請再試一次。': 'Media upload failed. Try again.',
  '商品未儲存成功，請查看錯誤訊息後再試一次。': 'The product was not saved. Review the error and try again.',
  '商品已建立。': 'Product created.',
  '商品已儲存。': 'Product saved.',
  '商品未儲存成功，請再試一次。': 'The product was not saved. Try again.',
  '商品刪除失敗，請再試一次。': 'Unable to delete the product. Try again.',
  '編輯商品': 'Edit product',
  '上架': 'Published',
  '下架': 'Unpublished',
  '商品上架': 'Publish product',
  '未儲存變更': 'Unsaved changes',
  '尚未建立': 'Not created yet',
  '已儲存': 'Saved',
  '儲存中': 'Saving',
  '建立商品': 'Create product',
  '儲存商品': 'Save product',
  '商品編輯內容': 'Product editor content',
  '商品名稱': 'Product name',
  '輸入商品名稱': 'Enter product name',
  '商品摘要': 'Product summary',
  '用一句話說明商品特色': 'Summarize the product in one sentence',
  '介紹商品特色、使用情境與保養方式。': 'Describe the product, how to use it, and care instructions.',
  '規格請在尺碼下方另外填寫。': 'Enter specifications separately below the size options.',
  '舊版重點與保養內容已合併於簡介；原有規格保留於獨立欄位。': 'Legacy highlights and care instructions have been merged into the description. Specifications remain in separate fields.',
  '售價庫存與媒體': 'Price, stock, and media',
  '售價（新台幣）': 'Price (NT$)',
  '洽詢售價可留空': 'Leave blank for price enquiries',
  '可選商品尺碼': 'Available sizes',
  '自訂尺碼': 'Custom sizes',
  '如：F、均碼': 'For example: F, One size',
  '加入': 'Add',
  '取消自訂尺碼': 'Cancel custom sizes',
  '不分尺碼的商品可全部不選。': 'Leave all sizes unselected if the product has no size options.',
  '每組規格選一項，以逗號、頓號或換行分隔。所有規格共用上方售價與總庫存；說明文字請放商品簡介。': 'Customers choose one option per group. Separate options with commas or new lines. All options share the price and total stock above. Put descriptive text in the product description.',
  '名稱': 'Name',
  '如：顏色、包裝': 'For example: Color, Packaging',
  '可選項目': 'Available options',
  '如：黑色、白色，或每行一個選項': 'For example: Black, White, or one option per line',
  '未填寫時，商店不顯示規格區。': 'The shop hides the specifications section when this is empty.',
  '新增規格': 'Add specification',
  '媒體檔案': 'Media files',
  '主圖': 'Main image',
  '上傳中': 'Uploading',
  '更換': 'Replace',
  '上傳': 'Upload',
  '商品主圖': 'Product main image',
  '影片': 'Video',
  '商品影片': 'Product video',
  '移除商品影片': 'Remove product video',
  '詳情圖': 'Detail images',
  '管理': 'Manage',
  '最多 12 張，只顯示保存結果。': 'Up to 12 images. Only saved results are listed.',
  '詳情圖片': 'Detail image',
  '加入詳情圖': 'Add detail image',
  '後台不顯示預覽，媒體於商店正常展示。': 'Media previews are shown in the shop, not in this editor.',
  '款式與進階設定': 'Styles and advanced settings',
  '個款式': 'styles',
  '商品標籤': 'Product tags',
  '以逗號分隔': 'Separate with commas',
  '官方商品連結': 'Official product link',
  '商品款式': 'Product styles',
  '不同顏色或版型需要不同圖片時才新增。': 'Add styles when colors or designs need different images.',
  '新增款式': 'Add style',
  '如：黑色': 'For example: Black',
  '更換款式主圖': 'Replace style main image',
  '上傳款式主圖': 'Upload style main image',
  '款式主圖已上傳': 'Style main image uploaded',
  '尚未上傳主圖': 'Main image not uploaded',
  '/ 詳情圖': '/ Detail images',
  '款式詳情圖': 'Style detail image',
  '圖片': 'Image',
  '張': 'images',
  '刪除商品': 'Delete product',
  '放棄變更': 'Discard changes',
  '刪除商品確認': 'Confirm product deletion',
  '商品將立即從商店移除，既有訂單仍會保留。': 'The product will be removed from the shop immediately. Existing orders will be retained.',
  '刪除中': 'Deleting',
  '確認刪除': 'Confirm deletion',
  '清除商品搜尋': 'Clear product search',
  '清除篩選': 'Clear filters',
  '正在新增商品': 'Adding a product',
  '上架中': 'Published',
  '瀏覽器無法建立圖片裁切畫布。': 'Your browser could not create the image crop canvas.',
  '裁切圖片輸出失敗。': 'Unable to export the cropped image.',
  '圖片裁切失敗。': 'Image cropping failed.',
  '裁切圖片': 'Crop image',
  '關閉圖片裁切': 'Close image cropper',
  '待裁切圖片預覽': 'Image crop preview',
  '無法讀取這張圖片，請重新選擇 JPG、PNG 或 WebP 圖片。': 'Unable to read this image. Choose a JPG, PNG, or WebP image.',
  '原圖': 'Original',
  'px · 裁切輸出': 'px · Cropped output',
  '圓框為課程顯示效果，儲存為 1:1 圖片。': 'The circle previews the class portrait. The saved image is square.',
  '裁切後解析度偏低，建議減少放大或選用更高解析度原圖。': 'The cropped resolution is low. Zoom out or choose a higher-resolution original.',
  '縮放': 'Zoom',
  '左右位置': 'Horizontal position',
  '上下位置': 'Vertical position',
  '裁切並上傳中': 'Cropping and uploading',
  '套用裁切並上傳': 'Apply crop and upload',
  '請填寫每個款式的名稱並上傳款式主圖。': 'Enter a name and upload a main image for each style.',
  '售價必須介於 0 與 100,000 元之間。': 'Price must be between NT$0 and NT$100,000.',
  '庫存必須是介於 0 與 1,000,000 的整數。': 'Stock must be a whole number between 0 and 1,000,000.',
  '商品簡介超過 5,000 字，請整理後再儲存，避免內容被截斷。': 'The description exceeds 5,000 characters. Shorten it before saving to avoid truncation.',
  '商品規格最多 30 項。': 'A product can have up to 30 specifications.',
  '規格名稱最多 80 字，內容最多 300 字。': 'Specification names can have up to 80 characters and options up to 300.',
}
