// Storefront interface and the repository's standard product copy.
export const shopEnglishCopy: Record<string, string> = {
  '關閉提示': 'Dismiss notification',
  '返回購物車': 'Back to cart',
  '購物車資料格式無效。': 'Invalid cart data.',
  '商品規格格式無效，請回商品頁重新選擇。': 'Invalid product options. Return to the product page and select them again.',
  '購物車包含無效商品，請重新確認。': 'Your cart contains an invalid product. Review it before continuing.',
  '購物車沒有可提交的商品。': 'Your cart has no items that can be ordered.',
  '商城規格功能尚未完成資料庫升級，請聯絡好運協助，暫勿重複匯款。': 'Product options are temporarily unavailable. Contact Nurture for help and do not transfer payment again.',
  '訂單已建立，但安全憑證產生失敗，請聯絡客服。': 'Your order was created, but its access token could not be generated. Contact support.',
  '訂單已建立，但匯款資料寫入失敗，請聯絡好運協助處理。': 'Your order was created, but the transfer details could not be saved. Contact Nurture for help.',
  '商城匯款資料請在結帳時一併提交。': 'Submit shop transfer details during checkout.',
  '購物車商品數量無效。': 'Invalid item quantity in cart.',
  '購物車包含無效商品。': 'Your cart contains an invalid product.',
  '商品尺碼已更新，請回商品頁重新選擇。': 'Product sizes have changed. Return to the product page and select again.',
  '商品款式已更新，請回商品頁重新選擇。': 'Product styles have changed. Return to the product page and select again.',
  '商品規格格式無效。': 'Invalid product options.',
  '每組商品規格只能選擇一項。': 'Choose one option from each specification group.',
  '洽詢售價': 'Ask for pricing',
  '商品資料載入失敗。': 'Unable to load product details.',
  '商品資料暫時無法確認，請重新整理頁面後再結帳。': 'Product details cannot be verified right now. Refresh before checking out.',
  '購物車沒有商品。': 'Your cart is empty.',
  '正在確認商品規格，請稍候。': 'Checking product options. Please wait.',
  '請先回商品頁重新選擇規格，再提交訂單。': 'Return to the product page and select the options again before placing your order.',
  '請填寫姓名和聯絡方式。': 'Enter your name and contact details.',
  '請完成匯款，並填寫轉出帳號後五碼。': 'Complete the transfer and enter the last five digits of the sending account.',
  '訂單提交失敗。': 'Unable to submit your order.',
  '正在讀取購物車': 'Loading cart',
  '訂單已送出': 'Order submitted',
  '訂單已送出，等待入帳核對': 'Order submitted; awaiting payment verification',
  '確認訂單': 'Review your order',
  '填寫聯絡資料、依下方好運匯款帳戶完成轉帳，再提交訂單。款項核對完成後，團隊會聯絡你確認跑班自取時間與地點。': 'Enter your contact details, transfer payment to the Nurture account below, and submit your order. After verification, the team will contact you to arrange pickup.',
  '以下商品規格已更新或尚未選齊，請先重新選擇，再匯款結帳。': 'The product options below have changed or are incomplete. Select them again before transferring payment and checking out.',
  '重新選擇': 'Select again',
  '聯絡與取貨資料': 'Contact and pickup details',
  '姓名 *': 'Name *',
  '收件人姓名': 'Customer name',
  '聯絡方式 *': 'Contact details *',
  '手機號碼或 LINE ID': 'Mobile number or LINE ID',
  '用於接收訂單通知（選填）': 'For order notifications (optional)',
  '好運銀行匯款帳戶': 'Nurture bank transfer account',
  '請依右側訂單小計完成匯款，並確認銀行機構、代碼與帳號後再轉帳。': 'Transfer the order subtotal shown in the summary. Check the bank, bank code, and account number before sending.',
  '查看好運匯款帳戶': 'View Nurture transfer account',
  '網站只記錄轉出帳號後五碼，不會要求網銀密碼或完整付款帳號；匯款備註請保持空白。': 'We only record the last five account digits, never your banking password or full sending account number. Leave the transfer reference blank.',
  '轉出帳號後五碼 *': 'Last five sending account digits *',
  '財務會依後五碼與訂單金額核對入帳。': 'Finance verifies the payment using these digits and the order amount.',
  '訂單備註': 'Order notes',
  '尺寸或其他需求（選填）': 'Size or other requests (optional)',
  '訂單摘要': 'Order summary',
  '數量': 'Quantity',
  '商品數量': 'Item count',
  '小計': 'Subtotal',
  '付款方式為銀行匯款，商品維持跑班自取；完成入帳核對後，團隊會另行通知取貨安排。': 'Pay by bank transfer and collect from the running team. We will contact you about pickup after payment verification.',
  '正在提交匯款訂單...': 'Submitting transfer order…',
  '提交匯款與自取訂單': 'Submit transfer and pickup order',
  '訂單送出': 'Submit order',
  '正在提交...': 'Submitting…',
  '商品詳情': 'Product details',
  '載入商品': 'Loading product',
  '找不到這件商品': 'Product not found',
  '返回好運商店': 'Back to Nurture Shop',
  '麵包屑': 'Breadcrumb',
  '商品圖片': 'Product images',
  '款式': 'Style',
  '商品尺碼': 'Size',
  '商品規格': 'Specifications',
  '減少數量': 'Decrease quantity',
  '增加數量': 'Increase quantity',
  '目前售完': 'Currently sold out',
  '加入購物車': 'Add to cart',
  '直接購買': 'Buy now',
  '聯絡購買': 'Contact to buy',
  '商品簡介': 'Product description',
  '商品操作': 'Product actions',
  '商品詳情 - 好運商店': 'Product details - Nurture Shop',
  '商品資料暫時無法載入，請稍後重新整理。': 'Products are temporarily unavailable. Please refresh later.',
  '商品資料載入中': 'Loading products',
  '商品分類': 'Product categories',
  '商品排序': 'Sort products',
  '推薦排序': 'Recommended',
  '價格低到高': 'Price: low to high',
  '價格高到低': 'Price: high to low',
  '重新載入商品': 'Reload products',
  '售完': 'Sold out',
  '找不到符合條件的商品': 'No products match your filters',
  '清除搜尋條件': 'Clear search',
  '關閉購物車': 'Close cart',
  '規格需重新確認。': 'Recheck your product options.',
  '剩餘可加': 'Available to add',
  '已加入': 'Added',
  '購物車是空的': 'Your cart is empty',
  '加入商品後，這裡會顯示品項、尺碼、規格、數量與小計。': 'Add products to see their sizes, options, quantities, and subtotal here.',
  '前往結帳': 'Checkout',
  '繼續選購': 'Continue shopping',
  '清空': 'Clear cart',
  '匯款資料暫時無法讀取。': 'Transfer details are temporarily unavailable.',
  '匯款資料暫時無法讀取，請重新整理後再試。': 'Transfer details are temporarily unavailable. Refresh and try again.',
  '正在讀取匯款資料…': 'Loading transfer details…',
  '商品規格已更新或尚未選齊，請回商品頁重新選擇後加入購物車。': 'Product options have changed or are incomplete. Return to the product page, select them again, and add the item to your cart.',
  '尺寸': 'Size',
  '尺碼': 'Size',
  '顏色': 'Color',
  '配色': 'Colorway',
  '商品特色': 'Product features',
  '商品資訊': 'Product information',
  '保養提醒': 'Care instructions',
  '私訊諮詢': 'Message us',
  '好運競速跑步背心': 'Nurture Racing Singlet',
  '跑者服飾': 'Running apparel',
  '好運跑步 T 恤': 'Nurture Running T-shirt',
  '好運運動毛巾': 'Nurture Sports Towel',
  '跑者配件': 'Running accessories',
  '運動補給': 'Sports nutrition',
  '團隊裝備': 'Team gear',
  '好運跑班團隊競速背心，提供兩款配色與 XS 至 XL 尺寸。': 'The Nurture team racing singlet comes in two colorways and sizes XS to XL.',
  '適合團練、賽事與日常跑步穿著的好運跑班團隊背心。可依喜好選擇紫電白或曜黑藍款式，並在下單前確認需要的尺寸。': 'A Nurture team singlet for group training, races, and everyday runs. Choose Purple Lightning White or Obsidian Blue and check your size before ordering.',
  '兩款團隊配色': 'Two team colorways',
  'XS 至 XL 尺寸': 'Sizes XS to XL',
  '團練與賽事皆可穿著': 'For group training and racing',
  '請依商品頁尺寸選項下單。': 'Order using the size options on the product page.',
  '清洗與保養方式以商品實際洗標為準。': 'Follow the care label on the product.',
  '紫電白': 'Purple Lightning White',
  '曜黑藍': 'Obsidian Blue',
  '好運跑班團隊 T 恤，提供 XS 至 XL 尺寸選擇。': 'The Nurture team T-shirt is available in sizes XS to XL.',
  '把好運跑班識別帶進團練與日常穿搭。商品頁可直接查看圖片、售價、庫存與可選尺寸。': 'Wear the Nurture team identity in group training and everyday life. View photos, prices, stock, and available sizes on the product page.',
  '好運跑班團隊設計': 'Nurture team design',
  '適合團練與日常穿著': 'For group training and everyday wear',
  '好運跑步帽': 'Nurture Running Cap',
  '日常訓練': 'Daily training',
  '黑色好運跑步帽，正面好運刺繡、側面閃電圖樣與背面馬蹄識別。': 'A black Nurture running cap with front embroidery, a lightning motif on the side, and a horseshoe emblem on the back.',
  '適合跑步、運動與日常休閒搭配的好運跑班帽款。商品圖完整呈現正面、側面、背面與實際配戴效果。': 'A Nurture cap for running, exercise, and casual wear. Product photos show the front, sides, back, and fit.',
  '正面好運刺繡': 'Nurture embroidery on the front',
  '側面閃電圖樣': 'Lightning motif on the side',
  '背面馬蹄識別': 'Horseshoe emblem on the back',
  '提供實際配戴圖片': 'Photos showing the fit',
  '黑色': 'Black',
  '請依頭圍與商品尺寸選項選購。': 'Choose based on your head circumference and the available sizes.',
  '清潔與保養方式以商品實際標示為準。': 'Follow the cleaning and care instructions on the product.',
  '訓練必備': 'Training essential',
  '33 × 70 公分好運運動毛巾，適合團練、比賽與運動後使用。': 'A 33 × 70 cm Nurture sports towel for training, racing, and post-workout use.',
  '以好運跑班品牌識別製作的運動毛巾，尺寸清楚、方便放入訓練包，適合日常訓練與賽事攜帶。': 'A sports towel featuring the Nurture identity, sized to fit your training bag for daily workouts and races.',
  '33 × 70 公分': '33 × 70 cm',
  '好運跑班品牌圖樣': 'Nurture team branding',
  '訓練與賽事方便攜帶': 'Easy to carry to training and races',
  '首次使用前建議先清洗。': 'Wash before first use.',
  '清洗與保養方式以商品實際標示為準。': 'Follow the washing and care instructions on the product.',
  'CALBOMB 蜂蜜檸檬能量膠': 'CALBOMB Honey Lemon Energy Gel',
  '訓練補給': 'Training fuel',
  '無添加認證': 'Additive-free certification',
  '每包 50 mL、含 42 g 碳水化合物與 170 kcal 的蜂蜜檸檬能量膠。': 'Honey lemon energy gel with 42 g of carbohydrate and 170 kcal per 50 mL packet.',
  'CALBOMB 蜂蜜檸檬能量膠採用蜂蜜配方，官方標示葡萄糖與果糖比例為 5:2，並取得 2024 A.A. 無添加驗證。適合依個人補給策略安排於訓練或賽事中使用。': 'CALBOMB Honey Lemon Energy Gel uses a honey formula with a stated glucose-to-fructose ratio of 5:2 and 2024 A.A. additive-free certification. Use during training or races according to your personal fueling plan.',
  '每包 42 g 碳水化合物': '42 g carbohydrate per packet',
  '每包 170 kcal': '170 kcal per packet',
  '50 mL 包裝': '50 mL packet',
  '2024 A.A. 無添加驗證': '2024 A.A. additive-free certification',
  '容量': 'Volume',
  '碳水化合物': 'Carbohydrate',
  '42 g / 包': '42 g / packet',
  '熱量': 'Energy',
  '170 kcal / 包': '170 kcal / packet',
  '風味': 'Flavor',
  '蜂蜜檸檬': 'Honey lemon',
  '請依個人訓練、賽事與飲食需求安排補給。': 'Plan your fueling around your training, racing, and dietary needs.',
  '食品資訊、過敏原與保存方式以商品包裝標示為準。': 'Refer to the packaging for food information, allergens, and storage instructions.',
  '匯款狀態讀取失敗。': 'Unable to load transfer status.',
  '尚未提交': 'Not submitted',
  '正在讀取匯款狀態': 'Loading transfer status',
  '目前沒有課程匯款資料': 'No class payment records yet',
  '從課程表進入課程詳情並完成報名後，核對狀態會顯示在這裡。': 'Open a class from the schedule and complete registration. Your payment verification status will appear here.',
  '好運跑班課程': 'Nurture Running Team class',
  '應匯金額': 'Amount to transfer',
  '依報名資料': 'As shown in your registration',
  '匯款資料提交': 'Transfer details submitted',
  '核對說明：': 'Verification note: ',
  '查看報名與匯款資料': 'View registration and transfer details',
}
