export const notificationEnglishCopy: Record<string, string> = {
  '補件要求與站內通知已保存，請查看下方郵件寄送狀態。': 'The follow-up request and in-site notification have been saved. Check the email status below.',
  '資料已送出，財務會重新核對。': 'Your details have been submitted. Finance will review them again.',
  '待回報匯款': 'Transfer not yet reported',
  '待人工核對': 'Awaiting payment review',
  '待學生補充': 'Awaiting student response',
  '已確認入帳': 'Payment confirmed',
  '郵件等待寄送': 'Email queued',
  '郵件寄送中；如超過一分鐘仍未更新，可重試': 'Sending email. Retry if the status has not updated after one minute.',
  '郵件服務已接受寄送': 'Email accepted for delivery',
  '郵件寄送失敗或尚未確認': 'Email failed or delivery has not been confirmed',
  '郵件服務尚未設定': 'Email service is not configured',
  '已超過安全重試時限，請人工確認郵件紀錄': 'The retry window has expired. Check the email records manually.',
  '已超過安全重試時限，請人工確認郵件紀錄；站內通知仍有效。': 'The retry window has expired. Check the email records manually. The in-site notification remains available.',
  '讀取失敗，已保留目前填寫的內容。': 'Unable to load. Your current input has been kept.',
  '操作失敗。': 'The action could not be completed.',
  '報名通知與核對待辦': 'Registration notifications and reviews',
  '我的報名通知': 'My registration notifications',
  '新報名、待核對與待學生補充分開處理。': 'Review new registrations, reported payments, and student follow-ups by status.',
  '補充資料沿用原報名，不需要重新報名。': 'Add details to your existing registration. You do not need to register again.',
  '返回銀行對帳': 'Back to bank reconciliation',
  '返回個人頁面': 'Back to my account',
  '重新整理': 'Refresh',
  '前往財務頁解鎖': 'Unlock access on the finance page',
  '正在確認登入狀態…': 'Checking sign-in status…',
  '登入後查看你的報名通知': 'Sign in to view your registration notifications',
  '登入後會保留目前這筆報名連結。': 'You will return to this registration after signing in.',
  '登入帳號': 'Sign in',
  '正在讀取報名…': 'Loading registrations…',
  '返回報名列表': 'Back to registrations',
  '找不到這筆報名，或目前帳號沒有查閱權限。': 'This registration was not found, or your account does not have access.',
  '報名進度': 'Registration progress',
  '應繳金額': 'Amount due',
  '待確認': 'To be confirmed',
  '帳號後五碼': 'Last five account digits',
  '尚未回報': 'Not yet reported',
  '匯款日期': 'Transfer date',
  '報名日期': 'Registration date',
  '請補充以下資料': 'Please provide the following details',
  '前次補充說明': 'Previous request for details',
  '學生備註': 'Student notes',
  '此季度已封存，僅供查閱。需要協助請聯絡跑班。': 'This season is archived and read-only. Contact the team if you need help.',
  '補件與寄送紀錄': 'Follow-up and email history',
  '補充紀錄': 'Follow-up history',
  '目前沒有補件紀錄。': 'No follow-ups yet.',
  '已結束': 'Closed',
  '學生回覆': 'Student reply',
  '內部備註：': 'Internal note: ',
  '無': 'None',
  '重試寄送': 'Retry email',
  '全部': 'All',
  '待核對': 'Awaiting review',
  '待回報': 'Awaiting transfer report',
  '待補充': 'Awaiting details',
  '已入帳': 'Payment confirmed',
  '已封存': 'Archived',
  '· 已封存': '· Archived',
  '本頁沒有符合條件的報名。': 'No matching registrations on this page.',
  '上一頁': 'Previous',
  '下一頁': 'Next',
  '這筆報名已確認入帳。': 'Payment for this registration has been confirmed.',
  '已通知學生補充。學生補交後，會重新進入待核對。': 'The student has been asked for details. Their response will return this registration to payment review.',
  '提醒回報／繳款': 'Send a payment or transfer report reminder',
  '請學生補充資料': 'Request details from the student',
  '處理原因': 'Reason',
  '給學生的說明': 'Message to the student',
  '會顯示在站內通知及郵件，請勿填寫內部資料。': 'This appears in the notification and email. Do not include internal information.',
  '帶入常用說明': 'Use a message template',
  '內部備註（選填）': 'Internal note (optional)',
  '僅管理員與獲授權財務可見。': 'Only administrators and authorized finance staff can see this.',
  '正在保存與寄送…': 'Saving and sending…',
  '發送通知與郵件': 'Send notification and email',
  '補件通知會沿用原報名。確認入帳仍請使用原有銀行對帳流程。': 'The request stays with the existing registration. Confirm payment through the bank reconciliation workflow.',
  '款項已確認入帳，報名完成。': 'Payment confirmed. Your registration is complete.',
  '資料已送出，等待財務核對。暫時不需要重複提交。': 'Your details have been submitted for finance review. There is no need to submit them again.',
  '補充資料': 'Provide details',
  '回報匯款': 'Report a bank transfer',
  '若已匯款，請填寫下方資料；若尚未匯款，請先查看收款資訊，完成付款後再回報。請勿填寫完整帳號或身分證號。': 'If you have transferred payment, complete the details below. Otherwise, view the payment instructions, pay, and then report your transfer. Do not enter a full bank account number or national ID number.',
  '收起收款資訊': 'Hide payment instructions',
  '查看收款資訊': 'View payment instructions',
  '匯款帳號後五碼': 'Last five digits of the sender’s account',
  '補充說明': 'Additional details',
  '（選填）': '(optional)',
  '請依財務說明補充資料，例如實際匯款金額、匯款人或其他需要核對的資訊。': 'Provide the details requested by finance, such as the amount transferred, sender, or other information needed for review.',
  '正在送出…': 'Submitting…',
  '送出資料，請財務核對': 'Submit for finance review',
  '無法讀取通知。': 'Unable to load notifications.',
  '標記已讀失敗。': 'Unable to mark notifications as read.',
  '通知暫時無法讀取，點擊重試': 'Notifications are unavailable. Select to retry.',
  '報名通知': 'Registration notifications',
  '通知': 'Notifications',
  '已讀不代表已完成核對或補件': 'Reading a notification does not complete a review or follow-up.',
  '關閉通知': 'Close notifications',
  '正在讀取通知…': 'Loading notifications…',
  '未讀': 'Unread',
  '目前沒有新通知。': 'No new notifications.',
  '將目前通知標為已讀': 'Mark displayed notifications as read',
  '查看報名待辦': 'View registration tasks',
  '資料不完整': 'Incomplete information',
  '尚未回報匯款': 'Transfer not yet reported',
  '金額不符': 'Amount mismatch',
  '其他': 'Other',
  '目前無法依已提供的資料核對款項，請確認匯款日期與帳號後五碼，並補充實際匯款金額。': 'We cannot match your payment using the information provided. Please confirm the transfer date and last five account digits, and tell us the amount transferred.',
  '目前尚未收到匯款回報。若已完成匯款，請補填匯款日期與帳號後五碼；若尚未匯款，請完成後回報。': 'We have not received a transfer report. If you have already paid, provide the transfer date and last five account digits. Otherwise, complete the transfer and then report it.',
  '目前查到的入帳金額與應繳金額不同，請補充實際匯款金額與日期，讓我們再次核對。': 'The payment found does not match the amount due. Please provide the actual transfer amount and date so we can check again.',
  '請選擇處理原因。': 'Select a reason.',
  '請填寫 1 至 1000 字的學生補充說明。': 'Enter a message to the student between 1 and 1,000 characters.',
  '內部備註不可超過 1000 字。': 'The internal note must not exceed 1,000 characters.',
  '有學生完成新報名': 'New student registration',
  '新報名已回報匯款，請核對。': 'A new registration includes a transfer report. Please review it.',
  '新報名成立，請查看報名狀態。': 'A new registration has been received. Please check its status.',
  '匯款資料待核對': 'Transfer details awaiting review',
  '學生已補交資料，請重新核對。': 'The student has provided additional details. Please review them.',
  '學生已回報匯款，請核對。': 'The student has reported a transfer. Please review it.',
  '你的報名需要補充資料': 'Your registration needs additional details',
  '匯款資料需要補充，請查看報名或聯絡財務。': 'More transfer details are needed. Open your registration or contact finance.',
  '款項已確認入帳': 'Payment confirmed',
  '課程報名已確認，請留意後續課程通知。': 'Your class registration is confirmed. Look out for upcoming class notifications.',
  '尚有報名待處理': 'Registrations need attention',
  '請查看現有報名的核對與補件狀態。': 'Check the review and follow-up status of existing registrations.',
  '請先登入後再查看匯款資料。': 'Sign in to view the bank transfer instructions.',
  '匯款資料讀取失敗。': 'Unable to load bank transfer instructions.',
  '正在安全讀取匯款資料': 'Loading bank transfer instructions securely',
}
