// Translations of the existing published policies. These do not change their terms.
export const policyEnglishCopy: Record<string, string> = {
  '版本：': 'Version: ',
  '我們只在提供課程、會員、帳務與商品服務所需的範圍內使用資料。': 'We use personal information only as needed to provide classes, membership, accounting, and product services.',
  '我們會收集哪些資料': 'Information we collect',
  '為完成會員、課程報名、緊急聯絡、出席核實、匯款核對、商品訂購與電子發票作業，我們只收集完成服務所需的資料。': 'We collect only the information needed for membership, class registration, emergency contact, attendance verification, transfer reconciliation, product orders, and electronic invoice processing.',
  '姓名、電子信箱、電話與 LINE 聯絡資料': 'Name, email address, phone number, and LINE contact details',
  '緊急聯絡人及電話': 'Emergency contact name and phone number',
  '跑步經驗、健康與傷病自述、目標賽事': 'Running experience, self-reported health and injuries, and target races',
  '課程報名、請假、補課、出席及教練核實紀錄': 'Registration, leave, make-up class, attendance, and coach verification records',
  '匯款後五碼、申報金額與財務核對結果': 'Last five transfer account digits, reported payment amount, and finance review results',
  '商品訂購、配送與電子發票資料': 'Product orders, delivery details, and electronic invoice information',
  '資料如何使用': 'How we use information',
  '資料僅用於提供課程、會員、出席、客服、帳務、商品與必要通知。教練只會看到執行教學與安全照護所需的學員資料，不會看到匯款後五碼或收款帳戶。': 'Information is used only for classes, membership, attendance, customer support, accounting, products, and necessary notifications. Coaches can see only the student information needed for teaching and safety. They cannot see the last five transfer account digits or the receiving bank account.',
  '保存與安全': 'Retention and security',
  '我們使用具權限控管的系統保存資料。匯款資料只在登入後的授權流程與管理員後台顯示；網站不會直接保存信用卡號、到期日或 CVC。': 'We store information in systems with access controls. Bank transfer information is shown only in authorized signed-in workflows and administration pages. The website does not directly store credit card numbers, expiry dates, or CVC codes.',
  '保存期間依服務、交易、稅務與爭議處理需要決定；正式上線前由管理者補入各類資料的實際期間。': 'Retention periods depend on service, transaction, tax, and dispute-resolution needs. Before formal launch, the administrator will specify the actual retention period for each category of information.',
  '資料可能在網站代管、資料庫、儲存、寄信與必要客服服務所在的地區處理；正式上線前應確認供應商與跨境傳輸範圍。': 'Information may be processed in the regions used by our website hosting, database, storage, email, and necessary customer support providers. Providers and the scope of cross-border transfers should be confirmed before formal launch.',
  '資料只提供給執行課程、客服、帳務、配送、發票與網站維運的必要人員或受託服務商。': 'Information is shared only with the personnel or contracted providers needed for classes, customer support, accounting, delivery, invoicing, and website operation.',
  '你的權利': 'Your rights',
  '你可以聯絡好運跑班申請查詢、更正或刪除個人資料，也可以詢問使用目的、處理方式與提供對象。刪除或拒絕提供必要資料，可能導致無法完成登入、報名、匯款核對、配送或發票作業。涉及已完成交易、發票、稅務、爭議處理或法定保存義務的資料，會依必要期間保留。正式上線前請補入正式聯絡信箱與資料保護窗口。': 'You may contact Nurture Running Team to request access to, correction of, or deletion of your personal information, or to ask about its purposes, processing methods, and recipients. Deleting or declining to provide necessary information may prevent sign-in, registration, transfer reconciliation, delivery, or invoicing. Information related to completed transactions, invoices, taxes, disputes, or statutory retention duties will be kept for the necessary period. An official contact email and data protection contact must be added before formal launch.',
  '影像與公開使用': 'Photography and public use',
  '課程或活動可能進行攝影。公開使用將依報名時同意的肖像授權範圍辦理；如有特殊需求，請於活動前向隨班教練提出。': 'Classes and events may be photographed. Public use will follow the image-use permission agreed to at registration. Tell your class coach before the activity if you have special requirements.',
  '報名前請閱讀課程安全、名額、請假補課及現場秩序規範。': 'Before registering, read the rules on class safety, places, leave, make-up sessions, and conduct.',
  '服務提供者與同意': 'Service provider and agreement',
  '本網站由好運跑班提供。經營主體名稱、聯絡地址與正式客服信箱目前尚待管理者確認，正式上線前會補入本條款與頁尾。送出報名或使用服務前，請閱讀並同意當時顯示的條款版本。': 'This website is provided by Nurture Running Team. The legal operator’s name, contact address, and official customer support email are awaiting administrator confirmation and will be added to these terms and the footer before formal launch. Before submitting a registration or using the services, read and agree to the version of the terms displayed at that time.',
  '報名與名額': 'Registration and places',
  '送出報名表不等於已完成報名。學員完成匯款回報後，仍需由財務人工核對銀行入帳；只有顯示「已確認入帳」才代表報名完成。': 'Submitting a registration form does not complete registration. After a student reports a bank transfer, finance must manually verify receipt. Registration is complete only when the status shows “Payment confirmed”.',
  '課程安全與健康': 'Class safety and health',
  '學員應依自身健康狀況評估是否參加，穿著合適裝備並遵守教練與助教指導。如有胸痛、呼吸困難、暈眩、失去意識或其他高風險症狀，應先諮詢專業醫療人員。': 'Students should assess participation according to their health, wear suitable equipment, and follow coaches’ and assistants’ instructions. If you experience chest pain, difficulty breathing, dizziness, loss of consciousness, or other high-risk symptoms, consult a healthcare professional first.',
  '天候、場地與停課': 'Weather, venues, and cancellations',
  '豪大雨、雷擊、颱風、地震、政府停班停課或場地不適合訓練時，團隊將以安全為優先調整地點、內容或停課，並於課程 LINE 群組公告後續安排。': 'In heavy rain, lightning, typhoons, earthquakes, government-declared work or school closures, or unsuitable venue conditions, the team will prioritize safety by changing the location or session content, or cancelling the session. Further arrangements will be announced in the class LINE group.',
  '請假與補課': 'Leave and make-up sessions',
  '請假與補課限當期課程，須依網站當下可選課次、班級名額與教練安排辦理，不能延至下一季度。': 'Leave and make-up sessions apply only to the current season and depend on the sessions available on the website, class capacity, and coach arrangements. They cannot be carried into the next season.',
  '課程內容與秩序': 'Class content and conduct',
  '課程是跑步訓練服務，不是教練培訓班。未經同意不得以電子器材或其他方式全程複製課程內容；家人與朋友原則上不得旁聽，特殊需求請先聯絡隨班教練。': 'These classes provide running training, not coach certification. Do not reproduce entire sessions using electronic devices or other means without permission. Family and friends generally may not observe classes; contact your class coach in advance about special requests.',
  '教練代班與變更': 'Substitute coaches and changes',
  '原定教練請假時，可能由受邀且確認的代班教練授課；網站會保留原定與實際授課紀錄。課程時間、場地、教練或內容如需調整，將依安全與可執行性公告，學員可依當期退費與補課規則提出疑問。': 'If the scheduled coach is absent, an invited and confirmed substitute may teach the session. The website retains records of both the scheduled and actual coach. Changes to time, venue, coach, or content will be announced based on safety and feasibility. Students may raise questions under the season’s refund and make-up rules.',
  '保險、責任與爭議': 'Insurance, responsibility, and disputes',
  '學員應自行評估健康狀況並妥善投保所需保險；網站不在未經確認的情況下承諾特定保險內容。爭議請先透過正式客服管道聯絡；適用法律與管轄資訊待經營主體確認後補入。': 'Students should assess their health and obtain any insurance they need. The website does not promise specific insurance coverage without confirmation. Contact official customer support first about disputes. Applicable law and jurisdiction information will be added once the legal operator is confirmed.',
  '條款更新': 'Updates to these terms',
  '本條款如有更新，將以網站公布版本為準。已完成的報名會保留當時同意的條款版本與時間。': 'Updates to these terms take effect as published on the website. Completed registrations retain the version agreed to and the time of agreement.',
  '退費會依申請時間、已進行課次與報名價格快照核對。': 'Refunds are reviewed against the request date, sessions already held, and the price recorded at registration.',
  '課程取消與退費': 'Class cancellations and refunds',
  '報名成功後，如在第二堂課開始前提出取消，退還尚未進行堂數的費用；第三堂課開始後原則上不退費。實際計算以該班已進行課次與報名時的價格快照為準。': 'After registration is confirmed, cancellation requested before the second session starts receives a refund for sessions not yet held. Refunds are generally unavailable once the third session starts. The actual calculation uses sessions already held for the class and the price recorded at registration.',
  '商品退換貨': 'Product returns and exchanges',
  '商品退換貨與課程取消退費分開處理。商品須保持未使用、完整包裝與可再次銷售狀態；實際可退換範圍依商品性質、配送狀況與當期公告確認。': 'Product returns and exchanges are handled separately from class cancellation refunds. Products must be unused, in complete packaging, and suitable for resale. Eligibility depends on the product, delivery conditions, and current announcements.',
  '申請方式': 'How to apply',
  '請透過官方 Instagram 或所屬班級聯絡管道提出，並提供報名姓名、課程、原因及退款銀行帳戶。退款金額可能扣除已發生的行政或轉帳手續費，核對完成後另行通知。': 'Apply through our official Instagram or your class contact channel. Provide the registration name, class, reason, and bank account for the refund. Incurred administrative or transfer fees may be deducted. You will be notified after the review is complete.',
  '處理時間與費用': 'Processing time and fees',
  '收到完整申請與必要資料後，會先進行報名、課次、商品或匯款核對，再通知可退金額與處理進度。實際處理工作日、匯費承擔方式與退款帳戶要求，正式上線前由管理者補入並以申請時公告為準。': 'After receiving a complete request and the necessary information, we will check the registration, sessions, products, or transfer, then confirm the refundable amount and progress. The administrator will specify processing business days, responsibility for transfer fees, and refund account requirements before formal launch. The announcement current at the time of application applies.',
  '傷病與個別狀況': 'Injury, illness, and individual circumstances',
  '課程沒有自動傷停機制。因傷病無法參加時，請先聯絡教練評估訓練調整；如需取消，仍依本政策與個案所需證明辦理。': 'Classes do not include an automatic injury suspension. If injury or illness prevents participation, contact your coach first to assess training adjustments. Cancellations remain subject to this policy and any evidence required for the individual case.',
  '停課與不可抗力': 'Cancelled sessions and force majeure',
  '由團隊公告的停課將優先安排補課、延期或等值處理；颱風、地震、政府命令或其他不可抗力情況，依當期公告與實際可執行方案處理。': 'For sessions cancelled by the team, priority will be given to make-up sessions, postponement, or an equivalent arrangement. Typhoons, earthquakes, government orders, and other force majeure events are handled according to current announcements and feasible arrangements.',
  '網站會依經營主體與實際發票資格公告可提供的合法憑證方式；目前尚未承諾一定開立電子發票。': 'The website will announce the lawful receipts or invoices available based on the operator and its actual invoicing eligibility. Electronic invoices are not currently guaranteed.',
  '開立資格與經營者資料': 'Invoicing eligibility and operator details',
  '目前網站尚未確認經營主體、稅籍資料與電子發票開立資格，因此本頁不承諾一定會開立電子發票。正式上線前，管理者必須補入真實經營者名稱、統一編號、發票作業方式與客服聯絡資料；如尚未具備資格，會改以實際可提供的合法憑證方式公告。': 'The website has not yet confirmed its legal operator, tax registration, or electronic invoicing eligibility, so this page does not guarantee electronic invoices. Before formal launch, the administrator must provide the actual operator name, business tax ID, invoicing process, and customer support contact. If electronic invoicing is unavailable, the lawful receipt or invoice options actually available will be announced instead.',
  '電子發票資料': 'Electronic invoice information',
  '報名時可選擇手機條碼載具、寄送至其他電子信箱，或寄送至本次報名信箱。需要統一編號與抬頭時，請在送出前確認資料正確。': 'During registration, you may select a mobile barcode carrier, another email address, or the registration email address. If you need a business tax ID and invoice title, check that they are correct before submitting.',
  '開立時間': 'Issue timing',
  '如經營主體具備相應資格並選擇電子發票，會在款項完成核對後依實際作業排程開立；目前不代表一定可提供電子發票。送出後五碼只代表已回報，不代表已確認入帳或已完成憑證開立。': 'If the operator is eligible and uses electronic invoices, these will be issued after payment verification according to the processing schedule. This does not currently guarantee electronic invoice availability. Submitting the last five account digits only reports a transfer; it does not confirm payment or issuance of a receipt or invoice.',
  '更正與補充': 'Corrections and additional details',
  '如載具、信箱、統一編號或抬頭有誤，請儘速聯絡好運跑班。已完成申報或超過可更正期限時，將依相關法規與實際作業狀況處理。': 'Contact Nurture Running Team promptly if the carrier, email address, business tax ID, or invoice title is incorrect. Once reporting is complete or the correction deadline has passed, requests will be handled according to applicable rules and processing circumstances.',
  '隱私': 'Privacy',
  '發票與帳務資料只供財務及必要系統作業使用，不會顯示給教練、其他學員或公開頁面。': 'Invoice and accounting information is used only by finance and necessary system processes. It is not shown to coaches, other students, or on public pages.',
}
