// Student and runner-account interface copy. Submitted notes remain in their original language.
export const studentEnglishCopy: Record<string, string> = {
  '帳戶': 'Account',
  '跑者名片': 'Runner profile',
  '完成個人跑者資料，讓教練與跑友更認識你。': 'Complete your runner profile so coaches and teammates can get to know you.',
  '在個人帳戶填寫暱稱、城市與偏好距離。': 'Add your nickname, city, and preferred distance to your account.',
  '初次集結': 'First class',
  '完成第一門好運跑班課程報名。': 'Register for your first Nurture Running Team class.',
  '第一筆課程款項經財務核對並確認後取得。': 'Earned when finance verifies and confirms your first class payment.',
  '訓練': 'Training',
  '訓練回聲': 'Training feedback',
  '送出第一篇完整訓練回饋。': 'Submit your first complete training feedback.',
  '完成第一次訓練回報後取得。': 'Earned after your first training report.',
  '穩定四週': 'Four steady weeks',
  '連續四週留下訓練紀錄。': 'Record training for four consecutive weeks.',
  '連續四週完成訓練回報後取得。': 'Earned after submitting training reports for four consecutive weeks.',
  '里程': 'Distance',
  '百公里累積': '100 kilometres',
  '累積完成 100 公里訓練里程。': 'Complete 100 kilometres of training.',
  '網站訓練里程累積達 100 公里後取得。': 'Earned when your logged training distance reaches 100 kilometres.',
  '賽事': 'Racing',
  '初次完賽': 'First finish',
  '完成第一場正式目標賽事。': 'Complete your first official target race.',
  '提交完賽資料並由管理員確認後取得。': 'Earned after submitting your finish details for administrator confirmation.',
  '突破 PB': 'New personal best',
  '刷新自己的最佳成績。': 'Set a new personal best.',
  '提交新的個人最佳成績並由管理員確認後取得。': 'Earned after submitting your new personal best for administrator confirmation.',
  '社群': 'Community',
  '好運同行': 'Running together',
  '積極參與團練，陪伴夥伴一起進步。': 'Take part in group training and help teammates progress.',
  '由教練或管理員依團隊參與狀況授予。': 'Awarded by a coach or administrator for team participation.',
  '十二週全勤': 'Twelve weeks of attendance',
  '完整參與一個十二週訓練週期。': 'Attend a complete twelve-week training cycle.',
  '完成一期課程全勤並經點名紀錄確認後取得。': 'Earned for full attendance in a course, confirmed by attendance records.',
  '已完成': 'Completed',
  '尚未雙重確認': 'Awaiting both check-in and coach confirmation',
  '讀取課表失敗，請稍後再試。': 'Unable to load the training plan. Try again later.',
  '台灣 +886': 'Taiwan +886',
  '中國 +86': 'China +86',
  '香港 +852': 'Hong Kong +852',
  '澳門 +853': 'Macao +853',
  '美國／加拿大 +1': 'USA / Canada +1',
  '日本 +81': 'Japan +81',
  '桃園市': 'Taoyuan City',
  '苗栗縣': 'Miaoli County',
  '台中市': 'Taichung City',
  '彰化縣': 'Changhua County',
  '南投縣': 'Nantou County',
  '雲林縣': 'Yunlin County',
  '嘉義市': 'Chiayi City',
  '嘉義縣': 'Chiayi County',
  '台南市': 'Tainan City',
  '高雄市': 'Kaohsiung City',
  '屏東縣': 'Pingtung County',
  '宜蘭縣': 'Yilan County',
  '花蓮縣': 'Hualien County',
  '台東縣': 'Taitung County',
  '基隆市': 'Keelung City',
  '澎湖縣': 'Penghu County',
  '金門縣': 'Kinmen County',
  '連江縣': 'Lienchiang County',
  '中國大陸': 'Mainland China',
  '香港': 'Hong Kong',
  '澳門': 'Macao',
  '未滿 6 個月': 'Less than 6 months',
  '6-12 個月': '6–12 months',
  '1-2 年': '1–2 years',
  '3-5 年': '3–5 years',
  '6-10 年': '6–10 years',
  '10 年以上': 'More than 10 years',
  '越野跑': 'Trail running',
  '尚未確定': 'Not decided yet',
  '多項距離': 'Multiple distances',
  '建立規律跑步習慣': 'Build a consistent running habit',
  '完成第一場 5K': 'Complete my first 5K',
  '完成第一場 10K': 'Complete my first 10K',
  '完成第一場半馬': 'Complete my first half marathon',
  '完成第一場全馬': 'Complete my first marathon',
  '突破 5K PB': 'Improve my 5K personal best',
  '突破 10K PB': 'Improve my 10K personal best',
  '突破半馬 PB': 'Improve my half marathon personal best',
  '突破全馬 PB': 'Improve my marathon personal best',
  '健康減脂': 'Healthy fat loss',
  '穩定無傷訓練': 'Train consistently and stay injury-free',
  '2026 TCS 雪梨馬拉松': '2026 TCS Sydney Marathon',
  '2026 BMW 柏林馬拉松': '2026 BMW Berlin Marathon',
  '2026 芝加哥馬拉松': '2026 Chicago Marathon',
  '2026 臺灣國家公園馬拉松－陽明山': '2026 Taiwan National Park Marathon — Yangmingshan',
  '2026 紐約市馬拉松': '2026 New York City Marathon',
  '2026 Garmin Run 臺北站': '2026 Garmin Run Taipei',
  '2026 新竹城市馬拉松': '2026 Hsinchu City Marathon',
  '2026 瓦倫西亞馬拉松': '2026 Valencia Marathon',
  '2026 臺北馬拉松': '2026 Taipei Marathon',
  '2027 金門馬拉松': '2027 Kinmen Marathon',
  '2027 東京馬拉松': '2027 Tokyo Marathon',
  '澳洲雪梨': 'Sydney, Australia',
  '德國柏林': 'Berlin, Germany',
  '美國芝加哥': 'Chicago, USA',
  '美國紐約': 'New York, USA',
  '西班牙瓦倫西亞': 'Valencia, Spain',
  '日本東京': 'Tokyo, Japan',
  '亞洲': 'Asia',
  '大洋洲': 'Oceania',
  '歐洲': 'Europe',
  '北美洲': 'North America',
  '今天開跑': 'Race day',
  '賽事已結束': 'Race finished',
  '待啟用': 'Pending activation',
  '已停用': 'Disabled',
  '設定': 'Settings',
  '好運跑者': 'Nurture runner',
  '教練': 'Coach',
  '請填寫賽事名稱。': 'Enter the race name.',
  '你的匯款資料需要補充或重新核對，請聯絡好運跑班協助處理。': 'Your transfer details need additional information or another review. Contact Nurture Running Team for help.',
  '你的匯款資料已回報，正在等待財務人工核對；確認入帳後將自動開通課表。': 'Your transfer details have been submitted for finance review. Your training plan will become available once payment is confirmed.',
  '到課': 'Present',
  '請假': 'On leave',
  '已扣除': 'Session deducted',
  '登入狀態已失效，請重新登入。': 'Your session has expired. Sign in again.',
  '未點': 'Not recorded',
  '所屬班級：': 'Class: ',
  '狀態': 'Status',
  '已綁定': 'Linked',
  '請重新登入後再修改資料。': 'Sign in again before editing your details.',
  '讀取帳戶資料失敗。': 'Unable to load account details.',
  '請填寫真實姓名。': 'Enter your full name.',
  '儲存帳戶資料失敗。': 'Unable to save account details.',
  '正在讀取跑者資料': 'Loading runner profile',
  '返回跑者名片': 'Back to runner profile',
  '完成後會返回跑者名片展示頁。': 'You will return to your runner profile when finished.',
  '真實姓名': 'Full name',
  '暱稱': 'Nickname',
  '跑友怎麼稱呼你？': 'What should other runners call you?',
  '所在城市': 'City',
  '請選擇': 'Select an option',
  '其他城市': 'Another city',
  '輸入城市': 'Enter a city',
  '跑步年限': 'Years of running',
  '偏好距離': 'Preferred distance',
  '個人最佳 PB': 'Personal best (PB)',
  '請選擇項目': 'Select an event',
  '尚未有正式 PB': 'No official personal best yet',
  '例如 1:45:00': 'For example, 1:45:00',
  '近期跑步目標': 'Current running goal',
  '其他目標': 'Another goal',
  '輸入你的目標': 'Enter your goal',
  '目標賽事': 'Target race',
  '尚未決定': 'Not decided yet',
  '其他賽事': 'Another race',
  '輸入賽事名稱與日期': 'Enter the race name and date',
  '官方資訊': 'Official information',
  '依地區整理全球賽事，只顯示尚未結束的項目；倒數計至賽事日期開始。目錄最後核對於 2026/07/13。': 'Browse upcoming races around the world by region. Countdowns end at the start of the race date. This directory was last checked on July 13, 2026.',
  '名稱或個人頁連結': 'Username or profile link',
  '發票資訊': 'Invoice details',
  '暫不設定': 'Set up later',
  '手機條碼載具': 'Mobile invoice barcode',
  '統一編號': 'Tax ID',
  '8 位統一編號': '8-digit tax ID',
  '這些帳務資料只會在你的登入帳戶與結帳流程中使用，不會顯示給教練或其他會員。': 'These billing details are only used within your account and during checkout. Coaches and other members cannot see them.',
  '跑者自我介紹': 'About you as a runner',
  '分享你的跑步故事': 'Share your running story',
  '取消': 'Cancel',
  '正在儲存': 'Saving',
  '儲存並展示': 'Save and view profile',
  '儲存後會同步更新跑者名片與勳章條件。': 'Saving updates your runner profile and badge eligibility.',
  '開放團練': 'Open group training',
  '請重新登入後再查看帳戶。': 'Sign in again to view your account.',
  '好運會員': 'Nurture member',
  '正在讀取帳戶...': 'Loading account…',
  '寫下你的跑步故事，讓這張跑者名片更像你。': 'Share your running story to make this profile your own.',
  '跑齡': 'Running experience',
  '偏好': 'Preference',
  '尚未選擇目標賽事。': 'No target race selected yet.',
  '聯絡資料': 'Contact details',
  '尚未填寫電話': 'Phone number not provided',
  '尚未填寫 Instagram': 'Instagram not provided',
  '尚未填寫 Facebook': 'Facebook not provided',
  '尚未選擇城市': 'City not selected',
  '尚未設定近期目標': 'No current goal set',
  '教練帳號': 'Coach account',
  '管理員已登記這個信箱；完成信箱驗證並重新登入後，系統會自動啟用教練工作台。': 'An administrator has registered this email. Verify your email and sign in again to activate the coach workspace.',
  '我的點名': 'My attendance',
  '查看到課、請假與本季度補課安排': 'View attendance, leave, and makeup sessions for this season',
  '收合': 'Collapse',
  '展開': 'Expand',
  '查看取得方式': 'View requirements',
  '已獲得': 'Earned',
  '常用入口': 'Quick links',
  '聯絡好運跑班': 'Contact Nurture Running Team',
  '關閉': 'Close',
  '日期待確認': 'Date to be confirmed',
  '普通': 'Average',
  '完成原計畫': 'Completed as planned',
  '好運跑班學員': 'Nurture Running Team student',
  '等待教練同步目標': 'Waiting for your coach to share a goal',
  '待綁定': 'Not linked yet',
  '等待首次回饋': 'Awaiting first feedback',
  '強度偏高': 'High intensity',
  '穩定推進': 'Steady progress',
  '建立節奏': 'Building consistency',
  '先提交一次訓練回饋': 'Submit your first training feedback',
  '請和教練確認恢復': 'Discuss recovery with your coach',
  '關注心率與睡眠': 'Keep an eye on heart rate and sleep',
  '可以按計畫推進': 'Continue with your training plan',
  '完成訓練後提交回饋': 'Submit feedback after training',
  '輕負荷': 'Light load',
  '適中負荷': 'Moderate load',
  '高負荷': 'High load',
  '訓練資料': 'Training data',
  '我的目標': 'My goals',
  '讀取學員資料失敗。': 'Unable to load student details.',
  '請先登入，登入後才能儲存賽事目標。': 'Sign in to save a target race.',
  '學員已中籤，加入目標賽事面板。': 'Race entry confirmed. Added to target races.',
  '已加入你的目標賽事面板。': 'Added to your target races.',
  '儲存賽事失敗，請稍後再試。': 'Unable to save the race. Try again later.',
  '已從面板移除該賽事。': 'Race removed from your dashboard.',
  '移除賽事失敗，請稍後再試。': 'Unable to remove the race. Try again later.',
  '請先登入，登入後回饋才會同步到教練端。': 'Sign in so your feedback can be shared with your coach.',
  '疼痛 / 不適位置：無明顯不適': 'Pain or discomfort: none reported',
  '提交失敗，請稍後再試。': 'Unable to submit. Try again later.',
  '請先登入，登入後才能儲存資料。': 'Sign in to save your details.',
  'Supabase 尚未設定，暫時無法儲存資料。': 'The account service is not configured. Your details cannot be saved yet.',
  '請先重新登入後再儲存資料。': 'Sign in again before saving your details.',
  '儲存失敗，請稍後再試。': 'Unable to save. Try again later.',
  '資料已更新。': 'Details updated.',
  '，這裡改為教練工作視角。': ', this is your coach workspace.',
  '你的帳號已經啟用教練權限，因此不再顯示學員的訓練感受表單。接下來的重點會放在學員狀態、課表同步與回饋處理。': 'Your coach access is active. This workspace focuses on student progress, training plans, and feedback instead of the student feedback form.',
  '目前身份': 'Current role',
  '可管理綁定學員與訓練課表': 'Manage linked students and training plans',
  '集中查看學員回饋、權限狀態與今日待處理事項。': 'Review student feedback, access status, and tasks for today in one place.',
  '學員狀態': 'Student status',
  '綁定學員後，查看目標、PB、班級與後續回饋狀態。': 'After linking students, view their goals, personal bests, classes, and feedback status.',
  '進入課表面板，儲存後寫入 training_plans 並同步到學員端。': 'Open the training planner. Saved plans are shared with your students.',
  '進入': 'Open',
  '目前沒有已確認入帳的開課中或招生中季度報名。請先選擇課程，完成匯款核對後即會建立正式班級資格。': 'You have no confirmed paid enrollment for an active or enrolling season. Choose a class; membership will become active once your transfer is verified.',
  '請完成匯款並回報後五碼；財務確認入帳後將自動開通課表。': 'Complete your transfer and report the last five account digits. Your training plan will become available after finance confirms payment.',
  '尚無正式課程資格': 'No active class membership',
  '報名審核': 'Enrollment review',
  '課表等待開通': 'Training plan access pending',
  '課表訪問': 'Training plan access',
  '確認後開通': 'Available after confirmation',
  '確認後可提交': 'Submissions open after confirmation',
  '查看匯款狀態': 'View transfer status',
  '，今天照顾好這一課。': ', make today’s training count.',
  '課表、完成狀態與訓練感受都集中在這裡。回報越清楚，教練越能幫你把下一週調得剛剛好。': 'Find your plan, completion status, and training feedback here. Clear feedback helps your coach adapt next week’s training to you.',
  '目前真實資料讀取失敗，請稍後再試。資訊：': 'Unable to load your data. Try again later. Details: ',
  '學員看板功能': 'Student dashboard features',
  '用訓練負荷、完成率和體感趨勢，快速判斷這一週該推進、維持還是先恢復。': 'Use training load, completion, and effort trends to decide whether to progress, maintain, or recover this week.',
  '去回報': 'Submit feedback',
  '目前訓練狀態': 'Current training status',
  '負荷': 'Load',
  '完成率': 'Completion rate',
  '平均 RPE': 'Average RPE',
  '近期里程': 'Recent distance',
  '先提交訓練回饋': 'Submit training feedback first',
  '平均心率': 'Average heart rate',
  '回饋時可填寫': 'Add this when submitting feedback',
  '來自已填寫記錄': 'From submitted records',
  '課表完成': 'Plan completion',
  '待同步': 'Awaiting update',
  '按訓練回饋匹配課表': 'Matched to plans using training feedback',
  '強度指數': 'Intensity index',
  '提交 RPE 後生成': 'Available after submitting RPE',
  '由 RPE 換算': 'Calculated from RPE',
  '近 7 次訓練負荷': 'Load over your last 7 sessions',
  '里程 × RPE，用來觀察疲勞趨勢': 'Distance × RPE, to track fatigue trends',
  '次': 'sessions',
  '還沒有負荷趨勢': 'No load trend yet',
  '提交訓練回饋後，這裡會自動生成趨勢。': 'Your trend will appear here after you submit training feedback.',
  '強度分布': 'Intensity distribution',
  '輕鬆 / 恢復': 'Easy / Recovery',
  '節奏 / 穩態': 'Tempo / Steady',
  '高強度': 'High intensity',
  '最近一次回饋': 'Latest feedback',
  '還沒有訓練回饋，完成一次訓練後從下方提交即可。': 'No training feedback yet. Submit the form below after your next session.',
  '教練已看': 'Seen by coach',
  '等待教練查看': 'Awaiting coach review',
  '待開始': 'Not started',
  '已同步': 'Updated',
  '配速由教練視狀態調整': 'Your coach will adjust the pace to your condition',
  '完成後請回報 RPE、實際里程、心率與感受。': 'After training, report your RPE, distance, heart rate, and how you felt.',
  '同步中': 'Updating',
  '尚未同步課表': 'No training plan shared yet',
  '教練已綁定，課表尚未同步。請等待教練派發本週課表，你仍然可以提交自主訓練回饋。': 'Your coach is linked but has not shared this week’s plan yet. You can still submit feedback for independent training.',
  '如已報名但看不到資料，請用報名信箱登入，並聯絡教練確認帳號綁定。你仍然可以提交自主訓練回饋。': 'If you have registered but cannot see your details, sign in with your registration email and ask your coach to check the account link. You can still submit independent training feedback.',
  '提交自主訓練回饋': 'Submit independent training feedback',
  '訓練類型': 'Training type',
  '本週訓練': 'This week’s training',
  '自主回饋': 'Independent training feedback',
  '我的目標賽事': 'My target races',
  '中籤後把賽事加入面板，教練之後可以围绕目標比賽調整訓練節奏。': 'Add races once your entry is confirmed so your coach can plan training around them.',
  '距離待確認': 'Distance to be confirmed',
  '移除賽事': 'Remove race',
  '已中籤': 'Entry confirmed',
  '還沒有目標賽事': 'No target races yet',
  '選擇一個全球賽事，或手動輸入你已中籤的比賽。': 'Choose a race from the directory or enter a race you have a confirmed place in.',
  '選擇賽事': 'Choose a race',
  '自定义其他賽事': 'Add a custom race',
  '添加中...': 'Adding…',
  '加入面板': 'Add to dashboard',
  '賽事名稱': 'Race name',
  '距離': 'Distance',
  '國家 / 地區': 'Country / Region',
  '橫向滑動查看': 'Swipe horizontally to view',
  '如果你已經報名，請先確認登入的是報名信箱；仍看不到資料時，請聯絡教練綁定帳號。你仍然可以提交自主訓練回饋。': 'If you have registered, check that you signed in with your registration email. If details are still missing, contact your coach to link the account. You can still submit independent training feedback.',
  '完成後回報': 'Report after training',
  '今日訓練感受': 'Today’s training feedback',
  '請先登入報名信箱。登入後提交的訓練回饋才會同步給教練。': 'Sign in with your registration email so submitted feedback can be shared with your coach.',
  '實際里程': 'Distance completed',
  '填寫實際里程': 'Enter distance completed',
  '完成時間': 'Duration',
  '填寫完成時間': 'Enter duration',
  '平均配速': 'Average pace',
  '填寫平均配速': 'Enter average pace',
  '填寫平均心率': 'Enter average heart rate',
  'RPE 體感強度：': 'Perceived exertion (RPE): ',
  '很輕鬆': 'Very easy',
  '剛剛好': 'Moderate',
  '非常吃力': 'Very hard',
  '睡眠質量': 'Sleep quality',
  '很好': 'Very good',
  '偏差': 'Below average',
  '很差': 'Very poor',
  '疲勞程度': 'Fatigue level',
  '輕鬆': 'Fresh',
  '偏疲勞': 'Somewhat fatigued',
  '非常疲勞': 'Very fatigued',
  '是否完成原計畫': 'Did you complete the original plan?',
  '部分完成': 'Partially completed',
  '改為輕鬆跑': 'Changed to an easy run',
  '未完成 / 休息': 'Not completed / Rest',
  '疼痛 / 不適位置': 'Pain or discomfort location',
  '例如：右小腿、左膝；沒有可留空': 'For example: right calf or left knee. Leave blank if none.',
  '訓練感受': 'How did training feel?',
  '填寫訓練感受': 'Describe how training felt',
  '例如：今天臨時加班、天氣很熱、補給不足等': 'For example: unexpected overtime, hot weather, or insufficient fuel',
  '上傳跑步截圖': 'Add a running screenshot',
  '第一版先記錄截圖檔案名；後續可接圖片上傳與自動識別里程、配速、心率。': 'Currently, only the screenshot filename is saved. Image upload and automatic reading of distance, pace, and heart rate are not available yet.',
  '已提交。教練端的「今日待處理」會看到這筆回饋，並依照 RPE 與感受調整下一次課表。': 'Submitted. Your coach will see this feedback in today’s tasks and can use your RPE and comments to adjust the next session.',
  '提交中...': 'Submitting…',
  '提交給教練': 'Submit to coach',
  '這裡只放影响訓練溝通的資料，儲存後會同步給教練端查看。': 'These details help you communicate about training. Saved changes are shared with your coach.',
  '關闭設定': 'Close settings',
  '登入信箱：': 'Sign-in email: ',
  '你的稱呼': 'Your name',
  '手機 / 聯絡方式': 'Phone / Contact details',
  '方便教練聯絡': 'How your coach can reach you',
  '儲存中...': 'Saving…',
  '儲存設定': 'Save settings',
  '讀取測試簽到狀態失敗。': 'Unable to load test check-in status.',
  '測試簽到失敗。': 'Test check-in failed.',
  '現在可以簽到': 'Check-in is open',
  '尚未開放': 'Not open yet',
  '測試時段已結束': 'Test period ended',
  '7 月 25 日網站驗收': 'July 25 website acceptance test',
  '教練本人測試簽到': 'Coach test check-in',
  '學員自主測試簽到': 'Student test check-in',
  '只寫入驗收測試紀錄，不計入正式出勤、點名、課酬或季度統計。': 'This creates a test record only. It does not affect official attendance, payroll, or season totals.',
  '處理中': 'Processing',
  '已完成測試簽到': 'Test check-in complete',
  '立即測試簽到': 'Test check-in now',
  '等待開放': 'Waiting to open',
  '讀取點名表失敗。': 'Unable to load attendance.',
  '點名操作失敗。': 'Unable to update attendance.',
  '點名資料已更新。': 'Attendance updated.',
  '本堂停課': 'Session cancelled',
  '學員自主簽到與教練現場點名分別記錄。開課前後各 15 分鐘開放簽到。': 'Student check-in and coach attendance are recorded separately. Check-in opens 15 minutes before class and closes 15 minutes after it starts.',
  '正在簽到…': 'Checking in…',
  '我已到場，簽到': 'I’m here — check in',
  '正在讀取本季度點名表': 'Loading this season’s attendance',
  '本季度': 'This season',
  '我的點名表': 'My attendance record',
  '查看季度': 'View season',
  '學員點名季度': 'Student attendance season',
  '查看自己的到課紀錄；只能為最近一堂課請假，補課則可選擇原課次之後、本季度內其他班級的可用課次。': 'View your attendance. Leave can only be requested for the next eligible session. Makeup sessions can be chosen from available classes later than the original session within the same season.',
  '目前沒有以此登入信箱核准的本季度課程。': 'There are no approved classes for this season under your sign-in email.',
  '如報名使用其他信箱，請聯絡管理員協助確認。': 'If you registered with another email, contact an administrator for help.',
  '停課': 'Cancelled',
  '本堂停課，不需要請假或扣除課次。': 'This session is cancelled. No leave request or session deduction is needed.',
  '補課簽到 ·': 'Makeup check-in ·',
  '補課安排：': 'Makeup session: ',
  '補課已完成：': 'Makeup completed: ',
  '本次補課資格已結束。': 'This makeup entitlement has ended.',
  '原補課課次已停課，請重新選擇本季度其他課次。': 'The selected makeup session was cancelled. Choose another session this season.',
  '請假已成立，尚未選擇補課課次。': 'Your leave is recorded. No makeup session has been selected yet.',
  '選擇原課次之後、本季度其他班級的補課課次': 'Choose a later makeup session in another class this season',
  '請選擇課次': 'Choose a session',
  '目前沒有原課次之後、尚未開始且未額滿的本季度補課課次，稍後可再回來查看。': 'No later makeup sessions with available places are currently open this season. Check again later.',
  '確認補課': 'Confirm makeup session',
  '更換補課': 'Change makeup session',
  '選擇補課': 'Choose makeup session',
  '取消補課': 'Cancel makeup session',
  '取消請假': 'Cancel leave',
  '我的任課教練': 'My class coaches',
  '尚無已入帳班級的教練關聯': 'No coaches linked to a confirmed paid class yet',
  '確認課程入帳後，依季度與報名班級自動關聯教練。跨班補課只開放該堂點名，不會更換原班教練。': 'Coaches are linked automatically by season and class once payment is confirmed. A makeup session in another class only grants attendance access for that session; it does not change your regular coach.',
  '讀取訓練日志失敗。': 'Unable to load the training log.',
  '請先登入，登入後才能提交訓練回饋。': 'Sign in to submit training feedback.',
  '提交訓練回饋失敗，請稍後再試。': 'Unable to submit training feedback. Try again later.',
  '訓練日志系統': 'Training log',
  '這裡會同步教練派發的真實課表；課表清空或尚未派發時顯示空狀態。': 'Training plans shared by your coach appear here. This area is empty when no plan has been assigned.',
  '尚未同步': 'Not shared yet',
  '今日訓練計畫': 'Today’s training plan',
  '目標配速': 'Target pace',
  '由教練調整': 'Set by your coach',
  '週數': 'Week',
  '完成訓練後，請在右側提交回饋。': 'Submit your feedback after completing the session.',
  '正在同步課表': 'Loading training plan',
  '目前沒有已同步課表': 'No training plan shared yet',
  '教練重新派發課表後，這裡會自動顯示真實訓練內容。': 'Your training plan will appear here when your coach shares it.',
  '完成里程 (km)': 'Distance completed (km)',
  '填寫完成里程': 'Enter distance completed',
  '體感疲勞度 (RPE 1-10):': 'Perceived exertion (RPE 1–10):',
  '非常輕鬆': 'Very easy',
  '中等': 'Moderate',
  '非常困難': 'Very hard',
  '訓練感受與備註': 'Training feedback and notes',
  '請描述今天的訓練感受...': 'Describe how today’s training felt…',
  '提交訓練回饋': 'Submit training feedback',
  '最近完成訓練': 'Recently completed training',
  '配速：': 'Pace: ',
  '心率：': 'Heart rate: ',
  '還沒有完成記錄': 'No completed sessions yet',
  '提交第一次真實回饋後，這裡會顯示最近訓練。': 'Recent sessions will appear here after you submit your first feedback.',
  '訓練回饋已提交，教練端會同步看到。': 'Training feedback submitted and shared with your coach.',
}
