// Complete interface copy for content and season editors. Editable values stay unchanged.
export const adminContentEnglishCopy: Record<string, string> = {
  '更換圖片': 'Replace image',
  '全站': 'Whole site',
  '切換、複製與歷史資料': 'Switch, duplicate and view history',
  '課程、日程表、報名與歷史報表': 'Classes, schedule, enrollment and historical reports',
  '課程資料': 'Class details',
  '班級日期與內容': 'Class dates and content',
  '首頁、日程表、課程詳情與網站報名表': 'Homepage, schedule, class details and registration forms',
  '儲存並發布': 'Save and publish',
  '向前移動': 'Move earlier',
  '向後移動': 'Move later',
  '刪除圖片': 'Delete image',
  '刪除': 'Delete',
  '編輯': 'Edit',
  '新增': 'Add',
  '課程名稱': 'Class name',
  '訓練方向': 'Training focus',
  '草稿': 'Draft',
  '進行中': 'In progress',
  '圖片服務尚未設定。': 'Image uploads are not configured.',
  '影片服務尚未設定。': 'Video uploads are not configured.',
  '無法建立影片上傳憑證。': 'Unable to prepare the video upload.',
  '影片上傳失敗。': 'Video upload failed.',
  '課程顯示預覽': 'Class display preview',
  '尚未設定圖片': 'No image set',
  '將臉部置於圓框中央，保留頭頂與下巴，避免裁入手臂。': 'Center the face in the circle, keeping the top of the head and chin visible. Keep arms outside the crop.',
  '尚未設定影片；沒有影片時，前台不會保留空白區塊。': 'No video set. The public page hides this section when no video is available.',
  '貼上 YouTube 網址，或使用下方按鈕上傳影片': 'Paste a YouTube URL or upload a video below',
  '更換影片': 'Replace video',
  '上傳影片': 'Upload video',
  '移除影片': 'Remove video',
  '支援 YouTube、MP4、WebM、MOV；上傳影片最大 50 MB。': 'Supports YouTube, MP4, WebM and MOV. Upload limit: 50 MB.',
  '首頁與活動': 'Homepage and activities',
  '公開頁面': 'Public pages',
  '全站設定': 'Site settings',
  '季度與課程': 'Seasons and classes',
  '請選擇正確的上課星期。': 'Choose a valid class weekday.',
  '上課時間請包含 24 小時制時間，例如 19:27（1.5-2 小時）。': 'Include a 24-hour class time, for example 19:27 (1.5–2 hours).',
  '請設定教練簽到使用的課程開始時間，例如 19:30。': 'Set the class start time used for coach check-in, for example 19:30.',
  '班級名額請設定為 1 至 500 之間。': 'Set class capacity between 1 and 500.',
  '請至少選擇一位本課程教練。': 'Choose at least one coach for this class.',
  '前台招生季度必須先完成實際收費課次設定。': 'Configure billable session dates before publishing the enrollment season.',
  '已發布至訓練課程、訓練日程表、課程詳情與報名頁。': 'Published to classes, the schedule, class details and registration pages.',
  '請填寫新課程名稱並選擇介紹版型。': 'Enter a new class name and choose a description template.',
  '請填寫報名計價設定。': 'Complete the enrollment pricing settings.',
  '請填寫實際收費課次日期。': 'Enter the billable session dates.',
  '收費日期必須是真實日期，格式為 YYYY-MM-DD；請修正後再儲存。': 'Session dates must be valid dates in YYYY-MM-DD format. Correct them before saving.',
  '價格必須是 0 至 1,000,000 之間的整數。': 'Prices must be whole numbers between 0 and 1,000,000.',
  '全期收費截止堂次必須介於 1 至 20 堂。': 'The full-season price cutoff must be between sessions 1 and 20.',
  '報價保留時數必須介於 1 至 168 小時。': 'The price lock must be between 1 and 168 hours.',
  '還原未儲存變更': 'Restore saved version',
  '查看前台': 'View public page',
  '返回季度列表': 'Back to seasons',
  '返回學員與統計': 'Back to students and statistics',
  '目前顯示：': 'Currently showing: ',
  '有尚未儲存的內容；切換內容區塊會保留草稿，離開工作區前請先儲存。': 'You have unsaved content. Drafts are kept when switching sections; save before leaving this workspace.',
  '首頁輪播圖片': 'Homepage slideshow images',
  '最多 8 張，可調整順序或刪除。建議使用橫式高解析度照片。': 'Add up to 8 images, reorder or remove them. Use high-resolution landscape photos.',
  '圖片上傳中...': 'Uploading image…',
  '新增輪播圖片': 'Add slideshow image',
  '儲存輪播': 'Save slideshow',
  '管理近期報名與課程預覽的標題及說明；首頁順序固定為近期報名、課程預覽。': 'Edit registration and class preview headings and descriptions. Registration appears before class previews on the homepage.',
  '首頁課程預覽背景圖': 'Homepage class preview background',
  '近期報名小標': 'Registration eyebrow',
  '近期報名標題': 'Registration heading',
  '近期報名說明': 'Registration description',
  '課程預覽小標': 'Class preview eyebrow',
  '課程預覽標題': 'Class preview heading',
  '課程預覽說明': 'Class preview description',
  '課程預覽按鈕': 'Class preview button',
  '管理完整課程頁的首屏與加入課程四步驟；班級資料仍由季度管理維護。': 'Edit the class page hero and four enrollment steps. Manage individual classes in Seasons.',
  '訓練日程首屏背景圖': 'Schedule hero background',
  '首屏小標': 'Hero eyebrow',
  '首屏標題': 'Hero heading',
  '首屏說明': 'Hero description',
  '加入流程小標': 'Enrollment steps eyebrow',
  '加入流程標題': 'Enrollment steps heading',
  '四個加入步驟': 'Four enrollment steps',
  '常見問題標題': 'FAQ heading',
  '常見問題內容': 'FAQ entries',
  '問題': 'Question',
  '回答': 'Answer',
  '課表下方三項重點': 'Three highlights below the schedule',
  '重點標題': 'Highlight heading',
  '重點說明': 'Highlight description',
  '首頁活動入口': 'Homepage activity links',
  '新增活動、報名頁或外部連結，首頁會依順序顯示。': 'Add activities, registration pages or external links. They appear in this order on the homepage.',
  '活動名稱': 'Activity name',
  '按鈕文字（選填）': 'Button text (optional)',
  '活動說明': 'Activity description',
  '連結（選填，留空即為公告）': 'Link (optional; leave empty for an announcement)',
  '刪除活動': 'Delete activity',
  '新增活動': 'Add activity',
  '發布活動入口': 'Publish activity links',
  '編輯課程教練頭像與裁切': 'Edit and crop class coach photos',
  '團隊陣容頁面介紹': 'Team page introduction',
  '管理首屏介紹與教練名單上方標題。': 'Edit the hero introduction and coach roster heading.',
  '教練團隊首屏背景圖': 'Team hero background',
  '名單小標': 'Roster eyebrow',
  '名單標題': 'Roster heading',
  '教練照片與公開資料': 'Coach photos and public profiles',
  '課程頭像與團隊照片分開維護。更換後請按「儲存並發布教練資料」，同一位教練的所有課程會同步更新；課程歸屬仍在季度管理設定。': 'Class avatars and team photos are managed separately. Save and publish the profile to update every class featuring this coach. Assign class coaches in Seasons.',
  '拖動把手或使用上下箭頭調整順序，然後儲存排序。只影響團隊陣容，不改變課程歸屬。': 'Drag the handle or use the arrows, then save the order. This changes the team roster order, not class assignments.',
  '儲存教練排序': 'Save coach order',
  '前台顯示中': 'Published',
  '前台隱藏': 'Hidden',
  '尚未填寫職務': 'No role entered',
  '課程詳情頭像（1:1，臉部近景）': 'Class avatar (1:1, face close-up)',
  '上傳高清頭像並裁切': 'Upload and crop avatar',
  '建議使用 1200 × 1200 px 以上的清晰原圖。支援 JPG、PNG、WebP；可調整縮放與位置，裁切後不再二次放大。': 'Use a clear original image of at least 1200 × 1200 px. Supports JPG, PNG and WebP. Adjust zoom and position; the crop will not be enlarged again.',
  '團隊頁照片（3:2，上半身／人物照）': 'Team photo (3:2, upper body or portrait)',
  '公開姓名': 'Public name',
  '暱稱': 'Nickname',
  '職務與專長': 'Role and expertise',
  '公開介紹': 'Public biography',
  '教學專長（每行一項）': 'Coaching specialties (one per line)',
  '帶訓風格': 'Coaching style',
  '代表經歷（每行一項）': 'Experience (one per line)',
  '教練證照（每行一項）': 'Coaching certifications (one per line)',
  '在團隊陣容與課程教練選單顯示': 'Show in the team roster and class coach selector',
  '儲存並發布教練資料': 'Save and publish coach profile',
  '頁尾 Logo、品牌文字與聯絡資料會同步到前台；頂部 Logo 依星期自動更換。': 'Footer logo, brand copy and contact details update the public site. The header logo changes automatically by weekday.',
  '頁尾品牌 Logo': 'Footer brand logo',
  '品牌名稱': 'Brand name',
  '品牌標語': 'Brand tagline',
  'Instagram 網址': 'Instagram URL',
  'Instagram 帳號': 'Instagram handle',
  '聯絡說明': 'Contact description',
  '服務地區': 'Service area',
  '頁尾品牌介紹': 'Footer brand description',
  '管理商店與週年活動目前實際使用的圖片與商店文案。': 'Edit images used on the shop and anniversary pages, and shop copy.',
  '商店主視覺': 'Shop hero image',
  '週年活動主圖': 'Anniversary hero image',
  '商店標題': 'Shop heading',
  '商店說明': 'Shop description',
  '管理目前前台實際顯示的首屏、三項理念、服務重點與下方品牌故事。': 'Edit the public hero, three training principles, service highlights and brand story.',
  '首屏': 'Hero',
  '首屏跑道背景圖': 'Hero track background',
  '英文主句': 'English headline',
  '中文主句': 'Chinese headline',
  '三項訓練理念': 'Three training principles',
  '理念標題': 'Principle heading',
  '英文短句': 'English phrase',
  '理念說明': 'Principle description',
  '三項服務重點': 'Three service highlights',
  '下方品牌故事': 'Brand story section',
  '品牌故事背景圖': 'Brand story background',
  '故事小標': 'Story eyebrow',
  '故事標題': 'Story heading',
  '故事標題重點': 'Story heading emphasis',
  '品牌介紹': 'Brand description',
  '首屏、影片、成長路徑主視覺與三段路徑內容集中在這裡；沒有影片時前台會自動收合。': 'Edit the hero, video, journey image and three journey stages. The video section is hidden when no video is set.',
  '學員見證首屏背景圖': 'Testimonials hero background',
  '成長路徑主視覺': 'Journey hero image',
  '學員見證影片': 'Testimonials video',
  '在學員見證頁顯示影片': 'Show video on the testimonials page',
  '影片標題': 'Video heading',
  '影片說明': 'Video description',
  '成長路徑小標': 'Journey eyebrow',
  '成長路徑標題': 'Journey heading',
  '成長路徑說明': 'Journey description',
  '主視覺內的三段成長路徑': 'Three journey stages in the hero image',
  '管理榮耀徽章頁面目前使用的主視覺、系列文案、紀念卡與申請說明。': 'Edit achievement hero images, collection copy, milestone cards and application instructions.',
  '首屏與起源': 'Hero and origin',
  '榮耀徽章首屏圖片': 'Achievements hero image',
  'THE ORIGIN 圖片': 'THE ORIGIN image',
  '首屏標題（可用換行）': 'Hero heading (line breaks allowed)',
  '首屏短句': 'Hero strapline',
  '起源小標': 'Origin eyebrow',
  '起源標題': 'Origin heading',
  '系列小標': 'Collection eyebrow',
  '系列標題': 'Collection heading',
  '系列說明': 'Collection description',
  '起源段落（每行一段）': 'Origin paragraphs (one per line)',
  '全系列五款徽章': 'Five-badge collection',
  '達標標準': 'Qualifying standard',
  '徽章名稱': 'Badge name',
  '設計說明': 'Design description',
  '象徵故事': 'Symbolism and story',
  'BQ Pride 與紀念卡': 'BQ Pride and milestone cards',
  'BQ Pride 主圖': 'BQ Pride main image',
  '如何取得主圖': 'How to apply main image',
  'BQ 小標': 'BQ eyebrow',
  'BQ 標題': 'BQ heading',
  'BQ 副標': 'BQ subheading',
  'BQ 說明': 'BQ description',
  'BQ 申請資格': 'BQ eligibility',
  '紀念卡小標': 'Milestone card eyebrow',
  '紀念卡標題': 'Milestone card heading',
  '紀念卡說明': 'Milestone card description',
  '申請方式小標': 'Application eyebrow',
  '申請方式標題': 'Application heading',
  '核對標題': 'Verification heading',
  '核對說明': 'Verification description',
  '帳戶區標題': 'Account section heading',
  '帳戶區說明': 'Account section description',
  '帳戶按鈕文字': 'Account button text',
  '申請步驟（每行一項）': 'Application steps (one per line)',
  '申請補充說明': 'Additional application notes',
  '管理週年活動頁目前展示的文案與意向表單提示；活動報名資料仍由既有表單流程處理。': 'Edit anniversary page copy and interest form prompts. Registrations continue through the existing form.',
  '活動小標': 'Activity eyebrow',
  '活動標題': 'Activity heading',
  '活動狀態': 'Activity status',
  '狀態小標': 'Status eyebrow',
  '狀態說明': 'Status description',
  '返回按鈕': 'Back button',
  'Instagram 按鈕': 'Instagram button',
  '查看課程按鈕': 'View classes button',
  '表單小標': 'Form eyebrow',
  '表單標題': 'Form heading',
  '表單說明': 'Form description',
  '同行人數欄位': 'Companion count field',
  '亮點（每行一項）': 'Highlights (one per line)',
  '同行人數選項（每行一項）': 'Companion count options (one per line)',
  '每一季獨立保留課程與報名資料。複製下一季後可先編輯草稿，確認後再切換前台。': 'Each season keeps its own classes and registrations. Duplicate the next season, edit its draft, then publish it when ready.',
  '作為複製來源的季度': 'Source season to duplicate',
  '複製建立下一季': 'Duplicate into next season',
  '前台招生季度': 'Published enrollment season',
  '報名記錄': 'Registrations',
  '已回報，待人工核對': 'Reported; awaiting manual review',
  '管理這季課程': 'Manage season classes',
  '設為前台招生': 'Publish for enrollment',
  '僅可刪除非招生中、非進行中且無營運紀錄的季度；有紀錄請封存': 'Only seasons that are not enrolling or active and have no operational records can be deleted. Archive seasons with records.',
  '刪除季度': 'Delete season',
  '儲存後會同步發布到首頁、訓練課程、日程表、課程詳情與報名頁。': 'Saving publishes to the homepage, classes, schedule, class details and registration pages.',
  '封存季度僅供查閱，不再接受修改。': 'Archived seasons are read-only.',
  '這是非當前季度，儲存只會更新這一季，不影響前台。': 'This season is not currently published. Saving updates only this season, not the public site.',
  '管理季度': 'Season to manage',
  '這一季的課程': 'Classes in this season',
  '尚未建立課程': 'No classes created yet',
  '（前台招生）': '(Published for enrollment)',
  '新課程名稱': 'New class name',
  '例如 2026 好運跑步訓練營 X 週一台北夜跑班': 'For example, 2026 Nurture Running · Monday Taipei Evening Class',
  '介紹版型': 'Description template',
  '建立課程': 'Create class',
  '版型只繼承課程介紹架構；名稱、星期、城市、日期、教練、名額與價格都可獨立修改。新課程完成設定前預設不對外顯示。': 'Templates provide the description structure. Edit the name, weekday, city, dates, coaches, capacity and price independently. New classes stay hidden until configured.',
  '此季度已封存，課程與報名資料僅供查閱，已停止同步與修改。': 'This season is archived. Classes and registrations are read-only; synchronization and editing are disabled.',
  '星期': 'Weekday',
  '請選擇星期': 'Choose a weekday',
  '城市 / 地點': 'City / location',
  '課程週期': 'Class date range',
  '例如 7/14 - 9/29': 'For example, 7/14–9/29',
  '例如 19:27（1.5-2 小時）': 'For example, 19:27 (1.5–2 hours)',
  '簽到判定開始時間': 'Start time for check-in',
  '班級名額': 'Class capacity',
  '官網課程介紹文案': 'Public class description',
  '季度英文小標（留白則依季度自動更新）': 'Season English eyebrow (leave blank for automatic)',
  '課程主標語': 'Class headline',
  '本期訓練重點（每行一項，最多三項）': 'Training highlights (one per line, up to three)',
  '開班提醒': 'Class opening notice',
  '沒有提醒時可留空': 'Leave blank if no notice is needed',
  '以上文案與課程名稱、適合對象會同步到本班課程詳情頂部。儲存當前招生季度後即可在前台查看。': 'This copy, the class name and audience appear at the top of the class details page. Save the enrollment season to view the changes publicly.',
  '報名計價設定': 'Enrollment pricing',
  '實際收費課次會直接決定插班堂數；課程開始後，學員必須選擇本期計費起始課次。': 'Billable session dates determine late-entry session counts. Once classes begin, students must select their first billable session.',
  '依課程週期重建日期': 'Rebuild dates from class range',
  '實際收費課次日期（每行一個 YYYY-MM-DD）': 'Billable session dates (one YYYY-MM-DD per line)',
  '舊生整季價格': 'Returning student full-season price',
  '新生整季價格': 'New student full-season price',
  '舊生插班每堂': 'Returning student late-entry rate',
  '有推薦人插班每堂': 'Referred student late-entry rate',
  '無推薦人插班每堂': 'Standard late-entry rate',
  '全期收費截止堂次': 'Full-season price cutoff session',
  '從此堂次（含）之前開始上課採整季價格，之後依插班每堂價格計費。': 'Starting on or before this session uses the full-season price. Later starts use the per-session late-entry rate.',
  '報價保留時數': 'Price lock (hours)',
  '啟用本班自動計價': 'Enable automatic pricing for this class',
  '本課程教練': 'Class coaches',
  '只在這裡設定課程歸屬；教練照片、姓名、經歷與課程介紹均由超級管理員統一維護。': 'Set class assignments here. The super administrator manages coach photos, names, experience and class descriptions.',
  '報名方式：網站內建報名表': 'Registration: website form',
  '發布後，「立即報名」會進入本課程的網站報名頁，不再使用 Google 表單。': 'After publishing, Register opens this class’s website registration page instead of Google Forms.',
  '這門課程對外顯示': 'Show this class publicly',
  '儲存並發布至課程與日程表': 'Save and publish class and schedule',
  '儲存這季課程': 'Save season class',
  '這一季尚未建立課程': 'No classes in this season yet',
  '點擊上方「新增」，即可從介紹版型建立全新的班級。': 'Choose Add above to create a class from a description template.',
}
