export type FeedbackStatus = 'new' | 'flagged' | 'reviewed' | 'missing'

export const studentProfile = {
  name: '林品安',
  program: '台北 PB 班',
  goal: '2026 台北半馬 sub 1:40',
  currentWeek: 4,
  coach: '好運教練團',
}

export const weeklyWorkouts = [
  {
    date: '2026/5/20',
    week: 4,
    day: '週三',
    title: '節奏跑',
    target: '2km E + 5km T + 1km E',
    pace: 'T 配速 4:45-4:55/km',
    note: '如果前一天睡眠不足，T 段改成 3km。',
    status: '今日',
  },
  {
    date: '2026/5/22',
    week: 4,
    day: '週五',
    title: '恢復跑',
    target: 'E 跑 8km',
    pace: '5:45-6:20/km',
    note: '重點是放鬆，不追配速。',
    status: '待完成',
  },
  {
    date: '2026/5/24',
    week: 4,
    day: '週日',
    title: '長距離',
    target: '18km progressive',
    pace: '後 5km 稍微加速',
    note: '跑後補水與碳水，回報腿部疲勞。',
    status: '待完成',
  },
]

export const feedbackQueue = [
  {
    id: 'fb-1',
    student: '林品安',
    program: '台北 PB 班',
    workout: '2km E + 5km T + 1km E',
    submittedAt: '今天 21:18',
    distance: '8.2km',
    pace: '5:03/km',
    heartRate: '158',
    rpe: 8,
    feeling: 'T 段最後 1km 明顯喘，右小腿有一點緊，但沒有痛。',
    status: 'flagged' as FeedbackStatus,
  },
  {
    id: 'fb-2',
    student: '陳又廷',
    program: '竹北夜跑班',
    workout: 'E 跑 10km',
    submittedAt: '今天 20:44',
    distance: '10.0km',
    pace: '6:02/km',
    heartRate: '142',
    rpe: 5,
    feeling: '今天狀態穩，前半段有點悶熱，後面節奏順。',
    status: 'new' as FeedbackStatus,
  },
  {
    id: 'fb-3',
    student: '黃子晴',
    program: '初心補習班',
    workout: '跑走 40 分鐘',
    submittedAt: '昨天 22:05',
    distance: '5.1km',
    pace: '7:50/km',
    heartRate: '136',
    rpe: 4,
    feeling: '比上週輕鬆，可以連續跑比較久了。',
    status: 'reviewed' as FeedbackStatus,
  },
]

export const coachStudents = [
  {
    id: 'stu-1',
    name: '林品安',
    program: '台北 PB 班',
    goal: '半馬 sub 1:40',
    week: 4,
    lastFeedback: '今天 21:18',
    readiness: '需調整',
    risk: '右小腿緊繃',
    nextWorkout: '恢復跑 8km',
  },
  {
    id: 'stu-2',
    name: '陳又廷',
    program: '竹北夜跑班',
    goal: '全馬完賽',
    week: 7,
    lastFeedback: '今天 20:44',
    readiness: '穩定',
    risk: '無明顯異常',
    nextWorkout: '坡跑 10 組',
  },
  {
    id: 'stu-3',
    name: '黃子晴',
    program: '初心補習班',
    goal: '養成跑步習慣',
    week: 2,
    lastFeedback: '昨天 22:05',
    readiness: '進步中',
    risk: '注意睡眠',
    nextWorkout: '跑走 45 分鐘',
  },
  {
    id: 'stu-4',
    name: '王柏宇',
    program: '新竹早鳥班',
    goal: '5000m sub 19',
    week: 5,
    lastFeedback: '尚未回報',
    readiness: '待追蹤',
    risk: '缺少本週回饋',
    nextWorkout: '400m x 10',
  },
]

export const plannerRows = [
  {
    date: '2026/5/20（4）',
    mon: '休息 + 滾筒',
    tue: 'E 8km',
    wed: '2km E + 5km T + 1km E',
    thu: '肌力 30 分',
    fri: 'E 8km',
    sat: '休息',
    sun: '18km progressive',
  },
  {
    date: '2026/5/27（5）',
    mon: '休息',
    tue: '坡跑 10 組',
    wed: 'E 10km',
    thu: '肌力 + strides',
    fri: 'T 6km',
    sat: '休息',
    sun: '20km LSD',
  },
  {
    date: '2026/6/3（6）',
    mon: '恢復跑 6km',
    tue: '1000m x 5',
    wed: '休息',
    thu: 'E 10km',
    fri: '節奏跑 7km',
    sat: '休息',
    sun: '16km 輕鬆跑',
  },
]
